ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    //柴油
    ctnh.fuel_refining("diesel")
        .inputFluids(Fluid.of("gtceu:heavy_fuel", 4000))
        .inputFluids(Fluid.of("gtceu:light_fuel", 1000))
        .outputFluids(Fluid.of("gtceu:diesel", 10000))
        .EUt(1920)
        .duration(50).blastFurnaceTemp(2273)
    //生物柴油
    ctnh.fuel_refining("bio_diesel1")
        .itemInputs("4x gtceu:sodium_hydroxide_dust")
        .inputFluids(Fluid.of("gtceu:fish_oil", 32000))
        .inputFluids(Fluid.of("gtceu:ethanol", 2000))
        .outputFluids(Fluid.of("gtceu:bio_diesel", 60000))
        .EUt(1920)
        .duration(60).blastFurnaceTemp(2273)
    ctnh.fuel_refining("bio_diesel2")
        .itemInputs("4x gtceu:sodium_hydroxide_dust")
        .inputFluids(Fluid.of("gtceu:seed_oil", 32000))
        .inputFluids(Fluid.of("gtceu:ethanol", 2000))
        .outputFluids(Fluid.of("gtceu:bio_diesel", 60000))
        .EUt(1920)
        .duration(60).blastFurnaceTemp(2273)
    ctnh.fuel_refining("bio_diesel3")
        .itemInputs("4x gtceu:sodium_hydroxide_dust")
        .inputFluids(Fluid.of("gtceu:seed_oil", 32000))
        .inputFluids(Fluid.of("gtceu:methanol", 2000))
        .outputFluids(Fluid.of("gtceu:bio_diesel", 60000))
        .EUt(1920)
        .duration(60).blastFurnaceTemp(2273)
    ctnh.fuel_refining("bio_diesel4")
        .itemInputs("4x gtceu:sodium_hydroxide_dust")
        .inputFluids(Fluid.of("gtceu:fish_oil", 32000))
        .inputFluids(Fluid.of("gtceu:methanol", 2000))
        .outputFluids(Fluid.of("gtceu:bio_diesel", 60000))
        .EUt(1920)
        .duration(60).blastFurnaceTemp(2273)
    //汽油
    ctnh.fuel_refining("gasoline")
        .inputFluids(Fluid.of("gtceu:naphtha", 16000))
        .inputFluids(Fluid.of("gtceu:wood_vinegar", 1000))
        .outputFluids(Fluid.of("gtceu:gasoline", 32000))
        .EUt(1920)
        .duration(60).blastFurnaceTemp(4500)
    //高辛烷值汽油
    ctnh.fuel_refining("high_octane_gasoline")
        .inputFluids(Fluid.of("gtceu:nitrogen", 4000))
        .inputFluids(Fluid.of("gtceu:hydrogen", 20000))
        .inputFluids(Fluid.of("gtceu:gasoline", 20000))
        .outputFluids(Fluid.of("gtceu:high_octane_gasoline", 56000))
        .EUt(1920)
        .duration(80).blastFurnaceTemp(5200)
    //高十六烷值柴油
    ctnh.fuel_refining("cetane_boosted_diesel1")
        .inputFluids(Fluid.of("gtceu:bio_diesel", 12000))
        .inputFluids(Fluid.of("gtceu:nitric_acid", 4000))
        .outputFluids(Fluid.of("gtceu:cetane_boosted_diesel", 26000))
        .EUt(1920)
        .duration(25).blastFurnaceTemp(4500)
    ctnh.fuel_refining("cetane_boosted_diesel2")
        .inputFluids(Fluid.of("gtceu:diesel", 12000))
        .inputFluids(Fluid.of("gtceu:nitric_acid", 4000))
        .outputFluids(Fluid.of("gtceu:cetane_boosted_diesel", 26000))
        .EUt(1920)
        .duration(25).blastFurnaceTemp(4500)
    //高级线圈处理配方
    ctnh.fuel_refining("high_octane_gasoline1")
        .circuit(1)
        .inputFluids(Fluid.of("gtceu:oil_light", 20000))
        .inputFluids(Fluid.of("gtceu:hydrogen", 2000))
        .inputFluids(Fluid.of("gtceu:nitrogen", 1000))
        .outputFluids(Fluid.of("gtceu:high_octane_gasoline", 4000))
        .EUt(6144)
        .duration(15).blastFurnaceTemp(7200)
    ctnh.fuel_refining("high_octane_gasoline2")
        .circuit(2)
        .inputFluids(Fluid.of("gtceu:oil", 15000))
        .inputFluids(Fluid.of("gtceu:hydrogen", 2000))
        .inputFluids(Fluid.of("gtceu:nitrogen", 1000))
        .outputFluids(Fluid.of("gtceu:high_octane_gasoline", 8000))
        .EUt(6144)
        .duration(15).blastFurnaceTemp(7200)
    ctnh.fuel_refining("high_octane_gasoline3")
        .circuit(3)
        .inputFluids(Fluid.of("gtceu:oil_medium", 15000))
        .inputFluids(Fluid.of("gtceu:hydrogen", 4000))
        .inputFluids(Fluid.of("gtceu:nitrogen", 2000))
        .outputFluids(Fluid.of("gtceu:high_octane_gasoline", 16000))
        .EUt(24567)
        .duration(80).blastFurnaceTemp(7200)
    ctnh.fuel_refining("high_octane_gasoline4")
        .circuit(4)
        .inputFluids(Fluid.of("gtceu:oil_heavy", 15000))
        .inputFluids(Fluid.of("gtceu:hydrogen", 8000))
        .inputFluids(Fluid.of("gtceu:nitrogen", 4000))
        .outputFluids(Fluid.of("gtceu:high_octane_gasoline", 24000))
        .EUt(24567)
        .duration(80).blastFurnaceTemp(7200)
    //硅岩燃料的精炼
    ctnh.silica_rock_fuel_refinery("naq1")
        .inputFluids('gtceu:naquadah_based_liquid_fuel 100', 'gtceu:helium_plasma 100')
        .itemInputs('8x gtceu:naquadah_dust', '4x gtceu:palladium_dust')
        .outputFluids('gtceu:nq_fuelmk1 500')
        .EUt(21305)
        .duration(300)
    ctnh.silica_rock_fuel_refinery("naq2")
        .inputFluids('gtceu:nq_fuelmk1 300', 'gtceu:oxygen_plasma 100')
        .itemInputs('8x gtceu:enriched_naquadah_dust', '4x gtceu:ruthenium_dust')
        .outputFluids('gtceu:nq_fuelmk2 200')
        .EUt(393216)
        .duration(450)
        .blastFurnaceTemp(10800)
    ctnh.silica_rock_fuel_refinery("naq3")
        .inputFluids('gtceu:nq_fuelmk2 190', 'gtceu:argon_plasma 100')
        .itemInputs('8x gtceu:naquadria_dust', '4x gtceu:osmium_dust')
        .outputFluids('gtceu:nq_fuelmk3 170')
        .EUt(393216)
        .duration(600)
        .blastFurnaceTemp(10800)
    ctnh.cracker("refuel_radon_cracking_1")
        .inputFluids("gtceu:nq_fuelmk1 1000")
        .inputFluids("gtceu:radon 1000")
        .outputFluids("gtceu:cracking_silica_rock_based_fuel 2000")
        .EUt(122330)
        .duration(300)
    ctnh.cracker("refuel_radon_cracking_2")
        .inputFluids("gtceu:nq_fuelmk2 1000")
        .inputFluids("gtceu:xenon 1000")
        .outputFluids("gtceu:cracking_enriched_silica_rock_based_fuel 2000")
        .EUt(122330)
        .duration(300)
    ctnh.distillation_tower("cracking_fix_1")
        .inputFluids("gtceu:cracking_silica_rock_based_fuel 2000")
        .outputFluids("gtceu:nq_fuelmk2 200", "gtceu:nq_fuelmk3 50", "gtceu:radon 750", "gtceu:fluorine 1000")
        .itemOutputs('8x gtceu:naquadah_nugget')
        .EUt(21430)
        .duration(100)
    ctnh.distillation_tower("cracking_fix_2")
        .inputFluids("gtceu:cracking_enriched_silica_rock_based_fuel 2000")
        .outputFluids("gtceu:nq_fuelmk3 300", "gtceu:nq_fuelmk1 550", "gtceu:xenon 750", "gtceu:fluorine 3000")
        .itemOutputs('8x gtceu:enriched_naquadah_nugget')
        .EUt(21430)
        .duration(100)
    ctnh.fusion_reactor("charged_silica_rock-i")
        .inputFluids("gtceu:nq_fuelmk1 100", "gtceu:nitrogen_plasma 200")
        .outputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_i 100")
        .EUt(8192)
        .fusionStartEU(300000000)
        .duration(50)
    ctnh.fusion_reactor("charged_silica_rock-ii")
        .inputFluids("gtceu:nq_fuelmk2 100", "gtceu:iron_plasma 200")
        .outputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_ii 100")
        .EUt(24102)
        .fusionStartEU(310000000)
        .duration(50)
    ctnh.silica_rock_fuel_refinery("charged_silica_rock-i_1")
        .itemInputs('64x gtceu:sodium_dust','64x gtceu:gelled_toluene')
        .inputFluids("gtceu:nq_fuelmk1 100","gtceu:nitrogen_plasma 100")
        .outputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_i 200")
        .EUt(24102)
        .duration(100)
    ctnh.silica_rock_fuel_refinery("charged_silica_rock-ii_1")
        .itemInputs('64x gtceu:potassium_dust','64x gtceu:gelled_toluene')
        .inputFluids("gtceu:nq_fuelmk2 100", "gtceu:iron_plasma 100")
        .outputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_ii 200")
        .EUt(122330)
        .duration(100)
    ctnh.silica_rock_fuel_refinery("charged_silica_rock-ii_2")
        .itemInputs('64x gtceu:potassium_dust','64x gtceu:gelled_toluene')
        .inputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_i 125", "gtceu:iron_plasma 100")
        .outputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_ii 200")
        .EUt(122330)
        .duration(100)
    ctnh.silica_rock_fuel_refinery("charged_silica_rock-iii")
        .itemInputs('64x gtceu:gelled_toluene','2x gtnn:enriched_uranium','4x gtceu:neutronium_dust')
        .inputFluids("gtceu:nq_fuelmk3 100", "gtceu:radon 1000", "gtceu:nickel_plasma 1000")
        .outputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_iii 125")
        .EUt(2000000)
        .duration(100)
    ctnh.silica_rock_fuel_refinery("charged_silica_rock-iii_1")
        .itemInputs('64x gtceu:gelled_toluene','2x gtnn:enriched_uranium','4x gtceu:neutronium_dust')
        .inputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_ii 100", "gtceu:radon 1000", "gtceu:nickel_plasma 1000")
        .outputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_iii 125")
        .EUt(2000000)
        .duration(100)
    ctnh.silica_rock_fuel_refinery("super_fuel_mki_1")
        .itemInputs('3x gtnn:enriched_thorium','2x gtnn:enriched_uranium','1x gtnn:enriched_plutonium')
        .inputFluids("gtceu:charged_silica_rock_based_fluid_fuel_mk_iii 500", "gtceu:high_energy_fuel 500", "gtceu:neutronium 1000")
        .outputFluids("gtceu:superfuelmk1 250")
        .EUt(8100000)
        .duration(300)
    ctnh.silica_rock_fuel_refinery("high_fuel_too")
        .inputFluids("gtceu:thorium_based_liquid_fuel_excited 1000","gtceu:uranium_based_liquid_fuel_excited 1000","gtceu:plutonium_based_liquid_fuel_excited 1000")
        .itemInputs('gtceu:boundless_dust')
        .outputFluids("gtceu:high_energy_fuel 3000")
        .EUt(2000000)
        .duration(300)
    
})