ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    ctnh.bedrock_drilling_rigs("jiyancheng1")
        .circuit(1)
        .inputFluids("gtceu:drilling_fluid 500")
        .itemOutputs('gtceu:bedrock_dust_dust')
        .outputFluids('gtceu:bedrock_fog', 1000)
        .EUt(491520)
        .duration(100)
    ctnh.cvd("chengqifenli")
        .inputFluids("gtceu:bedrock_fog 1000")
        .itemOutputs('gtceu:bedrock_dust_dust')
        .outputFluids("gtceu:bedrock_fog_re 1000")
        .EUt(122880)
        .duration(50)
    ctnh.mixer("jiyanchenghuijiaoban")
        .chancedInput('2x gtceu:ammonium_chloride_dust', 500, 0)
        .chancedInput('2x gtceu:osmium_dust', 100, 0)
        .inputFluids("gtceu:bedrock_fog_re 1000", "minecraft:water 1000")
        .outputFluids("gtceu:bedrock_dust_solution 1000")
        .EUt(122880)
        .duration(120)
    ctnh.centrifuge("qiyefenli")
        .inputFluids("gtceu:bedrock_dust_solution 3000")
        .outputFluids("gtceu:bedrock_fog_re_h 1000", "gtceu:bedrock_fog_re_m 1000", "gtceu:bedrock_fog_re_l 1000")
        .EUt(122880)
        .duration(240)
    ctnh.centrifuge("qiyefenli1")
        .inputFluids("gtceu:bedrock_fog_re_h 1000")
        .itemOutputs('3x gtceu:iridium_dust', '2x gtceu:osmium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 1000")
        .EUt(122880)
        .duration(140)
    ctnh.centrifuge("qiyefenli2")
        .inputFluids("gtceu:bedrock_fog_re_m 1000")
        .itemOutputs('4x gtceu:ruthenium_dust', '5x gtceu:rhodium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 500")
        .EUt(122880)
        .duration(140)
    ctnh.centrifuge("qiyefenli3")
        .inputFluids("gtceu:bedrock_fog_re_l 1000")
        .itemOutputs('6x gtceu:platinum_dust', '7x gtceu:palladium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 250")
        .EUt(122880)
        .duration(140)
    ctnh.distillery("yanwufenli")
        .inputFluids("gtceu:taranliquid 1000")
        .outputFluids("gtceu:bedrock_smoke 500")
        .itemOutputs('4x gtceu:taranmix_dust')
        .EUt(491520)
        .duration(100)
    ctnh.centrifuge("talanjiejin")
        .inputFluids("gtceu:bedrock_smoke 1000")
        .itemOutputs('2x gtceu:small_taranmix_dust')
        .outputFluids("gtceu:bedrock_smoke_re 1000")
        .duration(200)
        .EUt(491520)
    ctnh.mixer("jiyanwudefenli")
        .inputFluids("gtceu:bedrock_smoke_re 1000", "minecraft:water 1000")
        .chancedInput('2x gtceu:ammonium_chloride_dust', 1000, 0)
        .chancedInput('2x gtceu:naquadria_dust', 500, 0)
        .outputFluids('gtceu:bedrock_soot_solution 1000')
        .EUt(4915200)
        .duration(120)
    ctnh.cracker("fuliehua")
        .inputFluids("gtceu:fluorine 1000", "gtceu:bedrock_soot_solution 1000")
        .outputFluids("gtceu:f_bedrock_smoke_re 2000")
        .EUt(491520)
        .duration(250)
    ctnh.distillation_tower("jiyanyandezhengliu")
        .inputFluids('gtceu:f_bedrock_smoke_re 2000')
        .outputFluids("gtceu:bedrock_smoke_re_l 1000", 'gtceu:bedrock_smoke_re_m 500', 'gtceu:bedrock_smoke_re_h 250', 'gtceu:fluorine 500')
        .itemOutputs('2x gtceu:tiny_taranmix_dust') 
        .EUt(491520)
        .duration(500)
   ctnh.centrifuge("jiyanyanfenli1")
       .inputFluids("gtceu:bedrock_smoke_re_l 1000")
       .outputFluids("gtceu:ax_jiyanqi 100", "gtceu:nq_fuelmk1 750")
       .itemOutputs('3x gtceu:naquadah_oxide_mixture_dust', '8x gtceu:samarium_dust')
       .EUt(1966080)
       .duration(140)
    ctnh.centrifuge("jiyanyanfenli2")
        .inputFluids("gtceu:bedrock_smoke_re_m 1000")
        .outputFluids("gtceu:ax_jiyanqi 200", "gtceu:nq_fuelmk2 450")
        .itemOutputs('3x gtceu:enriched_naquadah_oxide_mixture_dust', '4x gtceu:europium_dust')
        .EUt(1966080)
        .duration(140)
    ctnh.centrifuge("jiyanyanfenli3")
        .inputFluids("gtceu:bedrock_smoke_re_h 1000")
        .outputFluids("gtceu:ax_jiyanqi 300", "gtceu:nq_fuelmk3 150")
        .itemOutputs('3x gtceu:naquadria_oxide_mixture_dust', '2x gtceu:americium_dust')
        .EUt(1966080)
        .duration(140)    
    ctnh.electric_blast_furnace("fangshexingfenli")
        .inputFluids('gtceu:bedrock_gas 1000')
        .circuit(0)
        .itemOutputs('1x gtceu:radioactive_metals_mix_dust')
        .outputFluids('gtceu:bedrock_gas_re 1000')
        .duration(500)
        .EUt(1966080)
        .blastFurnaceTemp(9000)
    ctnh.neutron_activator("jiyanqidehuohua")
        .inputFluids("gtceu:ax_jiyanqi 1000")
        .outputFluids('gtceu:bedrock_gas 1000')
        .itemOutputs('4x gtceu:tiny_radioactive_metals_mix_dust', 'gtceu:tiny_francium_dust', '3x gtceu:small_nuclear_waste_dust', '2x gtceu:small_technetium_dust')
        .duration(100)
        .addCondition($GTNNRecipes.setNA(600, 440))
    ctnh.cracker("jiyanqideliehua")
        .inputFluids("gtceu:bedrock_gas_re 1000", "gtceu:radon 1000")
        .outputFluids("gtceu:dr_bedrock_gas_re 2000")
        .EUt(1966080)
        .duration(500)
    ctnh.distillation_tower("dongliehuachanwu")
        .inputFluids("gtceu:dr_bedrock_gas_re 2000")
        .outputFluids("gtceu:bedrock_gas_re_l 400", "gtceu:bedrock_gas_re_m 250", "gtceu:bedrock_gas_re_h 100", "gtceu:radon 500")
        .EUt(7864320)
        .duration(400)
    ctnh.centrifuge("jiyanqilixing1")
        .inputFluids("gtceu:bedrock_gas_re_l 1000")
        .outputFluids("gtceu:taranliquidfuel_l 1000")
        .chancedOutput('2x gtceu:small_my_infinity_dust', 10, 0)
        .EUt(7864320)
        .duration(500)
    ctnh.centrifuge("jiyanqilixing2")
        .inputFluids("gtceu:bedrock_gas_re_m 1000")
        .outputFluids("gtceu:taranliquidfuel_m 500")
        .chancedOutput('2x gtceu:small_my_infinity_dust', 30, 0)
        .EUt(7864320)
        .duration(500)
    ctnh.centrifuge("jiyanqilixing3")
        .inputFluids("gtceu:bedrock_gas_re_h 1000")
        .outputFluids("gtceu:taranliquidfuel_h 250")
        .chancedOutput('2x gtceu:small_my_infinity_dust', 50, 0)
        .EUt(7864320)
        .duration(500)
        





















})