const $CTNHRecipes = Java.loadClass("io.github.cpearl0.ctnhcore.registry.CTNHRecipes")
ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
        //基岩主线
    ctnh.bedrock_drilling_rigs("bedrock_dust_1")
        .circuit(1)
        .inputFluids("gtceu:drilling_fluid 500")
        .itemOutputs('gtceu:bedrock_dust_dust')
        .outputFluids(Fluid.of('gtceu:bedrock_fog', 1000))
        .EUt(491520)
        .duration(100)
    ctnh.chemical_vapor_deposition("dust_gas_separation")
        .inputFluids("gtceu:bedrock_fog 1000")
        .itemOutputs('gtceu:bedrock_dust_dust')
        .outputFluids("gtceu:bedrock_fog_re 1000")
        .EUt(122880)
        .duration(50)
    ctnh.mixer("bedrock_dust_ash_solution")
        .chancedInput('2x gtceu:ammonium_chloride_dust', 500, 0)
        .chancedInput('2x gtceu:osmium_dust', 100, 0)
        .inputFluids("gtceu:bedrock_fog_re 1000", "minecraft:water 1000")
        .outputFluids("gtceu:bedrock_dust_solution 1000")
        .EUt(122880)
        .duration(120)
    ctnh.centrifuge("gas_liquid_separation_1")
        .inputFluids("gtceu:bedrock_dust_solution 3000")
        .outputFluids("gtceu:bedrock_fog_re_h 1000", "gtceu:bedrock_fog_re_m 1000", "gtceu:bedrock_fog_re_l 1000")
        .EUt(122880)
        .duration(240)
    ctnh.centrifuge("gas_liquid_separation_2")
        .inputFluids("gtceu:bedrock_fog_re_h 1000")
        .itemOutputs('3x gtceu:iridium_dust', '2x gtceu:osmium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 1000")
        .EUt(122880)
        .duration(140)
    ctnh.centrifuge("gas_liquid_separation_3")
        .inputFluids("gtceu:bedrock_fog_re_m 1000")
        .itemOutputs('4x gtceu:ruthenium_dust', '5x gtceu:rhodium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 500")
        .EUt(122880)
        .duration(140)
    ctnh.centrifuge("gas_liquid_separation_4")
        .inputFluids("gtceu:bedrock_fog_re_l 1000")
        .itemOutputs('6x gtceu:platinum_dust', '7x gtceu:palladium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 250")
        .EUt(122880)
        .duration(140)
    ctnh.distillery("smoke_separation")
        .inputFluids("gtceu:taranliquid 1000")
        .outputFluids("gtceu:bedrock_smoke 500")
        .itemOutputs('4x gtceu:taranmix_dust')
        .EUt(491520)
        .duration(100)
    ctnh.centrifuge("taran_crystallization")
        .inputFluids("gtceu:bedrock_smoke 1000")
        .itemOutputs('2x gtceu:small_taranmix_dust')
        .outputFluids("gtceu:bedrock_smoke_re 1000")
        .duration(200)
        .EUt(491520)
    ctnh.mixer("bedrock_fog_separation")
        .inputFluids("gtceu:bedrock_smoke_re 1000", "minecraft:water 1000")
        .chancedInput('2x gtceu:ammonium_chloride_dust', 1000, 0)
        .chancedInput('2x gtceu:naquadria_dust', 500, 0)
        .outputFluids('gtceu:bedrock_soot_solution 1000')
        .EUt(491520)
        .duration(120)
    ctnh.cracker("fluorination")
        .inputFluids("gtceu:fluorine 1000", "gtceu:bedrock_soot_solution 1000")
        .outputFluids("gtceu:f_bedrock_smoke_re 2000")
        .EUt(491520)
        .duration(250)
    ctnh.distillation_tower("bedrock_smoke_distillation")
        .inputFluids('gtceu:f_bedrock_smoke_re 2000')
        .outputFluids("gtceu:bedrock_smoke_re_l 1000", 'gtceu:bedrock_smoke_re_m 500', 'gtceu:bedrock_smoke_re_h 250', 'gtceu:fluorine 500')
        .itemOutputs('2x gtceu:tiny_taranmix_dust')
        .EUt(491520)
        .duration(500)
    ctnh.centrifuge("bedrock_smoke_separation_1")
        .inputFluids("gtceu:bedrock_smoke_re_l 1000")
        .outputFluids("gtceu:ax_jiyanqi 100", "gtceu:nq_fuelmk1 75")
        .itemOutputs('3x gtceu:naquadah_oxide_mixture_dust', '8x gtceu:samarium_dust')
        .EUt(1966080)
        .duration(140)
    ctnh.centrifuge("bedrock_smoke_separation_2")
        .inputFluids("gtceu:bedrock_smoke_re_m 1000")
        .outputFluids("gtceu:ax_jiyanqi 200", "gtceu:nq_fuelmk2 45")
        .itemOutputs('3x gtceu:enriched_naquadah_oxide_mixture_dust', '4x gtceu:europium_dust')
        .EUt(1966080)
        .duration(140)
    ctnh.centrifuge("bedrock_smoke_separation_3")
        .inputFluids("gtceu:bedrock_smoke_re_h 1000")
        .outputFluids("gtceu:ax_jiyanqi 300", "gtceu:nq_fuelmk3 15")
        .itemOutputs('3x gtceu:naquadria_oxide_mixture_dust', '2x gtceu:americium_dust')
        .EUt(1966080)
        .duration(140)
    ctnh.electric_blast_furnace("radioactive_material_separation")
        .inputFluids('gtceu:bedrock_gas 1000')
        .circuit(0)
        .itemOutputs('1x gtceu:radioactive_metals_mix_dust')
        .outputFluids('gtceu:bedrock_gas_re 1000')
        .duration(500)
        .EUt(1966080)
        .blastFurnaceTemp(9000)
    ctnh.neutron_activator("neutron_activation_of_bedrock_gas")
        .inputFluids("gtceu:ax_jiyanqi 1000")
        .outputFluids('gtceu:bedrock_gas 1000')
        .itemOutputs('4x gtceu:tiny_radioactive_metals_mix_dust', 'gtceu:tiny_francium_dust', '3x gtceu:tiny_naquadria_oxide_mixture_dust', '2x gtceu:small_technetium_dust')
        .duration(100)
        .addCondition($CTNHRecipes.setNA(440, 600))
    ctnh.cracker("bedrock_gas_cracking")
        .inputFluids("gtceu:bedrock_gas_re 1000", "gtceu:radon 1000")
        .outputFluids("gtceu:dr_bedrock_gas_re 2000")
        .EUt(1966080)
        .duration(500)
    ctnh.distillation_tower("radon_cracking_distillation")
        .inputFluids("gtceu:dr_bedrock_gas_re 2000")
        .outputFluids("gtceu:bedrock_gas_re_l 400", "gtceu:bedrock_gas_re_m 250", "gtceu:bedrock_gas_re_h 100", "gtceu:radon 500")
        .EUt(7864320)
        .duration(400)
    ctnh.centrifuge("bedrock_gas_centrifugation_1")
        .inputFluids("gtceu:bedrock_gas_re_l 1000")
        .outputFluids("gtceu:taranliquidfuel_l 1000")
        .chancedOutput('gtceu:boundless_dust', 1000, 3000)
        .EUt(7864320)
        .duration(500)
    ctnh.centrifuge("bedrock_gas_centrifugation_2")
        .inputFluids("gtceu:bedrock_gas_re_m 1000")
        .outputFluids("gtceu:taranliquidfuel_m 500")
        .chancedOutput('gtceu:boundless_dust', 3000, 2000)
        .EUt(7864320)
        .duration(500)
    ctnh.centrifuge("bedrock_gas_centrifugation_3")
        .inputFluids("gtceu:bedrock_gas_re_h 1000")
        .outputFluids("gtceu:taranliquidfuel_h 250")
        .chancedOutput('gtceu:boundless_dust', 5000, 1000)
        .EUt(7864320)
        .duration(500)
        //放射性处理产线---基岩支线
    ctnh.mixer("enrichment_of_radioactive_materials")
        .itemInputs('gtceu:plutonium_241_dust', 'gtceu:radioactive_metals_mix_dust', 'gtceu:uranium_235_dust')
        .inputFluids("gtceu:nitration_mixture 4000")
        .itemOutputs('6x gtceu:enrich_radioactive_waste_dust')
        .EUt(491020)
        .duration(100)
    ctnh.large_chemical_reactor("radioactive_particles")
        .circuit(1)
        .itemInputs('gtceu:enrich_radioactive_waste_dust')
        .inputFluids("gtceu:ammonia_monohydrate 1000")
        .outputFluids('gtceu:radioactive_ion_solution 2000')
        .EUt(114514)
        .duration(20)
    ctnh.neutron_activator("neutron_irradiation_of_radioactive_materials")
        .inputFluids('gtceu:radioactive_ion_solution 1000')
        .itemInputs('gtceu:small_neutronium_dust')
        .itemOutputs('2x gtceu:small_americium_dust', '2x gtceu:small_radium_dust', '2x gtceu:small_francium_dust')
        .outputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .duration(100)
        .addCondition($CTNHRecipes.setNA(110, 600))
    ctnh.centrifuge("neutron_substance_separation")
        .inputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .outputFluids('gtceu:radon 8000', 'gtceu:fluorine 16000', 'gtceu:helium_plasma 4000', 'gtceu:nuclear_waste_water 16000')
        .itemOutputs('3x gtceu:radiation_dust_dust', '2x gtceu:small_mendelevium_dust', 'gtceu:small_tritanium_dust')
        .EUt(491020)
        .duration(80)
    ctnh.compressor('radiation_ingot')
        .itemInputs('gtceu:radiation_dust_dust')
        .itemOutputs('gtceu:radioactive_metal_ingot_ingot')
        .EUt(114514)
        .duration(100)
    ctnh.decay_pools('decay_radiation_ingot_1')
        .circuit(0)
        .itemInputs('gtceu:radioactive_metal_ingot_ingot')
        .outputFluids('gtceu:low_level_radioactive_dust 1000', 'gtceu:high_level_radioactive_dust 1000')
        .itemOutputs('6x gtceu:tiny_neutronium_mixture_dust')
        .duration(800)
    ctnh.decay_pools('decay_radiation_ingot_2')
        .circuit(1)
        .itemInputs('gtceu:radioactive_metal_ingot_ingot')
        .outputFluids('gtceu:low_level_radioactive_dust 1000', 'gtceu:high_level_radioactive_dust 1000')
        .itemOutputs('6x gtceu:neutronium_mixture_dust')
        .duration(40)
        .EUt(491020)
    ctnh.electric_blast_furnace('enrichment_of_low_radioactive_materials')
        .inputFluids('gtceu:low_level_radioactive_dust 1000')
        .notConsumable('ctnhcore:neutron_source')
        .outputFluids('gtceu:concentrated_low_level_radioactive_dust 1000')
        .itemOutputs('16x gtceu:americium_dust', '8x gtceu:melodic_alloy_dust')
        .blastFurnaceTemp(9100)
        .EUt(491020)
        .duration(100)
    ctnh.electric_blast_furnace('enrichment_of_high_radioactive_materials')
        .inputFluids('gtceu:high_level_radioactive_dust 1000')
        .notConsumable('ctnhcore:neutron_source')
        .outputFluids('gtceu:concentrated_high_level_radioactive_dust 1000')
        .itemOutputs('16x gtceu:lutetium_dust', '8x gtceu:stellar_alloy_dust')
        .blastFurnaceTemp(9100)
        .EUt(491020)
        .duration(100)
    ctnh.fusion_reactor('aether')
        .inputFluids('gtceu:concentrated_low_level_radioactive_dust 1000', 'gtceu:concentrated_high_level_radioactive_dust 1000')
        .outputFluids('gtceu:aether_plasma 2000')
        .fusionStartEU(600000000)
        .EUt(491020)
        .duration(200)
    ctnh.plasma_generator('aether_ingot')
        .inputFluids("gtceu:aether_plasma 4")
        .outputFluids("gtceu:aether 4")
        .EUt(-491020)
        .duration(300)
    ctnh.centrifuge("nuclear_waste_water_treatment")
        .inputFluids('gtceu:nuclear_waste_water 2000')
        .outputFluids('alexscaves:acid 4000')
        .itemOutputs('1x gtceu:tiny_naquadria_dust')
        .EUt(114514)
        .duration(40)
        //P-507
    ctnh.large_chemical_reactor('2-ethyl_hexanol_1')
        .notConsumable('gtceu:copper_chromium_catalyst_dust')
        .inputFluids('gtceu:diesel 1000')
        .outputFluids('gtceu:2_ethylhexanol 1000')
        .EUt(114514)
        .duration(200)
    ctnh.large_chemical_reactor('2-ethyl_hexanol_2')
        .notConsumable('gtceu:copper_chromium_catalyst_dust')
        .inputFluids('gtceu:seed_oil 500')
        .outputFluids('gtceu:2_ethylhexanol 1000')
        .EUt(114514)
        .duration(200)
    ctnh.chemical_reactor('phosphoric_acid_1')
        .circuit(0)
        .itemInputs('14x gtceu:phosphorus_pentoxide_dust')
        .inputFluids('minecraft:water 6000')
        .outputFluids('gtceu:phosphoric_acid 4000')
        .EUt(16)
        .duration(50)
    ctnh.chemical_reactor('hypo_phosphoric_acid_1')
        .circuit(1)
        .itemInputs('14x gtceu:phosphorus_pentoxide_dust')
        .inputFluids('minecraft:water 3000')
        .outputFluids('gtceu:phosphorous_acid 2000')
        .EUt(120)
        .duration(200)
    ctnh.large_chemical_reactor('dimethyl_hypo_phosphite')
        .inputFluids('gtceu:methanol 2000', 'gtceu:phosphorous_acid 1000')
        .outputFluids('gtceu:dimethyl_phosphite 1000', 'minecraft:water 2000')
        .EUt(1920)
        .duration(200)
    ctnh.large_chemical_reactor('phosphoric_acid_dimethyl_ester_2-ethyl_hexanol')
        .inputFluids('gtceu:dimethyl_phosphite 1000', 'gtceu:2_ethylhexanol 2000')
        .outputFluids('gtceu:methanol 2000', 'gtceu:di_2_ethylhexyl_phosphite 1000')
        .EUt(6144)
        .duration(250)
    ctnh.large_chemical_reactor('chlorinated_cyclohexane')
        .inputFluids('gtceu:chlorine 1000', 'gtceu:cyclohexane 1000')
        .outputFluids('gtceu:chlorocyclohexane 1000', 'gtceu:hydrochloric_acid 1000')
        .EUt(480)
        .duration(50)
    ctnh.large_chemical_reactor('2-chloroethyl_hexanol')
        .inputFluids('gtceu:chlorocyclohexane 1000', 'gtceu:acetone 1000')
        .outputFluids('gtceu:2_ethylhexanol 1000')
        .EUt(24678)
        .duration(100)
    ctnh.large_chemical_reactor('2-cl-yijijichun')
        .inputFluids('gtceu:chlorine 1000', 'gtceu:2_ethylhexanol 1000')
        .outputFluids('gtceu:1_chloro_2_ethylhexane 1000', 'gtceu:hydrochloric_acid 1000')
        .EUt(24678)
        .duration(100)
    ctnh.large_chemical_reactor('phosphonate_ester')
        .circuit(0)
        .inputFluids('gtceu:1_chloro_2_ethylhexane 1000', 'gtceu:di_2_ethylhexyl_phosphite 1000')
        .outputFluids('gtceu:phosphonate 1000')
        .EUt(114514)
        .duration(500)
    ctnh.large_chemical_reactor('beta_phosphonate_ester')
        .circuit(1)
        .inputFluids('gtceu:1_chloro_2_ethylhexane 1000', 'gtceu:di_2_ethylhexyl_phosphite 1000')
        .outputFluids('gtceu:beta_aminophosphonate 1000')
        .EUt(24768)
        .duration(500)
    ctnh.dehydrator('phosphonate_ester_dehydration')
        .inputFluids('gtceu:phosphonate 1000')
        .itemInputs('gtceu:fluid_cell')
        .outputFluids('gtceu:p507_extractant 1000')
        .itemOutputs(Item.of('gtceu:fluid_cell', '{Fluid:{Amount:1000,FluidName:"minecraft:water"}}'))
        .EUt(24768)
        .duration(150)
    ctnh.mixer('copper_chromium_catalyst')
        .circuit(10)
        .itemInputs('gtceu:copper_dust', 'gtceu:chromium_dust')
        .itemOutputs('gtceu:copper_chromium_catalyst_dust')
        .EUt(1920)
        .duration(1000)
        //塔兰金属混合物的处理
    ctnh.distillery('talanchuli0')
        .itemInputs('5x gtceu:taranmix_dust')
        .inputFluids('gtceu:helium_3 1000')
        .outputFluids('gtceu:taranium_dirty_helium3 1000')
        .EUt(24720)
        .duration(100)
    ctnh.centrifuge('taran_processing_1')
        .inputFluids('gtceu:taranium_dirty_helium3 1000')
        .outputFluids('gtceu:taranium_enriched_liquid_helium3 1000', 'gtceu:taranium_half_life_liquid_helium3 1000', 'gtceu:taranium_depleted_liquid_helium3 1000')
        .EUt(122880)
        .duration(100)
    ctnh.centrifuge('taran_processing_2')
        .inputFluids('gtceu:taranium_half_life_liquid_helium3 1000')
        .outputFluids('gtceu:taranium_enriched_liquid_helium3 500', 'gtceu:taranium_depleted_liquid_helium3 500')
        .EUt(122880)
        .duration(200)
    ctnh.fusion_reactor('taran_processing_3')
        .inputFluids('gtceu:taranium_enriched_liquid_helium3 1000', 'gtceu:helium_3 1000')
        .outputFluids('gtceu:taranium_enriched_dirty_helium_plasma_plasma 1000')
        .EUt(122880)
        .duration(100)
        .fusionStartEU(300000000)
    ctnh.centrifuge('taran_processing_4')
        .notConsumable('gtceu:hv_item_magnet')
        .inputFluids('gtceu:taranium_enriched_dirty_helium_plasma_plasma 1000')
        .outputFluids('gtceu:taranium_enriched_helium4_plasma_plasma 1000', 'gtceu:taranium_depleted_helium_plasma_plasma 1000', 'gtceu:hydrogen 8000')
        .EUt(122880)
        .duration(100)
    ctnh.mixer('p-507')
        .inputFluids('gtceu:p507_extractant 1000')
        .itemInputs('gtceu:adamant_mud_dust')
        .outputFluids('gtceu:adamantiteliquid 1000')
        .EUt(24678)
        .duration(100)
    ctnh.distillation_tower('refined_gold_separation')
        .inputFluids('gtceu:adamantiteliquid 1000')
        .itemOutputs('16x gtceu:chalcogen_anode_mud_dust')
        .outputFluids('gtceu:p507_extractant 1000')
        .outputFluids("gtceu:refined_gold_aq 1000")
        .EUt(114514)
        .duration(320)
    ctnh.differential_centrifuge("refined_gold_separation_and_purification")
        .circuit(1)
        .inputFluids("gtceu:refined_gold_aq 1000")
        .itemOutputs('6x gtceu:enriched_naquadah_dust', '3x gtceu:adamantite_dust')
        .EUt(122340)
        .duration(120)
    ctnh.plasma_condenser('taran_processing_5')
        .inputFluids('gtceu:taranium_enriched_helium4_plasma_plasma 1000', 'gtceu:liquid_helium 4000')
        .outputFluids('gtceu:taranium_enriched_liquid_helium4 1000', 'gtceu:helium_plasma 4000')
        .EUt(122340)
        .duration(150)
    ctnh.plasma_condenser('taran_processing_6')
        .inputFluids('gtceu:taranium_depleted_helium_plasma_plasma 1000', 'gtceu:liquid_helium 4000')
        .outputFluids('gtceu:helium_plasma 4000')
        .itemOutputs('8x gtceu:adamant_mud_dust')
        .EUt(122340)
        .duration(150)
    ctnh.centrifuge('taran_processing_7')
        .inputFluids('gtceu:taranium_depleted_liquid_helium3 1000')
        .outputFluids('gtceu:helium_3 333', 'gtceu:red_slurry 16000')
        .itemOutputs('gtceu:taranmix_dust')
        .EUt(24768)
        .duration(120)
    ctnh.chemical_vapor_deposition('taran_processing_8')
        .inputFluids('gtceu:taranium_enriched_liquid_helium4 1000')
        .itemOutputs('2x gtceu:taranium_powder_dust')
        .outputFluids('gtceu:taranium_depleted_liquid_helium 1000')
        .EUt(122340)
        .duration(500)
    ctnh.centrifuge('taran_processing_9')
        .inputFluids('gtceu:taranium_depleted_liquid_helium 1000')
        .itemOutputs('gtceu:adamant_mud_dust')
        .duration(120)
        .EUt(122340)
    ctnh.distillation_tower("refined_gold_fractionation")
        .inputFluids("gtceu:refined_gold_aq_low 1000")
        .outputFluids('gtceu:helium 500', 'gtceu:neon 250', 'gtceu:snow_steel 250')
        .EUt(120)
        .duration(3000)
    ctnh.plasma_condenser("aether_plasma_condensation")
        .inputFluids('gtceu:aether_plasma 1000', 'gtceu:liquid_helium 4000')
        .outputFluids('gtceu:aether 1000', 'gtceu:helium_plasma 4000')
        .EUt(1920152)
        .duration(150)
    ctnh.fusion_reactor('refined_gold_plasma_polymerization')
        .inputFluids('gtceu:adamantite 1000', 'gtceu:nickel_plasma 1000')
        .outputFluids('gtceu:adamantite_plasma 1000')
        .EUt(22468)
        .duration(200)
        .fusionStartEU(300000000)
    ctnh.plasma_condenser('refined_gold_plasma_condensation')
        .notConsumable('gtceu:ingot_casting_mold')
        .inputFluids('gtceu:adamantite_plasma 144', 'gtceu:cryotheum 1000')
        .outputFluids('gtceu:argon_plasma 1000')
        .itemOutputs('gtceu:adamantite_ingot')
        .EUt(1920152)
        .duration(150)
    event.recipes.gtceu.electric_blast_furnace("liquid_platinum")
        .itemInputs('gtceu:adamantite_dust', 'gtceu:saltpeter_dust')
        .outputFluids('gtceu:adamantite 144')
        .blastFurnaceTemp(10800)
        .EUt(491520)
        .duration(100)





















})