ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    //基岩主线
    ctnh.bedrock_drilling_rigs("jiyancheng1")
        .circuit(1)
        .inputFluids("gtceu:drilling_fluid 500")
        .itemOutputs('gtceu:bedrock_dust_dust')
        .outputFluids('gtceu:bedrock_fog', 1000)
        .EUt(491520)
        .duration(100)
    ctnh.cvd("chengqifenli")
        .inputFluids("gtceu:bedrock_fog 1000")
        .itemOutputs('gtceu:bedrock_dust_dust')
        .outputFluids("gtceu:bedrock_fog_re 1000")
        .EUt(122880)
        .duration(50)
    ctnh.mixer("jiyanchenghuijiaoban")
        .chancedInput('2x gtceu:ammonium_chloride_dust', 500, 0)
        .chancedInput('2x gtceu:osmium_dust', 100, 0)
        .inputFluids("gtceu:bedrock_fog_re 1000", "minecraft:water 1000")
        .outputFluids("gtceu:bedrock_dust_solution 1000")
        .EUt(122880)
        .duration(120)
    ctnh.centrifuge("qiyefenli")
        .inputFluids("gtceu:bedrock_dust_solution 3000")
        .outputFluids("gtceu:bedrock_fog_re_h 1000", "gtceu:bedrock_fog_re_m 1000", "gtceu:bedrock_fog_re_l 1000")
        .EUt(122880)
        .duration(240)
    ctnh.centrifuge("qiyefenli1")
        .inputFluids("gtceu:bedrock_fog_re_h 1000")
        .itemOutputs('3x gtceu:iridium_dust', '2x gtceu:osmium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 1000")
        .EUt(122880)
        .duration(140)
    ctnh.centrifuge("qiyefenli2")
        .inputFluids("gtceu:bedrock_fog_re_m 1000")
        .itemOutputs('4x gtceu:ruthenium_dust', '5x gtceu:rhodium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 500")
        .EUt(122880)
        .duration(140)
    ctnh.centrifuge("qiyefenli3")
        .inputFluids("gtceu:bedrock_fog_re_l 1000")
        .itemOutputs('6x gtceu:platinum_dust', '7x gtceu:palladium_dust')
        .chancedOutput('gtceu:small_bedrock_dust_dust', 5000, 0)
        .outputFluids("gtceu:taranliquid 250")
        .EUt(122880)
        .duration(140)
    ctnh.distillery("yanwufenli")
        .inputFluids("gtceu:taranliquid 1000")
        .outputFluids("gtceu:bedrock_smoke 500")
        .itemOutputs('4x gtceu:taranmix_dust')
        .EUt(491520)
        .duration(100)
    ctnh.centrifuge("talanjiejin")
        .inputFluids("gtceu:bedrock_smoke 1000")
        .itemOutputs('2x gtceu:small_taranmix_dust')
        .outputFluids("gtceu:bedrock_smoke_re 1000")
        .duration(200)
        .EUt(491520)
    ctnh.mixer("jiyanwudefenli")
        .inputFluids("gtceu:bedrock_smoke_re 1000", "minecraft:water 1000")
        .chancedInput('2x gtceu:ammonium_chloride_dust', 1000, 0)
        .chancedInput('2x gtceu:naquadria_dust', 500, 0)
        .outputFluids('gtceu:bedrock_soot_solution 1000')
        .EUt(4915200)
        .duration(120)
    ctnh.cracker("fuliehua")
        .inputFluids("gtceu:fluorine 1000", "gtceu:bedrock_soot_solution 1000")
        .outputFluids("gtceu:f_bedrock_smoke_re 2000")
        .EUt(491520)
        .duration(250)
    ctnh.distillation_tower("jiyanyandezhengliu")
        .inputFluids('gtceu:f_bedrock_smoke_re 2000')
        .outputFluids("gtceu:bedrock_smoke_re_l 1000", 'gtceu:bedrock_smoke_re_m 500', 'gtceu:bedrock_smoke_re_h 250', 'gtceu:fluorine 500')
        .itemOutputs('2x gtceu:tiny_taranmix_dust') 
        .EUt(491520)
        .duration(500)
   ctnh.centrifuge("jiyanyanfenli1")
       .inputFluids("gtceu:bedrock_smoke_re_l 1000")
       .outputFluids("gtceu:ax_jiyanqi 100", "gtceu:nq_fuelmk1 750")
       .itemOutputs('3x gtceu:naquadah_oxide_mixture_dust', '8x gtceu:samarium_dust')
       .EUt(1966080)
       .duration(140)
    ctnh.centrifuge("jiyanyanfenli2")
        .inputFluids("gtceu:bedrock_smoke_re_m 1000")
        .outputFluids("gtceu:ax_jiyanqi 200", "gtceu:nq_fuelmk2 450")
        .itemOutputs('3x gtceu:enriched_naquadah_oxide_mixture_dust', '4x gtceu:europium_dust')
        .EUt(1966080)
        .duration(140)
    ctnh.centrifuge("jiyanyanfenli3")
        .inputFluids("gtceu:bedrock_smoke_re_h 1000")
        .outputFluids("gtceu:ax_jiyanqi 300", "gtceu:nq_fuelmk3 150")
        .itemOutputs('3x gtceu:naquadria_oxide_mixture_dust', '2x gtceu:americium_dust')
        .EUt(1966080)
        .duration(140)    
    ctnh.electric_blast_furnace("fangshexingfenli")
        .inputFluids('gtceu:bedrock_gas 1000')
        .circuit(0)
        .itemOutputs('1x gtceu:radioactive_metals_mix_dust')
        .outputFluids('gtceu:bedrock_gas_re 1000')
        .duration(500)
        .EUt(1966080)
        .blastFurnaceTemp(9000)
    ctnh.neutron_activator("jiyanqidehuohua")
        .inputFluids("gtceu:ax_jiyanqi 1000")
        .outputFluids('gtceu:bedrock_gas 1000')
        .itemOutputs('4x gtceu:tiny_radioactive_metals_mix_dust', 'gtceu:tiny_francium_dust', '3x gtceu:small_nuclear_waste_dust', '2x gtceu:small_technetium_dust')
        .duration(100)
        .addCondition($GTNNRecipes.setNA(600, 440))
    ctnh.cracker("jiyanqideliehua")
        .inputFluids("gtceu:bedrock_gas_re 1000", "gtceu:radon 1000")
        .outputFluids("gtceu:dr_bedrock_gas_re 2000")
        .EUt(1966080)
        .duration(500)
    ctnh.distillation_tower("dongliehuachanwu")
        .inputFluids("gtceu:dr_bedrock_gas_re 2000")
        .outputFluids("gtceu:bedrock_gas_re_l 400", "gtceu:bedrock_gas_re_m 250", "gtceu:bedrock_gas_re_h 100", "gtceu:radon 500")
        .EUt(7864320)
        .duration(400)
    ctnh.centrifuge("jiyanqilixing1")
        .inputFluids("gtceu:bedrock_gas_re_l 1000")
        .outputFluids("gtceu:taranliquidfuel_l 1000")
        .chancedOutput('gtceu:boundless_dust', 10, 0)
        .EUt(7864320)
        .duration(500)
    ctnh.centrifuge("jiyanqilixing2")
        .inputFluids("gtceu:bedrock_gas_re_m 1000")
        .outputFluids("gtceu:taranliquidfuel_m 500")
        .chancedOutput('gtceu:boundless_dust', 30, 0)
        .EUt(7864320)
        .duration(500)
    ctnh.centrifuge("jiyanqilixing3")
        .inputFluids("gtceu:bedrock_gas_re_h 1000")
        .outputFluids("gtceu:taranliquidfuel_h 250")
        .chancedOutput('gtceu:boundless_dust', 50, 0)
        .EUt(7864320)
        .duration(500)
    //放射性处理产线---基岩支线
    ctnh.mixer("fujifangshex")
        .itemInputs('gtceu:nuclear_waste_dust', 'gtceu:radioactive_metals_mix_dust')
        .itemOutputs('2x gtceu:enrich_radioactive_waste_dust')
        .EUt(491020)
        .duration(100)
    ctnh.large_chemical_reactor("fangshexinglizi")
        .circuit(1)
        .itemInputs('gtceu:enrich_radioactive_waste_dust')
        .inputFluids("gtceu:ammonium_hydroxide 1000")
        .outputFluids('gtceu:radioactive_ion_solution 2000')
        .EUt(114514)
        .duration(20)
    ctnh.neutron_activator("zhozizhaoshe")
        .inputFluids('gtceu:radioactive_ion_solution 1000')
        .itemInputs('gtceu:small_neutronium_dust')
        .itemOutputs('2x gtceu:small_americium_dust', '2x gtceu:small_radium_dust', '2x gtceu:small_francium_dust')
        .outputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .duration(100)
        .addCondition($GTNNRecipes.setNA(600, 110))
    ctnh.centrifuge("zhozisufengli")
        .inputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .outputFluids('gtceu:radon 8000', 'gtceu:fluorine 16000', 'gtceu:helium_plasma 4000','gtceu:nuclear_waste_water 16000')
        .itemOutputs('3x gtceu:radiation_dust_dust', '2x gtceu:small_mendelevium_dust', 'gtceu:small_tritanium_dust')
        .EUt(491020)
        .duration(80)
    ctnh.compressor('fusheding')
        .itemInputs('gtceu:radiation_dust_dust')
        .itemOutputs('gtceu:radioactive_metal_ingot_ingot')
        .EUt(114514)
        .duration(100)
    ctnh.decay_pools('shuaibianfusheding1')
        .circuit(0)
        .itemInputs('gtceu:radioactive_metal_ingot_ingot')
        .outputFluids('gtceu:low_level_radioactive_dust 1000', 'gtceu:high_level_radioactive_dust 1000')
        .itemOutputs('6x gtceu:tiny_neutronium_mixture_dust')
        .duration(800)
    ctnh.decay_pools('shuaibianfusheding2')
        .circuit(1)
        .itemInputs('gtceu:radioactive_metal_ingot_ingot')
        .outputFluids('gtceu:low_level_radioactive_dust 1000', 'gtceu:high_level_radioactive_dust 1000')
        .itemOutputs('6x gtceu:neutronium_mixture_dust')
        .duration(40)
        .EUt(491020)
    ctnh.electric_blast_furnace('difagshe')
        .inputFluids('gtceu:low_level_radioactive_dust 1000')
        .notConsumable('gtnn:neutron_source')
        .outputFluids('gtceu:concentrated_low_level_radioactive_dust 1000') 
        .itemOutputs('16x gtceu:americium_dust', '8x gtceu:melodic_alloy_dust')
        .blastFurnaceTemp(9100)
        .EUt(491020)
        .duration(100)
    ctnh.electric_blast_furnace('difagshe1')
        .inputFluids('gtceu:high_level_radioactive_dust 1000')
        .notConsumable('gtnn:neutron_source')
        .outputFluids('gtceu:concentrated_high_level_radioactive_dust 1000')
        .itemOutputs('16x gtceu:lutetium_dust', '8x gtceu:stellar_alloy_dust')
        .blastFurnaceTemp(9100)
        .EUt(491020)
        .duration(100)
    ctnh.fusion_reactor('aether')
        .inputFluids('gtceu:concentrated_low_level_radioactive_dust 1000', 'gtceu:concentrated_high_level_radioactive_dust 1000')
        .outputFluids('gtceu:aether_plasma 2000')
        .fusionStartEU(600000000)
        .EUt(491020)
        .duration(200)
    ctnh.plasma_generator('aetherding')
        .inputFluids("gtceu:aether_plasma 4")
        .outputFluids("gtceu:aether 4")
        .EUt(-491020)
        .duration(300)
    ctnh.centrifuge("hefeishuichuli")
        .inputFluids('gtceu:nuclear_waste_water 1000')
        .outputFluids('alexscaves:acid 4000')
        .itemOutputs('2x gtceu:tiny_naquadria_dust')
        .EUt(114514)
        .duration(40)
    //P-507
    ctnh.large_chemical_reactor('2-yijijichun2')
        .notConsumable('gtceu:copper_chromium_catalyst_dust')
        .inputFluids('gtceu:diesel 1000')
        .outputFluids('gtceu:2_ethylhexanol 1000')
        .EUt(114514)
        .duration(200)
    ctnh.large_chemical_reactor('2-yijijichun')
        .notConsumable('gtceu:copper_chromium_catalyst_dust')
        .inputFluids('gtceu:seed_oil 500')
        .outputFluids('gtceu:2_ethylhexanol 1000')
        .EUt(114514)
        .duration(200)
    ctnh.chemical_reactor('linsuan')
        .circuit(0)
        .itemInputs('14x gtceu:phosphorus_pentoxide_dust')
        .inputFluids('minecraft:water 6000')
        .outputFluids('gtceu:phosphoric_acid 4000')
        .EUt(16)
        .duration(50)
    ctnh.chemical_reactor('yalinsuan')
        .circuit(1)
        .itemInputs('14x gtceu:phosphorus_pentoxide_dust')
        .inputFluids('minecraft:water 3000')
        .outputFluids('gtceu:phosphorous_acid 2000')
        .EUt(120)
        .duration(200)
    ctnh.large_chemical_reactor('gtceu:dimethyl_phosphite')
        .inputFluids('gtceu:methanol 2000', 'gtceu:phosphorous_acid 1000')
        .outputFluids('gtceu:dimethyl_phosphite 1000', 'minecraft:water 2000')
        .EUt(1920)
        .duration(200)
    ctnh.large_chemical_reactor('erlinsuanerjiazhiyijijichun')
        .inputFluids('gtceu:dimethyl_phosphite 1000', 'gtceu:2_ethylhexanol 2000')
        .outputFluids('gtceu:methanol 2000', 'gtceu:di_2_ethylhexyl_phosphite 1000')
        .EUt(6144)
        .duration(250)
    ctnh.large_chemical_reactor('lvdaihuanjiwan')
        .inputFluids('gtceu:chlorine 1000', 'gtceu:cyclohexane 1000')
        .outputFluids('gtceu:chlorocyclohexane 1000', 'gtceu:hydrochloric_acid 1000')
        .EUt(480)
        .duration(50)
    ctnh.large_chemical_reactor('2-yijijichun1')
        .inputFluids('gtceu:chlorocyclohexane 1000', 'gtceu:acetone 1000')
        .outputFluids('gtceu:2_ethylhexanol 1000')
        .EUt(24678)
        .duration(100)
    ctnh.large_chemical_reactor('2-cl-yijijichun')
        .inputFluids('gtceu:chlorine 1000', 'gtceu:2_ethylhexanol 1000')
        .outputFluids('gtceu:1_chloro_2_ethylhexane 1000', 'gtceu:hydrochloric_acid 1000')
        .EUt(24678)
        .duration(100)
    ctnh.large_chemical_reactor('linsuanzhi')
        .circuit(0)
        .inputFluids('gtceu:1_chloro_2_ethylhexane 1000', 'gtceu:di_2_ethylhexyl_phosphite 1000')
        .outputFluids('gtceu:phosphonate 1000')
        .EUt(114514)
        .duration(500)
    ctnh.large_chemical_reactor('linsuanzhi1')
        .circuit(1)
        .inputFluids('gtceu:1_chloro_2_ethylhexane 1000', 'gtceu:di_2_ethylhexyl_phosphite 1000')
        .outputFluids('gtceu:beta_aminophosphonate 1000')
        .EUt(24768)
        .duration(500)
    ctnh.dehydrator('linsuanzhituoshui')
        .inputFluids('gtceu:phosphonate 1000')
        .itemInputs('gtceu:fluid_cell')
        .outputFluids('gtceu:p507_extractant 1000')
        .itemOutputs(Item.of('gtceu:fluid_cell', '{Fluid:{Amount:1000,FluidName:"minecraft:water"}}'))
        .EUt(24768)
        .duration(150)
    //塔兰金属混合物的处理
    ctnh.distillery('talanchuli0')
        .itemInputs('5x gtceu:taranmix_dust')
        .inputFluids('gtceu:helium_3 1000')
        .outputFluids('gtceu:taranium_dirty_helium3 1000')
        .EUt(24720)
        .duration(100)
    ctnh.centrifuge('talanchuli1')
        .inputFluids('gtceu:taranium_dirty_helium3 1000')
        .outputFluids('gtceu:taranium_enriched_liquid_helium3 1000', 'gtceu:taranium_half_life_liquid_helium3 1000', 'gtceu:taranium_depleted_liquid_helium3 1000')
        .EUt(122880)
        .duration(100)
    ctnh.centrifuge('talanchuli2')
        .inputFluids('gtceu:taranium_half_life_liquid_helium3 1000')
        .outputFluids('gtceu:taranium_enriched_liquid_helium3 500', 'gtceu:taranium_depleted_liquid_helium3 500')
        .EUt(122880)
        .duration(200)
    ctnh.fusion_reactor('talanchuli3')
        .inputFluids('gtceu:taranium_enriched_liquid_helium3 1000', 'gtceu:helium_3 1000')
        .outputFluids('gtceu:taranium_enriched_dirty_helium_plasma_plasma 1000')
        .EUt(122880)
        .duration(100)
        .fusionStartEU(300000000)
    ctnh.centrifuge('tanlanchuli4')
        .notConsumable('gtceu:hv_item_magnet')
        .inputFluids('gtceu:taranium_enriched_dirty_helium_plasma_plasma 1000')
        .outputFluids('gtceu:taranium_enriched_helium4_plasma_plasma 1000', 'gtceu:taranium_depleted_helium_plasma_plasma 1000', 'gtceu:hydrogen 8000')
        .EUt(122880)
        .duration(100)
    ctnh.mixer('p507ad')
        .inputFluids('gtceu:p507_extractant 1000')
        .itemInputs('gtceu:adamant_mud_dust')
        .outputFluids('gtceu:adamantiteliquid 1000')
        .EUt(24678)
        .duration(100)
    ctnh.differential_centrifuge('adfenli')
        .inputFluids('gtceu:adamantiteliquid 1000')
        .itemOutputs('16x gtceu:chalcogen_anode_mud_dust', '3x gtceu:adamantite_dust')
        .outputFluids('gtceu:p507_extractant 1000')
        .EUt(114514)
        .duration(320)
    ctnh.plasma_condenser('talanchuli5')
        .inputFluids('gtceu:taranium_enriched_helium4_plasma_plasma 1000', 'gtceu:liquid_helium 4000')
        .outputFluids('gtceu:taranium_enriched_liquid_helium4 1000', 'gtceu:helium_plasma 4000')
        .EUt(122340)
        .duration(150)
    ctnh.plasma_condenser('talanchuli6')
        .inputFluids('gtceu:taranium_depleted_helium_plasma_plasma 1000', 'gtceu:liquid_helium 4000')
        .outputFluids('gtceu:helium_plasma 4000')
        .itemOutputs('2x gtceu:adamant_mud_dust')
        .EUt(122340)
        .duration(150)
    ctnh.centrifuge('talanchuli7')
        .inputFluids('gtceu:taranium_depleted_liquid_helium3 1000')
        .outputFluids('gtceu:helium_3 333', 'gtceu:red_slurry 16000')
        .itemOutputs('gtceu:taranmix_dust')
        .EUt(24768)
        .duration(120)
    ctnh.cvd('talanchuli8')
        .inputFluids('gtceu:taranium_enriched_liquid_helium4 1000')
        .outputFluids('2x gtceu:taranium_powder_dust')
        .outputFluids('gtceu:taranium_depleted_liquid_helium 1000')
        .EUt(122340)
        .duration(500)
    ctnh.centrifuge('talanchuli9')
        .inputFluids('gtceu:taranium_depleted_liquid_helium 1000')
        .itemOutputs('gtceu:adamant_mud_dust')
        .duration(120)
        .EUt(122340)
        //结合了nomi gtleisure gtlite和原创的产线处理
        
    
    
    















})