ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    ctnh.electric_blast_furnace("shimoqi")
        .itemInputs('gtceu:graphite_dust')
        .outputFluids("gtceu:graphite_steam 1000")
        .duration(1000)
        .EUt(6144)
        .blastFurnaceTemp(4500)
    ctnh.cvd("shimoxiban")
        .inputFluids("gtceu:graphite_steam 1000")
        .itemInputs('gtceu:stainless_steel_plate')
        .itemOutputs('gtceu:graphite_buxiugang_plate_plate')
        .duration(100)
        .EUt(1920)
    ctnh.thermal_centrifuge("relishimoxi")
        .itemInputs('gtceu:graphite_buxiugang_plate_plate')
        .itemOutputs('6x gtceu:small_graphene_dust')
        .itemOutputs('gtceu:stainless_steel_plate')
        .duration(200)
        .EUt(480)
    ctnh.cvd("shimoxiban1")
        .inputFluids("gtceu:graphite_steam 4000")
        .itemInputs('gtceu:double_stainless_steel_plate')
        .itemOutputs('gtceu:double_graphite_buxiugang_plate_plate')
        .duration(100)
        .EUt(6144)
    ctnh.thermal_centrifuge("relishimoxi1")
        .itemInputs('gtceu:double_graphite_buxiugang_plate_plate')
        .itemOutputs('2x gtceu:graphene_dust')
        .itemOutputs('gtceu:double_stainless_steel_plate')
        .duration(200)
        .EUt(480)
})