ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    ctnh.electric_blast_furnace("shimoqi")//1C 500
        .itemInputs('2x gtceu:graphite_dust')
        .outputFluids("gtceu:graphite_steam 4000")
        .duration(1000)
        .EUt(6144)
        .blastFurnaceTemp(4500)
    ctnh.cvd("shimoxiban")
        .inputFluids("gtceu:graphite_steam 4000")
        .itemInputs('gtceu:iridium_plate')
        .inputFluids("gtceu:nitrogen 1000")
        .itemOutputs('gtceu:graphite_ir_plate_plate')
        .duration(100)
        .EUt(1920)
    ctnh.cvd("shimoxiban1")
        .inputFluids("gtceu:graphite_steam 8000")
        .itemInputs('gtceu:double_iridium_plate')
        .inputFluids("gtceu:nitrogen 2000")
        .itemOutputs('gtceu:double_graphite_ir_plate_plate')
        .duration(100)
        .EUt(6144)
    ctnh.chemical_reactor("yibanfenli1")
        .itemInputs('2x gtceu:graphite_ir_plate_plate')
        .inputFluids("gtceu:hydrochloric_acid 6000")
        .outputFluids("gtceu:hydrogen 6000")
        .itemOutputs('2x gtceu:iridium_chloride_dust', "2x gtceu:graphene_dust")
        .duration(200)
        .EUt(1920)
    ctnh.chemical_reactor("yibanfenli2")
        .itemInputs('2x gtceu:double_graphite_ir_plate_plate')
        .inputFluids("gtceu:hydrochloric_acid 12000")
        .outputFluids("gtceu:hydrogen 12000")
        .itemOutputs('4x gtceu:iridium_chloride_dust', "4x gtceu:graphene_dust")
    ctnh.assembler("shimoxi")
        .itemInputs(['8x gtceu:graphite_dust', '1x gtceu:duct_tape'])
        .itemOutputs(['6x gtceu:small_graphene_dust'])
        .EUt(480)
        .duration(180)
    ctnh.centrifuge("jingshuzha")
        .itemInputs('gtceu:metal_sludge_dust')
        .itemOutputs('gtceu:nickel_dust', 'gtceu:copper_dust')
        .duration(80)
        .EUt(480)
    ctnh.electric_blast_furnace("shimoqi1")
        .itemInputs('24x gtceu:fluid_cell')
        .inputFluids("gtceu:methane 6000")//6C 3000
        .outputFluids("gtceu:graphite_steam 3000")
        .itemOutputs(Item.of('gtceu:fluid_cell', 24, '{Fluid:{Amount:1000,FluidName:"gtceu:hydrogen"}}'))
        .EUt(480)
        .duration(200)
        .blastFurnaceTemp(2200)
})