ServerEvents.recipes(event => {
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_andradite' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_ferrosilite' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_wollastonite' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_obsidian' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_talc' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_soapstone' })
    event.remove({ id: 'gtceu:electrolyzer/bentonite_electrolysis' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_asbestos' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_uvarovite' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_fullers_earth' })
    event.replaceOutput({ id: 'gtceu:electrolyzer/zeolite_electrolysis' }, 'gtceu:aluminium_dust', 'gtceu:alumina_dust')
    event.replaceOutput({ id: 'gtceu:electrolyzer/zeolite_electrolysis' }, 'gtceu:silicon_dust', 'gtceu:silicon_dioxide_dust')
    event.replaceOutput({ id: 'gtceu:centrifuge/decomposition_centrifuging__redstone' }, 'gtceu:silicon_dust', 'gtceu:silicon_dioxide_dust')
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_silicon_dioxide' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_silicon_fluoride' })



    event.recipes.gtceu.electrolyzer('andradite')//钙铁榴石
        .EUt(60)
        .duration(480)
        .itemInputs('20x gtceu:andradite_dust')
        .itemOutputs(['2x gtceu:iron_dust', '3x gtceu:calcium_dust', '9x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('gtceu:oxygen', 6000))
    event.recipes.gtceu.electrolyzer('ferrosilite')//铁辉石
        .EUt(60)
        .duration(120)
        .itemInputs('5x gtceu:ferrosilite_dust')
        .itemOutputs(['gtceu:iron_dust', '3x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('gtceu:oxygen', 1000))
    event.recipes.gtceu.electrolyzer('wollastonite')//钙辉石
        .EUt(60)
        .duration(110)
        .itemInputs('5x gtceu:wollastonite_dust')
        .itemOutputs(['gtceu:calcium_dust', '3x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('gtceu:oxygen', 1000))
    event.recipes.gtceu.electrolyzer('obsidian')//黑曜石 
        .EUt(60)
        .duration(192)
        .itemInputs('8x gtceu:obsidian_dust')
        .itemOutputs(['gtceu:iron_dust', 'gtceu:magnesium_dust', '6x gtceu:silicon_dioxide_dust'])
    event.recipes.gtceu.electrolyzer('talc')//滑石 
        .EUt(60)
        .duration(378)
        .itemInputs('21x gtceu:talc_dust')
        .itemOutputs(['3x gtceu:magnesium_dust', '12x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('gtceu:oxygen', 4000))
        .outputFluids(Fluid.of('gtceu:hydrogen', 2000))
    event.recipes.gtceu.electrolyzer('soapstone')//皂石
        .EUt(60)
        .duration(378)
        .itemInputs('21x gtceu:soapstone_dust')
        .itemOutputs(['3x gtceu:magnesium_dust', '12x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('gtceu:oxygen', 4000))
        .outputFluids(Fluid.of('gtceu:hydrogen', 2000))
    event.recipes.gtceu.electrolyzer('bentonite')//膨润土
        .EUt(60)
        .duration(480)
        .itemInputs('30x gtceu:bentonite_dust')
        .itemOutputs(['gtceu:sodium_dust', '6x gtceu:magnesium_dust', '36x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('minecraft:water', 5000))
        .outputFluids(Fluid.of('gtceu:hydrogen', 6000))
    event.recipes.gtceu.electrolyzer('asbestos')//石棉粉 
        .EUt(60)
        .duration(252)
        .itemInputs('18x gtceu:asbestos_dust')
        .itemOutputs(['3x gtceu:magnesium_dust', '6x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('gtceu:oxygen', 5000))
        .outputFluids(Fluid.of('gtceu:hydrogen', 4000))
    event.recipes.gtceu.electrolyzer('uvarovite')//钙铬榴石 
        .EUt(360)
        .duration(480)
        .itemInputs('20x gtceu:uvarovite_dust')
        .itemOutputs(['3x gtceu:calcium_dust', '2x gtceu:chromium_dust', '9x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('gtceu:oxygen', 6000))
    event.recipes.gtceu.electrolyzer('fullers_earth')//漂白土
        .EUt(60)
        .duration(336)
        .itemInputs('21x gtceu:fullers_earth_dust')
        .itemOutputs(['gtceu:magnesium_dust', '12x gtceu:silicon_dioxide_dust'])
        .outputFluids(Fluid.of('gtceu:oxygen', 3000))
        .outputFluids(Fluid.of('gtceu:hydrogen', 1000))
        .outputFluids(Fluid.of('minecraft:water', 4000))

    //二氧化硅处理
    event.recipes.gtceu.chemical_reactor('silicon_dioxide_reduction')
        .EUt(300)
        .duration(200)
        .itemInputs(['3x gtceu:silicon_dioxide_dust', '2x gtceu:carbon_dust'])
        .itemOutputs('gtceu:silicon_dust')
        .outputFluids(Fluid.of('gtceu:carbon_monoxide', 2000))

    event.recipes.gtceu.chemical_reactor('silicon_dioxide_chloride')
        .EUt(30)
        .duration(40)
        .itemInputs(['3x gtceu:silicon_dioxide_dust'])
        .inputFluids(Fluid.of('gtceu:hydrochloric_acid', 4000))
        .outputFluids(Fluid.of('gtceu:silicon_chloride', 1000))
        .outputFluids(Fluid.of('minecraft:water', 2000))

    event.recipes.gtceu.chemical_reactor('silicon_from_sodium')
        .EUt(30)
        .duration(40)
        .itemInputs(['4x gtceu:sodium_dust'])
        .inputFluids(Fluid.of('gtceu:silicon_chloride', 1000))
        .itemOutputs('8x gtceu:salt_dust')
        .itemOutputs('gtceu:silicon_dust')

    event.recipes.gtceu.chemical_reactor('silicon_from_potassium')
        .EUt(30)
        .duration(40)
        .itemInputs(['4x gtceu:potassium_dust'])
        .inputFluids(Fluid.of('gtceu:silicon_chloride', 1000))
        .itemOutputs('8x gtceu:rock_salt_dust')
        .itemOutputs('gtceu:silicon_dust')

    event.recipes.gtceu.chemical_reactor('silicon_from_sodium2')
        .EUt(30)
        .duration(40)
        .itemInputs(['4x gtceu:sodium_dust'])
        .inputFluids(Fluid.of('gtceu:silicon_fluoride', 1000))
        .itemOutputs('8x gtceu:sodium_fluoride_dust')
        .itemOutputs('gtceu:silicon_dust')
})