ServerEvents.recipes(event =>{
    let ctnh = event.recipes.gtceu
    // Kapton K

    ctnh.chemical_reactor('dimethylformamide')
        .inputFluids(Fluid.of('gtceu:carbon_monoxide',1000))
        .inputFluids(Fluid.of('gtceu:dimethylamine',1000))
        .outputFluids(Fluid.of('gtceu:dimethylformamide',1000))
        .duration(200)
        .EUt(480)

    ctnh.chemical_reactor('pyrometillic_dianhydride')
        .inputFluids(Fluid.of('gtceu:oxygen',1500))
        .inputFluids(Fluid.of('gtceu:toluene',250))
        .outputFluids(Fluid.of('gtceu:pyrometillic_dianhydride',250))
        .outputFluids(Fluid.of('minecraft:water',1500))
        .duration(400)
        .EUt(480)

    ctnh.chemical_reactor('oxydianiline_sludge')
        .inputFluids(Fluid.of('gtceu:aminophenol',1000))
        .inputFluids(Fluid.of('gtceu:nitrochlorobenzene',1000))
        .inputFluids(Fluid.of('gtceu:dimethylformamide',1000))
        .itemInputs('gtceu:potassium_carbonate_dust')
        .outputFluids(Fluid.of('gtceu:oxydianiline_sludge',250))
        .outputFluids(Fluid.of('minecraft:water',1500))
        .duration(400)
        .EUt(480) 

    ctnh.distillation_tower('distill_oxydianiline_sludge')
        .inputFluids(Fluid.of('gtceu:oxydianiline_sludge',1000))
        .outputFluids(Fluid.of('gtceu:dimethylformamide',1000))
        .outputFluids(Fluid.of('gtceu:oxydianiline',144))
        .duration(200)
        .EUt(480)

    ctnh.chemical_reactor('kapton_k')
        .inputFluids(Fluid.of('gtceu:pyrometillic_dianhydride',1000))
        .inputFluids(Fluid.of('gtceu:oxydianiline',1000))
        .outputFluids(Fluid.of('gtceu:kapton_k',1000))
        .duration(400)
        .EUt(480)    

// Kapton E coming soon:tm:
/*
* ortho-Xylene, 3 Oxygen, Palladium (Cata (consumed)) -> biphenyltetracarboxylic acid dianhydride (BPDA) (C16H6O6), 3 Water (heater), Hydrogen (skips a step: Phthalic Anhydride (C6H4(CO)2O))
*
*/

// Kevlar
    ctnh.chemical_reactor('cobalt_bromide')
        .itemInputs('gtceu:cobalt_dust')
        .inputFluids(Fluid.of('gtceu:bromine',1000))
        .inputFluids(Fluid.of('gtceu:acetic_acid',1000))
        .outputFluids(Fluid.of('gtceu:cobalt_bromide',1000))
        .duration(60)
        .EUt(480)

    ctnh.chemical_reactor('manganese_bromide')
        .itemInputs('gtceu:manganese_dust')
        .inputFluids(Fluid.of('gtceu:bromine',1000))
        .inputFluids(Fluid.of('gtceu:acetic_acid',1000))
        .outputFluids(Fluid.of('gtceu:manganese_bromide',1000))
        .duration(60)
        .EUt(480)

    ctnh.chemical_reactor('manganese_acetate')
        .itemInputs('gtceu:manganese_dust')
        .inputFluids(Fluid.of('gtceu:acetic_acid',1000))
        .outputFluids(Fluid.of('gtceu:manganese_acetate',1000))
        .duration(60)
        .EUt(480)

    ctnh.chemical_reactor('hydrobromic_acid')
        .notConsumable('gtceu:platinum_dust')
        .inputFluids(Fluid.of('minecraft:water',1000))
        .inputFluids(Fluid.of('gtceu:bromine',1000))
        .inputFluids(Fluid.of('gtceu:hydrogen',1000))
        .outputFluids(Fluid.of('gtceu:hydrobromic_acid',1000))
        .duration(60)
        .EUt(480)

    ctnh.large_chemical_reactor('co_mn_br_catalyst')
        .inputFluids(Fluid.of('gtceu:manganese_bromide',1000))
        .inputFluids(Fluid.of('gtceu:manganese_acetate',1000))
        .inputFluids(Fluid.of('gtceu:hydrobromic_acid',1000))
        .inputFluids(Fluid.of('gtceu:cobalt_bromide',1000))
        .outputFluids(Fluid.of('gtceu:co_mn_br_catalyst',4000))
        .duration(100)
        .EUt(480)

    ctnh.chemical_reactor('bis_trichloromethyl_benzene')
        .inputFluids(Fluid.of('gtceu:dimethylbenzene',1000))
        .inputFluids(Fluid.of('gtceu:chlorine',12000))
        .outputFluids(Fluid.of('gtceu:bis_trichloromethyl_benzene',1000))
        .outputFluids(Fluid.of('gtceu:hydrochloric_acid',6000))
        .duration(60)
        .EUt(480)

    ctnh.chemical_reactor('therephthalic_acid')
        .inputFluids(Fluid.of('gtceu:dimethylbenzene',1000))
        .inputFluids(Fluid.of('gtceu:oxygen',2000))
        .inputFluids(Fluid.of('gtceu:co_mn_br_catalyst',1000))
        .outputFluids(Fluid.of('gtceu:terephthalic_acid',1000))
        .outputFluids(Fluid.of('minecraft:water',1000))
        .duration(60)
        .EUt(480)

    ctnh.chemical_reactor('terephthaloyl_chloride')
        .inputFluids(Fluid.of('gtceu:bis_trichloromethyl_benzene',1000))
        .inputFluids(Fluid.of('gtceu:terephthalic_acid',1000))
        .outputFluids(Fluid.of('gtceu:terephthaloyl_chloride',2000))
        .outputFluids(Fluid.of('gtceu:hydrochloric_acid',1000))
        .duration(60)
        .EUt(480)

    ctnh.chemical_reactor('nitroaniline')
        .inputFluids(Fluid.of('gtceu:nitrochlorobenzene',1000))
        .inputFluids(Fluid.of('gtceu:ammonia',2000))
        .outputFluids(Fluid.of('gtceu:nitroaniline',1000))
        .itemOutputs('gtceu:ammonium_chloride_dust')
        .duration(60)
        .EUt(480)

    ctnh.chemical_reactor('para_phenylenediamine')
        .inputFluids(Fluid.of('gtceu:nitroaniline',1000))
        .inputFluids(Fluid.of('gtceu:hydrogen',6000))
        .outputFluids(Fluid.of('gtceu:para_phenylenediamine',1000))
        .outputFluids(Fluid.of('minecraft:water',3000))
        .duration(60)
        .EUt(480)

    ctnh.chemical_reactor('para_aramid')
        .inputFluids(Fluid.of('gtceu:para_phenylenediamine',1000))
        .inputFluids(Fluid.of('gtceu:terephthaloyl_chloride',1000))
        .outputFluids(Fluid.of('gtceu:para_aramid',1000))
        .outputFluids(Fluid.of('gtceu:hydrochloric_acid',2000))
        .duration(200)
        .EUt(480)

    ctnh.assembler('space_fabric')
        .itemInputs('4x gtceu:polytetrafluoroethylene_foil')
        .itemInputs('4x gtceu:para_aramid_foil')
        .itemInputs('4x gtceu:polyphenylene_sulfide_foil')
        .itemInputs('4x gtceu:fiber_glass_dust')
        .itemOutputs('kubejs:space_fabric')
        .duration(100).EUt(480)
})