ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
//催化剂配方
    ctnh.centrifuge('catalyst')
    .itemInputs('60x gtceu:stone_dust')
    .notConsumable('kubejs:stone_process_catalyst')
    .itemOutputs('gtceu:tiny_inert_residues_dust')
    .itemOutputs('2x gtceu:small_oxidized_residues_dust')
    .itemOutputs('2x gtceu:small_heavy_oxidized_residues_dust')
    .itemOutputs('gtceu:small_magnetite_dust')
    .inputFluids(Fluid.of('gtceu:hydrofluoric_acid',12000))
    .outputFluids(Fluid.of('gtceu:red_mud',75))
    .outputFluids(Fluid.of('gtceu:fluorosilicic_acid',2000))
    .EUt(480)
    .duration(200)
//产线配方   
    ctnh.mixer('dirty_hexafluorosilicic_acid')
        .itemInputs('24x gtceu:stone_dust')
        .inputFluids(Fluid.of('gtceu:hydrofluoric_acid', 6000))
        .outputFluids(Fluid.of('gtceu:dirty_hexafluorosilicic_acid', 3000))
        .EUt(100)
        .duration(40)

    ctnh.centrifuge('dilute_hexafluorosilicic_acid')
        .inputFluids(Fluid.of('gtceu:dirty_hexafluorosilicic_acid', 3000))
        .outputFluids(Fluid.of('gtceu:dilute_hexafluorosilicic_acid', 3000))
        .itemOutputs('12x gtceu:stone_residue_dust')
        .duration(40)
        .EUt(100)

    ctnh.distillation_tower('fluorosilicic_acid')
        .inputFluids(Fluid.of('gtceu:dilute_hexafluorosilicic_acid', 3000))
        .outputFluids(Fluid.of('minecraft:water', 2000))
        .outputFluids(Fluid.of('gtceu:fluorosilicic_acid', 1000))
        .duration(160)
        .EUt(200)

    ctnh.chemical_reactor('uncommon_residues_dust')
        .itemInputs('24x gtceu:stone_residue_dust')
        .itemOutputs('gtceu:uncommon_residues_dust')
        .itemOutputs('gtceu:small_magnetite_dust')
        .inputFluids(Fluid.of('gtceu:sodium_hydroxide_solution', 1000))
        .outputFluids(Fluid.of('gtceu:sodium_hydroxide_solution', 925))
        .outputFluids(Fluid.of('gtceu:red_mud', 75))
        .duration(40)
        .EUt(100)

    ctnh.vacuum_freezer('liquid_fluorine')
        .inputFluids(Fluid.of('gtceu:fluorine', 1000))
        .outputFluids(Fluid.of('gtceu:liquid_fluorine', 1000))
        .EUt(1920)
        .duration(240)

    ctnh.chemical_reactor('dioxygendifluoride')
        .inputFluids(Fluid.of('gtceu:liquid_oxygen', 2000))
        .inputFluids(Fluid.of('gtceu:liquid_fluorine', 2000))
        .outputFluids(Fluid.of('gtceu:dioxygendifluoride', 1000))
        .duration(80)
        .EUt(200)

    ctnh.chemical_reactor('partially_oxidized_residues_dust')
        .itemInputs('gtceu:uncommon_residues_dust')
        .itemOutputs('gtceu:partially_oxidized_residues_dust')
        .inputFluids(Fluid.of('gtceu:dioxygendifluoride', 1000))
        .duration(80)
        .EUt(100)

    ctnh.centrifuge('oxidized_residual_solution')
        .itemInputs('10x gtceu:partially_oxidized_residues_dust')
        .itemOutputs('gtceu:inert_residues_dust')
        .inputFluids(Fluid.of('gtceu:distilled_water', 10000))
        .outputFluids(Fluid.of('gtceu:oxidized_residual_solution', 10000))
        .duration(200)
        .EUt(100)

    ctnh.dehydrator('oxidized_residues_dust')
        .itemOutputs('gtceu:oxidized_residues_dust')
        .itemOutputs('gtceu:heavy_oxidized_residues_dust')
        .inputFluids(Fluid.of('gtceu:oxidized_residual_solution', 2000))
        .duration(80)
        .EUt(3000)

    ctnh.electric_blast_furnace('metallic_residues_dust')
        .itemInputs('10x gtceu:oxidized_residues_dust')
        .itemOutputs('gtceu:metallic_residues_dust')
        .inputFluids(Fluid.of('gtceu:hydrogen', 60000))
        .outputFluids(Fluid.of('gtceu:dilute_hydrofluoric_acid', 40000))
        .duration(1600)
        .EUt(2000)
        .blastFurnaceTemp(3500)

    ctnh.electric_blast_furnace('heavy_metallic_residues_dust')
        .itemInputs('10x gtceu:heavy_oxidized_residues_dust')
        .itemOutputs('gtceu:heavy_metallic_residues_dust')
        .inputFluids(Fluid.of('gtceu:hydrogen', 60000))
        .outputFluids(Fluid.of('gtceu:dilute_hydrofluoric_acid', 40000))
        .duration(1600)
        .EUt(2000)
        .blastFurnaceTemp(3500)

    ctnh.distillation_tower('hydrofluoric_acid')
        .inputFluids(Fluid.of('gtceu:dilute_hydrofluoric_acid', 2000))
        .outputFluids(Fluid.of('minecraft:water', 1000))
        .outputFluids(Fluid.of('gtceu:hydrofluoric_acid', 1000))
        .duration(80)
        .EUt(200)

    ctnh.mana_seperator('metallic_residues_dust_seperate')
        .itemInputs('10x gtceu:metallic_residues_dust')
        .itemOutputs('3x gtceu:diamagnetic_residues_dust')
        .itemOutputs('3x gtceu:paramagnetic_residues_dust')
        .itemOutputs('3x gtceu:ferromagnetic_residues_dust')
        .itemOutputs('gtceu:uncommon_residues_dust')
        .duration(80)
        .EUt(8000)

    ctnh.mana_seperator('heavy_metallic_residues_dust_seperate')
        .itemInputs('10x gtceu:heavy_metallic_residues_dust')
        .itemOutputs('3x gtceu:heavy_diamagnetic_residues_dust')
        .itemOutputs('3x gtceu:heavy_paramagnetic_residues_dust')
        .itemOutputs('3x gtceu:heavy_ferromagnetic_residues_dust')
        .itemOutputs('gtceu:exotic_heavy_residues_dust')
        .duration(80)
        .EUt(8000)

    ctnh.centrifuge('ferromagnetic_residues_dust')
        .itemInputs('6x gtceu:ferromagnetic_residues_dust')
        .itemOutputs('gtceu:small_iron_dust')
        .itemOutputs('gtceu:small_nickel_dust')
        .itemOutputs('gtceu:small_cobalt_dust')
        .duration(100)
        .EUt(3000)

    ctnh.centrifuge('diamagnetic_residues_dust')
        .itemInputs('6x gtceu:diamagnetic_residues_dust')
        .itemOutputs('gtceu:small_calcium_dust')
        .itemOutputs('gtceu:small_zinc_dust')
        .itemOutputs('gtceu:small_copper_dust')
        .itemOutputs('gtceu:small_gallium_dust')
        .itemOutputs('gtceu:small_beryllium_dust')
        .itemOutputs('gtceu:small_tin_dust')
        .duration(100)
        .EUt(3000)

    ctnh.centrifuge('paramagnetic_residues_dust')
        .itemInputs('6x gtceu:paramagnetic_residues_dust')
        .itemOutputs('gtceu:small_sodium_dust')
        .itemOutputs('gtceu:small_potassium_dust')
        .itemOutputs('gtceu:small_magnesium_dust')
        .itemOutputs('gtceu:small_titanium_dust')
        .itemOutputs('gtceu:small_vanadium_dust')
        .itemOutputs('gtceu:small_manganese_dust')
        .duration(100)
        .EUt(3000)

    ctnh.centrifuge('heavy_paramagnetic_residues_dust')
        .itemInputs('6x gtceu:heavy_paramagnetic_residues_dust')
        .itemOutputs('gtceu:small_thorium_dust')
        .itemOutputs('gtceu:small_uranium_dust')
        .itemOutputs('gtceu:small_tungsten_dust')
        .itemOutputs('gtceu:small_hafnium_dust')
        .itemOutputs('gtceu:small_tantalum_dust')
        .itemOutputs('gtceu:small_thallium_dust')
        .duration(100)
        .EUt(3000)

    ctnh.centrifuge('heavy_diamagnetic_residues_dust')
        .itemInputs('6x gtceu:heavy_diamagnetic_residues_dust')
        .itemOutputs('gtceu:small_lead_dust')
        .itemOutputs('gtceu:small_cadmium_dust')
        .itemOutputs('gtceu:small_indium_dust')
        .itemOutputs('gtceu:small_gold_dust')
        .itemOutputs('gtceu:small_bismuth_dust')
        .outputFluids(Fluid.of('gtceu:mercury', 36))
        .duration(120)
        .EUt(3000)

    ctnh.centrifuge('heavy_ferromagnetic_residues_dust')
        .itemInputs('6x gtceu:heavy_ferromagnetic_residues_dust')
        .itemOutputs('gtceu:small_dysprosium_dust')
        .duration(120)
        .EUt(3000)

    // MIXER_RECIPES.recipeBuilder()
    //         .fluidInputs(DistilledWater.getFluid(2000))
    //         .inputs(ExoticHeavyResidues.getItemStack(16))
    //         .input(dust, SodiumHydroxide, 3)
    //         .inputs(PROTONATED_FULLERENE_SIEVING_MATRIX.getStackForm())
    //         .fluidOutputs(SodiumHydroxideSolution.getFluid(1000))
    //         .outputs(SATURATED_FULLERENE_SIEVING_MATRIX.getStackForm())
    //         .duration(40)
    //         .EUt(2000000)
    //         .buildAndRegister();

    ctnh.large_chemical_reactor('clean_inert_residues')
        .itemInputs('10x gtceu:inert_residues_dust')
        .notConsumableFluid(Fluid.of('gtceu:fluoroantimonic_acid', 1000))
        .itemOutputs('10x gtceu:clean_inert_residues_dust')
        .itemOutputs('gtceu:naquadah_oxide_mixture_dust')
        .duration(320)
        .EUt(200)

    // CHEMICAL_RECIPES.recipeBuilder()
    //         .fluidInputs(Tritium.getFluid(1000))
    //         .fluidInputs(Hydrogen.getFluid(1000))
    //         .fluidOutputs(TritiumHydride.getFluid(1000))
    //         .duration(160)
    //         .EUt(2000)
    //         .buildAndRegister();

    // DISTILLATION_RECIPES.recipeBuilder()
    //         .fluidInputs(TritiumHydride.getFluid(10000))
    //         .fluidOutputs(Helium3Hydride.getFluid(100))
    //         .fluidOutputs(TritiumHydride.getFluid(9900))
    //         .duration(800)
    //         .EUt(200)
    //         .buildAndRegister();

    // MIXER_RECIPES.recipeBuilder()
    //         .inputs(CleanInertResidues.getItemStack())
    //         .fluidInputs(Helium3Hydride.getFluid(1000))
    //         .fluidOutputs(UltraacidicResidueSolution.getFluid(1000))
    //         .duration(160)
    //         .EUt(2000)
    //         .buildAndRegister();

    // LARGE_CHEMICAL_RECIPES.recipeBuilder()
    //         .fluidInputs(UltraacidicResidueSolution.getFluid(2000))
    //         .fluidInputs(LiquidOxygen.getFluid(4000))
    //         .fluidInputs(LiquidXenon.getFluid(1000))
    //         .fluidOutputs(XenicAcid.getFluid(1000))
    //         .fluidOutputs(DustyLiquidHelium3.getFluid(2000))
    //         .duration(120)
    //         .EUt(2000)
    //         .buildAndRegister();

    // // 2 H2XeO4 -> 2 Xe + H2O + H2O2 + O3 + 2 O
    // ELECTROLYZER_RECIPES.recipeBuilder()
    //         .fluidInputs(XenicAcid.getFluid(2000))
    //         .fluidOutputs(Xenon.getFluid(2000))
    //         .fluidOutputs(Water.getFluid(1000))
    //         .fluidOutputs(Ozone.getFluid(1000))
    //         .fluidOutputs(HydrogenPeroxide.getFluid(1000))
    //         .fluidOutputs(Oxygen.getFluid(2000))
    //         .duration(120)
    //         .EUt(500)
    //         .buildAndRegister();

    // CENTRIFUGE_RECIPES.recipeBuilder()
    //         .fluidInputs(DustyLiquidHelium3.getFluid(1000))
    //         .fluidOutputs(TaraniumEnrichedLHelium3.getFluid(100))
    //         .fluidOutputs(TaraniumSemidepletedLHelium3.getFluid(300))
    //         .fluidOutputs(TaraniumDepletedLHelium3.getFluid(600))
    //         .duration(400)
    //         .EUt(3000)
    //         .buildAndRegister();

    // FUSION_RECIPES.recipeBuilder()
    //         .fluidInputs(TaraniumEnrichedLHelium3.getFluid(1000))
    //         .fluidInputs(Helium3.getFluid(1000))
    //         .fluidOutputs(TaraniumRichDustyHeliumPlasma.getFluid(3000))
    //         .duration(160)
    //         .EUt(7680)
    //         .EUToStart(480000000)
    //         .buildAndRegister();

    // LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
    //         .fluidInputs(TaraniumRichDustyHeliumPlasma.getFluid(3000))
    //         .notConsumable(SEPARATION_ELECTROMAGNET.getStackForm())
    //         .fluidOutputs(TaraniumRichHelium4.getPlasma(500))
    //         .fluidOutputs(Hydrogen.getPlasma(2000))
    //         .fluidOutputs(TaraniumDepletedHeliumPlasma.getFluid(500))
    //         .duration(80)
    //         .EUt(2000)
    //         .buildAndRegister();

    // MIXER_RECIPES.recipeBuilder()
    //         .fluidInputs(Helium3.getPlasma(1000))
    //         .fluidInputs(TaraniumDepletedLHelium3.getFluid(1000))
    //         .fluidOutputs(TaraniumDepletedHeliumPlasma.getFluid(2000))
    //         .duration(160)
    //         .EUt(2000)
    //         .buildAndRegister();

    // LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
    //         .fluidInputs(TaraniumDepletedHeliumPlasma.getFluid(10000))
    //         .notConsumable(SEPARATION_ELECTROMAGNET.getStackForm())
    //         .fluidOutputs(Helium3.getPlasma(10000))
    //         .outputs(CleanInertResidues.getItemStack(2))
    //         .duration(160)
    //         .EUt(2000)
    //         .buildAndRegister();

    // CENTRIFUGE_RECIPES.recipeBuilder()
    //         .fluidInputs(TaraniumSemidepletedLHelium3.getFluid(1000))
    //         .fluidOutputs(TaraniumEnrichedLHelium3.getFluid(100))
    //         .fluidOutputs(TaraniumDepletedLHelium3.getFluid(900))
    //         .duration(400)
    //         .EUt(3000)
    //         .buildAndRegister();

    // CENTRIFUGE_RECIPES.recipeBuilder()
    //         .fluidInputs(TaraniumRichHelium4.getFluid(400))
    //         .output(dust, Taranium)
    //         .fluidOutputs(TaraniumPoorLiquidHelium.getFluid(400))
    //         .duration(20)
    //         .EUt(8000)
    //         .buildAndRegister();

    // MIXER_RECIPES.recipeBuilder()
    //         .fluidInputs(TaraniumPoorLiquidHelium.getFluid(1000))
    //         .fluidInputs(LiquidHelium3.getFluid(200))
    //         .fluidOutputs(TaraniumPoorLiquidHeliumMix.getFluid(1200))
    //         .duration(80)
    //         .EUt(8000)
    //         .buildAndRegister();

    // CENTRIFUGE_RECIPES.recipeBuilder()
    //         .fluidInputs(TaraniumPoorLiquidHeliumMix.getFluid(1200))
    //         .fluidOutputs(LiquidHelium.getFluid(1000))
    //         .fluidOutputs(DustyLiquidHelium3.getFluid(200))
    //         .duration(80)
    //         .EUt(8000)
    //         .buildAndRegister();

    // PLASMA_CONDENSER_RECIPES.recipeBuilder()
    //         .fluidInputs(LiquidHelium.getFluid(100))
    //         .fluidInputs(TaraniumRichHelium4.getPlasma(1000))
    //         .fluidOutputs(TaraniumRichHelium4.getFluid(1000))
    //         .fluidOutputs(Helium.getFluid(100))
    //         .notConsumable(new IntCircuitIngredient(1))
    //         .duration(80)
    //         .EUt(8000)
    //         .buildAndRegister();

    // PLASMA_CONDENSER_RECIPES.recipeBuilder()
    //         .fluidInputs(LiquidHelium.getFluid(100))
    //         .fluidInputs(Hydrogen.getPlasma(1000))
    //         .fluidOutputs(Hydrogen.getFluid(1000))
    //         .fluidOutputs(Helium.getFluid(100))
    //         .notConsumable(new IntCircuitIngredient(1))
    //         .duration(80)
    //         .EUt(8000)
    //         .buildAndRegister();

    // VACUUM_RECIPES.recipeBuilder().duration(30).EUt(480)
    //         .fluidInputs(fluorine.getFluid(1000))
    //         .fluidOutputs(Liquidfluorine.getFluid(1000))
    //         .buildAndRegister();

    // VACUUM_RECIPES.recipeBuilder().duration(30).EUt(480)
    //         .fluidInputs(Xenon.getFluid(1000))
    //         .fluidOutputs(LiquidXenon.getFluid(1000))
    //         .buildAndRegister();

    // FLUID_HEATER_RECIPES.recipeBuilder()
    //         .fluidInputs(Helium3.getFluid(1000))
    //         .fluidOutputs(Helium3.getPlasma(1000))
    //         .circuitMeta(0)
    //         .duration(60)
    //         .EUt(8000)
    //         .buildAndRegister();
})