name = "Create New Horizon"
author = "mo_guang"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8bb1551ea89cafc091e13b4dd1c5324db18ae2c128cfe2fe35408647e476cf5"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
