name = "Create New Horizon"
author = "mo_guang"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c476482c08eefb3132a317981b77b20b3be552fc43268476808b8e7e939316fd"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
