name = "Create New Horizon"
author = "mo_guang"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63f004918553e6bb684755afd24d3b99a2351fe607cbe1c591798b8c498f0637"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
