ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    ctnh.circuit_assembler("color_ulv")
        .itemInputs('32x gtceu:plastic_printed_circuit_board')
        .itemInputs('kubejs:colorful_soc')
        .itemInputs('gtceu:red_alloy_block')
        .itemInputs('gtceu:soldering_alloy_block')
        .inputFluids('gtceu:living_metal 72')
        .itemOutputs('8192x gtceu:nand_chip')
        .EUt(32678 * 16 * 4)
        .duration(1)
    ctnh.circuit_assembler("color_mv")
        .itemInputs('128x gtceu:plastic_printed_circuit_board')
        .itemInputs('kubejs:colorful_soc')
        .itemInputs('gtceu:red_alloy_block')
        .itemInputs('gtceu:annealed_copper_block')
        .inputFluids('gtceu:living_metal 72')
        .itemOutputs('2048x gtceu:micro_processor')
        .EUt(32678 * 16 * 4)
        .duration(1)
    ctnh.circuit_assembler("color_lv")
        .itemInputs('64x gtceu:plastic_printed_circuit_board')
        .itemInputs('kubejs:colorful_soc')
        .itemInputs('gtceu:soldering_alloy_block')
        .itemInputs('gtceu:annealed_copper_block')
        .inputFluids('gtceu:living_metal 72')
        .itemOutputs('4096x gtceu:microchip_processor')
        .EUt(32678 * 16 * 4)
        .duration(1)
    ctnh.circuit_assembler("color_hv")
        .itemInputs('32x gtceu:epoxy_printed_circuit_board')
        .itemInputs('kubejs:colorful_soc')
        .itemInputs('gtceu:electrum_block')
        .itemInputs('gtceu:platinum_block')
        .inputFluids('gtceu:living_metal 144')
        .itemOutputs('1024x gtceu:nano_processor')
        .EUt(32678 * 16 * 4)
        .duration(1)
    ctnh.circuit_assembler("color_ev")
        .itemInputs('32x gtceu:multilayer_fiber_reinforced_printed_circuit_board')
        .itemInputs('kubejs:colorful_soc')
        .itemInputs('gtceu:niobium_titanium_block')
        .itemInputs('gtceu:platinum_block')
        .inputFluids('gtceu:living_metal 288')
        .itemOutputs('512x gtceu:quantum_processor')
        .EUt(32678 * 16 * 4)
        .duration(1)
    ctnh.circuit_assembler("color_iv")
        .itemInputs('12x gtceu:multilayer_fiber_reinforced_printed_circuit_board')
        .itemInputs('kubejs:colorful_soc')
        .itemInputs('gtceu:niobium_titanium_block')
        .itemInputs('gtceu:yttrium_barium_cuprate_block')
        .inputFluids('gtceu:living_metal 288')
        .itemOutputs('128x gtceu:crystal_processor')
        .EUt(32678 * 16 * 4)
        .duration(1)
    ctnh.circuit_assembler("color_luv")
        .itemInputs('8x gtceu:wetware_printed_circuit_board')
        .itemInputs('kubejs:colorful_soc')
        .itemInputs('gtceu:naquadah_block')
        .itemInputs('gtceu:yttrium_barium_cuprate_block')
        .inputFluids('gtceu:living_metal 432')
        .itemOutputs('64x gtceu:wetware_processor')
        .EUt(32678 * 16 * 4)
        .duration(1)
    ctnh.circuit_assembler("color_zpm")
        .itemInputs('4x kubejs:echo_printed_circuit_board')
        .itemInputs('kubejs:colorful_soc')
        .itemInputs('gtceu:enriched_naquadah_trinium_europium_duranide_block')
        .itemInputs('gtceu:bedrock_neutronium_block')
        .inputFluids('gtceu:living_metal 864')
        .itemOutputs('32x kubejs:echo_processor')
        .EUt(32678 * 16 * 4)
        .duration(1)
    ctnh.laser_sorter_recipe("colorful_gem")
        .itemInputs('gtceu:exquisite_ruby_gem')
        .itemInputs('gtceu:exquisite_sapphire_gem')
        .itemInputs('gtceu:exquisite_emerald_gem')
        .itemInputs('gtceu:exquisite_topaz_gem')
        .itemInputs('gtceu:exquisite_zircon_gem')
        .itemInputs('gtceu:exquisite_magneto_resonatic_gem')
        .itemOutputs('gtceu:exquisite_colorful_gem_gem')
        .EUt(32678 * 16 * 4)
        .duration(100)
        .addData("cwut", 64)
    ctnh.assembly_line('gtceu:exquisite_colorful_gem_gem')
        .itemInputs('gtceu:exquisite_colorful_gem_gem')
        .itemInputs('gtceu:exquisite_arcane_crystal_gem')
        .itemInputs('gtceu:exquisite_tungstencu_diamond_plating_gem')
        .itemInputs('gtceu:exquisite_quartzite_gem')
        .itemInputs('gtceu:exquisite_certus_quartz_gem')
        .itemInputs('gtceu:exquisite_diamond_gem')
        .itemInputs('gtceu:crystal_soc')
        .itemInputs('gtceu:highly_advanced_soc_wafer')
        .itemOutputs('kubejs:colorful_soc')
        .inputFluids('gtceu:mystery_fluid 1000')
        .inputFluids('gtceu:quantum_alloy 1000')
        .inputFluids('gtceu:bedrock_neutronium 1000')
        .inputFluids('gtceu:living_metal 288')
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2000)
})