ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    event.recipes.gtceu.accelerator_upmode('gtceu:acidic_enriched_naquadah_solution1')
        .inputFluids(Fluid.of('gtceu:acidic_enriched_naquadah_solution', 16000))
        .addData("type", "nu")
        .addData("speed", 4000)
        .outputFluids(Fluid.of('gtceu:impure_naquadria_solution', 1500))
        .itemOutputs('18x gtceu:enriched_naquadah_sulfate_dust')
        .EUt(32678)
        .duration(20)
    event.recipes.gtceu.accelerator_downmode('gtceu:acidic_enriched_naquadah_solution2')
        .inputFluids(Fluid.of('gtceu:acidic_enriched_naquadah_solution', 16000))
        .addData("type", "nu")
        .addData("speed", 4000)
        .outputFluids(Fluid.of('gtceu:impure_naquadria_solution', 1500))
        .itemOutputs('18x gtceu:enriched_naquadah_sulfate_dust')
        .EUt(32678)
        .duration(20)

    event.recipes.gtceu.accelerator_downmode('gtceu:naquadah_oxide_mixture_dust1')
        .itemInputs('4x gtceu:naquadah_oxide_mixture_dust')
        .addData("type", "nu")
        .addData("speed", 3000)
        .itemOutputs('2x gtceu:naquadah_dust')
        .itemOutputs('2x gtceu:titanium_dust')
        .EUt(32678)
        .duration(20)
    event.recipes.gtceu.accelerator_upmode('gtceu:naquadah_oxide_mixture_dust2')
        .itemInputs('4x gtceu:naquadah_oxide_mixture_dust')
        .addData("type", "nu")
        .addData("speed", 3000)
        .itemOutputs('2x gtceu:naquadah_dust')
        .itemOutputs('2x gtceu:titanium_dust')
        .EUt(32678)
        .duration(20)

    event.recipes.gtceu.accelerator_upmode('uranium_based_liquid_fuel1')
        .inputFluids(Fluid.of('gtceu:uranium_based_liquid_fuel', 4000))
        .notConsumable('gtceu:neutron_reflector')
        .addData("type", "nu")
        .addData("speed", 7500)
        .outputFluids(Fluid.of('gtceu:uranium_based_liquid_fuel_excited', 4000))
        .EUt(32678)
        .duration(80)
    event.recipes.gtceu.accelerator_downmode('uranium_based_liquid_fuel2')
        .inputFluids(Fluid.of('gtceu:uranium_based_liquid_fuel', 4000))
        .notConsumable('gtceu:neutron_reflector')
        .addData("type", "nu")
        .addData("speed", 7500)
        .outputFluids(Fluid.of('gtceu:uranium_based_liquid_fuel_excited', 4000))
        .EUt(32678)
        .duration(80)
    ctnh.accelerator_downmode("neutron_activation_of_bedrock_gas2")
        .inputFluids("gtceu:ax_jiyanqi 1000")
        .outputFluids('gtceu:bedrock_gas 1000')
        .itemOutputs('4x gtceu:tiny_radioactive_metals_mix_dust', 'gtceu:tiny_francium_dust', '3x gtceu:tiny_naquadria_oxide_mixture_dust', '2x gtceu:small_technetium_dust')
        .duration(20)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 12500)
    ctnh.accelerator_upmode("neutron_activation_of_bedrock_gas1")
        .inputFluids("gtceu:ax_jiyanqi 1000")
        .outputFluids('gtceu:bedrock_gas 1000')
        .itemOutputs('4x gtceu:tiny_radioactive_metals_mix_dust', 'gtceu:tiny_francium_dust', '3x gtceu:tiny_naquadria_oxide_mixture_dust', '2x gtceu:small_technetium_dust')
        .duration(20)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 12500)
    ctnh.accelerator_upmode("neutron_irradiation_of_radioactive_materials2")
        .inputFluids('gtceu:radioactive_ion_solution 1000')
        .itemInputs('gtceu:small_neutronium_dust')
        .itemOutputs('2x gtceu:small_americium_dust', '2x gtceu:small_radium_dust', '2x gtceu:small_francium_dust')
        .outputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .duration(20)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 12500)
    ctnh.accelerator_downmode("neutron_irradiation_of_radioactive_materials1")
        .inputFluids('gtceu:radioactive_ion_solution 1000')
        .itemInputs('gtceu:small_neutronium_dust')
        .itemOutputs('2x gtceu:small_americium_dust', '2x gtceu:small_radium_dust', '2x gtceu:small_francium_dust')
        .outputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .duration(20)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 12500)
    event.recipes.gtceu.accelerator_downmode('twist_power_mana1')
        .itemInputs('20x gtceu:twist_mana_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 1500))
        .itemOutputs('20x gtceu:twist_power_mana_dust')
        .duration(10)
        .addData("type", "nu")
        .addData("speed", 5000)
        .EUt(32678)
    event.recipes.gtceu.accelerator_upmode('twist_power_mana2')
        .itemInputs('20x gtceu:twist_mana_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 1500))
        .itemOutputs('20x gtceu:twist_power_mana_dust')
        .duration(10)
        .addData("type", "nu")
        .addData("speed", 5000)
        .EUt(32678)
    event.recipes.gtceu.accelerator_downmode('gtceu:acidic_naquadria_caesiumfluoride1')
        .inputFluids(Fluid.of('gtceu:acidic_naquadria_caesiumfluoride', 1800))
        .itemOutputs('8x gtceu:naquadria_sulfate_dust')
        .itemOutputs('8x gtceu:caesium_dust')
        .addData("type", "nu")
        .addData("speed", 9000)
        .outputFluids('gtceu:fluorine 18000')
        .duration(20)
        .EUt(131072)
    event.recipes.gtceu.accelerator_upmode('gtceu:acidic_naquadria_caesiumfluoride2')
        .inputFluids(Fluid.of('gtceu:acidic_naquadria_caesiumfluoride', 1800))
        .itemOutputs('8x gtceu:naquadria_sulfate_dust')
        .itemOutputs('8x gtceu:caesium_dust')
        .addData("type", "nu")
        .addData("speed", 9000)
        .outputFluids('gtceu:fluorine 18000')
        .duration(20)
        .EUt(131072)
    event.recipes.gtceu.assembly_line('widespeedingpipe')
        .itemOutputs('5x ctnhcore:widespeedingpipe')
        .itemInputs('5x gtceu:neutron_reflector')
        .itemInputs('5x gtnn:high_speed_pipe_block')
        .itemInputs('8x gtceu:neutronium_plate')
        .itemInputs('4x gtnn:plate_radiation_protection')
        .itemInputs('gtceu:uhv_hermetic_casing')
        .itemInputs('2x #gtceu:circuits/uv')
        .duration(80)
        .EUt(524288)
        .stationResearch(b => b.researchStack(Item.of('gtnn:high_speed_pipe_block'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UV])
            .CWUt(32))
    ctnh.assembly_line('ctnhcore:wideparticleaccelerator')
        .itemOutputs('ctnhcore:wideparticleaccelerator')
        .itemInputs('4x gtceu:luv_field_generator')
        .itemInputs('2x gtceu:zpm_field_generator')
        .itemInputs('8x gtceu:iv_field_generator')
        .itemInputs('64x gtceu:neutron_reflector')
        .itemInputs("8x kubejs:strongly_interacting_neutron_refector")
        .itemInputs("16x gtceu:bedrock_neutronium_gear")
        .itemInputs('16x gtnn:quark_core')
        .itemInputs('64x gtnn:plate_radiation_protection')
        .inputFluids(Fluid.of('gtceu:bedrock_neutronium', 20000))
        .inputFluids(Fluid.of('gtceu:naquadria', 20000))
        .duration(400)
        .EUt(524288)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:widespeedingpipe'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UV])
            .CWUt(48))
    ctnh.accelerator_downmode('na22')
        .itemInputs('8x gtceu:sodium')
        .notConsumable("kubejs:strongly_interacting_neutron_refector")
        .addData("type", "nu")
        .addData("speed", 20000)
        .duration(80)
        .EUt(524288)
        .itemOutputs('6x gtceu:sodium22')
    ctnh.accelerator_upmode('una2')
        .itemInputs('8x gtceu:sodium')
        .notConsumable("kubejs:strongly_interacting_neutron_refector")
        .addData("type", "nu")
        .addData("speed", 20000)
        .duration(80)
        .EUt(524288)
        .itemOutputs('6x gtceu:sodium22')
    ctnh.accelerator_downmode("neutron_irradiation_of_radioactive_materials")
        .inputFluids('gtceu:radioactive_ion_solution 1000')
        .itemInputs('gtceu:small_neutronium_dust')
        .itemOutputs('2x gtceu:small_americium_dust', '2x gtceu:small_radium_dust', '2x gtceu:small_francium_dust')
        .outputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .duration(100)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 5000)
    ctnh.accelerator_upmode("neutron_irradiation_of_radioactive_materials")
        .inputFluids('gtceu:radioactive_ion_solution 1000')
        .itemInputs('gtceu:small_neutronium_dust')
        .itemOutputs('2x gtceu:small_americium_dust', '2x gtceu:small_radium_dust', '2x gtceu:small_francium_dust')
        .outputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .duration(100)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 5000)
    ctnh.assembly_line('kubejs:strongly_interacting_neutron_refector')
        .itemOutputs('kubejs:strongly_interacting_neutron_refector')
        .itemInputs('8x gtceu:neutron_reflector')
        .itemInputs('8x gtceu:double_bedrock_neutronium_plate')
        .itemInputs('8x gtceu:naquadria_plate')
        .itemInputs('8x gtnn:plate_radiation_protection')
        .inputFluids('gtceu:molten_naquadah_alloy 1024')
        .inputFluids('gtceu:lubricant 1024')
        .EUt(114514)
        .duration(1000)
        .stationResearch(b => b.researchStack(Item.of('kubejs:strongly_interacting_neutron_refector'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UV])
            .CWUt(48))

})