ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    event.recipes.gtceu.accelerator_upmode('gtceu:acidic_enriched_naquadah_solution1')
        .inputFluids(Fluid.of('gtceu:acidic_enriched_naquadah_solution', 16000))
        .addData("type", "nu")
        .addData("speed", 4000)
        .outputFluids(Fluid.of('gtceu:impure_naquadria_solution', 1500))
        .itemOutputs('18x gtceu:enriched_naquadah_sulfate_dust')
        .EUt(32678)
        .duration(20)

    event.recipes.gtceu.accelerator_upmode('gtceu:naquadah_oxide_mixture_dust2')
        .itemInputs('4x gtceu:naquadah_oxide_mixture_dust')
        .addData("type", "nu")
        .addData("speed", 3000)
        .itemOutputs('2x gtceu:naquadah_dust')
        .itemOutputs('2x gtceu:titanium_dust')
        .EUt(32678)
        .duration(20)

    event.recipes.gtceu.accelerator_upmode('uranium_based_liquid_fuel1')
        .inputFluids(Fluid.of('gtceu:uranium_based_liquid_fuel', 4000))
        .notConsumable('gtceu:neutron_reflector')
        .addData("type", "nu")
        .addData("speed", 7500)
        .outputFluids(Fluid.of('gtceu:uranium_based_liquid_fuel_excited', 4000))
        .EUt(32678)
        .duration(80)
    ctnh.accelerator_upmode("neutron_activation_of_bedrock_gas1")
        .inputFluids("gtceu:ax_jiyanqi 1000")
        .outputFluids('gtceu:bedrock_gas 1000')
        .itemOutputs('4x gtceu:tiny_radioactive_metals_mix_dust', 'gtceu:tiny_francium_dust', '3x gtceu:tiny_naquadria_oxide_mixture_dust', '2x gtceu:small_technetium_dust')
        .duration(20)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 12500)
    ctnh.accelerator_upmode("neutron_irradiation_of_radioactive_materials2")
        .inputFluids('gtceu:radioactive_ion_solution 1000')
        .itemInputs('gtceu:small_neutronium_dust')
        .itemOutputs('2x gtceu:small_americium_dust', '2x gtceu:small_radium_dust', '2x gtceu:small_francium_dust')
        .outputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .duration(20)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 12500)
    event.recipes.gtceu.accelerator_upmode('twist_power_mana2')
        .itemInputs('20x gtceu:twist_mana_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 1500))
        .itemOutputs('20x gtceu:twist_power_mana_dust')
        .duration(10)
        .addData("type", "nu")
        .addData("speed", 5000)
        .EUt(32678)
    event.recipes.gtceu.accelerator_upmode('gtceu:acidic_naquadria_caesiumfluoride2')
        .inputFluids(Fluid.of('gtceu:acidic_naquadria_caesiumfluoride', 1800))
        .itemOutputs('8x gtceu:naquadria_sulfate_dust')
        .itemOutputs('8x gtceu:caesium_dust')
        .addData("type", "nu")
        .addData("speed", 9000)
        .outputFluids('gtceu:fluorine 18000')
        .duration(20)
        .EUt(131072)
    event.recipes.gtceu.assembly_line('widespeedingpipe')
        .itemOutputs('5x ctnhcore:widespeedingpipe')
        .itemInputs('5x gtceu:neutron_reflector')
        .itemInputs('5x ctnhcore:high_speed_pipe_block')
        .itemInputs('8x gtceu:neutronium_plate')
        .itemInputs('4x ctnhcore:plate_radiation_protection')
        .itemInputs('gtceu:uhv_hermetic_casing')
        .itemInputs('2x #gtceu:circuits/uv')
        .duration(80)
        .EUt(524288)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:high_speed_pipe_block'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UV])
            .CWUt(32))
    ctnh.assembly_line('wide_particle_accelerator')
        .itemOutputs('ctnhcore:wide_particle_accelerator')
        .itemInputs('4x gtceu:luv_field_generator')
        .itemInputs('2x gtceu:zpm_field_generator')
        .itemInputs('8x gtceu:iv_field_generator')
        .itemInputs('64x gtceu:neutron_reflector')
        .itemInputs("8x kubejs:strongly_interacting_neutron_refector")
        .itemInputs("16x gtceu:bedrock_neutronium_gear")
        .itemInputs('16x ctnhcore:quark_core')
        .itemInputs('64x ctnhcore:plate_radiation_protection')
        .inputFluids(Fluid.of('gtceu:bedrock_neutronium', 20000))
        .inputFluids(Fluid.of('gtceu:naquadria', 20000))
        .duration(400)
        .EUt(524288)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:widespeedingpipe'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UV])
            .CWUt(48))
    ctnh.accelerator_upmode('na2')
        .itemInputs('8x gtceu:sodium_dust')
        .notConsumable("kubejs:strongly_interacting_neutron_refector")
        .addData("type", "nu")
        .addData("speed", 30000)
        .duration(300)
        .EUt(524288)
        .itemOutputs('6x gtceu:sodium22_dust')

    ctnh.accelerator_upmode("neutron_irradiation_of_radioactive_materials")
        .inputFluids('gtceu:radioactive_ion_solution 1000')
        .itemInputs('gtceu:small_neutronium_dust')
        .itemOutputs('2x gtceu:small_americium_dust', '2x gtceu:small_radium_dust', '2x gtceu:small_francium_dust')
        .outputFluids('gtceu:neutron_irradiation_of_radioactive_waste 1000')
        .duration(100)
        .EUt(131072)
        .addData("type", "nu")
        .addData("speed", 5000)
    ctnh.assembly_line('kubejs:strongly_interacting_neutron_refector')
        .itemOutputs('kubejs:strongly_interacting_neutron_refector')
        .itemInputs('8x gtceu:neutron_reflector')
        .itemInputs('8x gtceu:double_bedrock_neutronium_plate')
        .itemInputs('8x gtceu:naquadria_plate')
        .itemInputs('8x ctnhcore:plate_radiation_protection')
        .inputFluids('gtceu:molten_naquadah_alloy 1024')
        .inputFluids('gtceu:lubricant 1024')
        .EUt(114514)
        .duration(1000)
        .stationResearch(b => b.researchStack(Item.of('gtceu:dense_iridium_plate'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UV])
            .CWUt(48))
    ctnh.mixer('gtceu:bedrock_neutronium_dust')
        .itemInputs('gtceu:bedrock_dust_dust')
        .itemInputs('gtceu:neutronium_dust')
        .itemInputs('gtceu:naquadria_dust')
        .itemOutputs('gtceu:bedrock_neutronium_dust')
        .outputFluids('gtceu:naquadah 72')
        .itemOutputs('gtceu:bedrock_neutronium_dust')
        .EUt(32678 * 8)
        .duration(200)
    ctnh.assembly_line('kubejs:adamantite_proton_source')
        .itemOutputs('kubejs:adamantite_proton_source')
        .itemInputs('64x gtceu:adamantite_dust')
        .itemInputs('64x gtceu:adamantite_dust')
        .itemInputs('64x gtceu:adamantite_dust')
        .itemInputs('8x kubejs:strongly_interacting_neutron_refector')
        .inputFluids('gtceu:aether_plasma 2000')
        .inputFluids('gtceu:molten_ruthenium_trinium_americium_neutronate 2000')
        .inputFluids('gtceu:bedrock_neutronium 2000')
        .inputFluids('gtceu:naquadria 2000')
        .EUt(2097152)
        .duration(400)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:neutron_source'))
            .dataStack(Item.of('gtceu:data_module'))
            .EUt(GTValues.VA[GTValues.UHV])
            .CWUt(96))
    ctnh.accelerator_upmode('kubejs:constrained_electron_deficient_atom_neutronium')
        .itemOutputs('kubejs:constrained_electron_deficient_atom_neutronium')
        .itemInputs('128x gtceu:neutronium_dust')
        .itemInputs('gtceu:gravi_star')
        .circuit(1)
        .notConsumable('kubejs:strongly_interacting_neutron_refector')
        .addData("type", "element")
        .addData("speed", 30000)
        .EUt(1048576)
        .duration(400)
    ctnh.accelerator_upmode('kubejs:constrained_proton_deficient_atom_neutronium_broken')
        .itemOutputs('kubejs:constrained_proton_deficient_atom_neutronium_broken')
        .notConsumable('kubejs:adamantite_proton_source')
        .itemInputs('128x gtceu:neutronium_dust')
        .itemInputs('gtceu:gravi_star')
        .circuit(2)
        .notConsumable('kubejs:strongly_interacting_neutron_refector')
        .addData("type", "proton")
        .addData("speed", 30000)
        .EUt(1048576)
        .duration(400)
    ctnh.accelerator_upmode('kubejs:constrained_proton_deficient_atom_neutronium')
        .itemInputs('kubejs:constrained_proton_deficient_atom_neutronium_broken')
        .itemOutputs('kubejs:constrained_proton_deficient_atom_neutronium')
        .itemInputs('16x gtceu:neutronium_dust')
        .itemInputs('gtceu:gravi_star')
        .inputFluids('gtceu:bedrock_neutronium 20000')
        .inputFluids('gtceu:cryotheum 20000')
        .circuit(3)
        .notConsumable('kubejs:strongly_interacting_neutron_refector')
        .addData("type", "proton")
        .addData("speed", 300)
        .EUt(1048576)
        .duration(400)
    ctnh.accelerator_upmode('kubejs:constrained_unstable_neutronium')
        .itemInputs('kubejs:constrained_proton_deficient_atom_neutronium')
        .itemInputs('kubejs:constrained_electron_deficient_atom_neutronium')
        .itemOutputs('kubejs:constrained_unstable_neutronium')
        .itemInputs('128x gtceu:neutronium_dust')
        .itemInputs('4x gtceu:gravi_star')
        .notConsumable('kubejs:adamantite_proton_source')
        .circuit(30)
        .notConsumable('kubejs:strongly_interacting_neutron_refector')
        .addData("type", "nu")
        .addData("speed", 45000)
        .EUt(1048576)
        .duration(450)
    ctnh.accelerator_upmode('anti_power')
        .itemInputs('20x gtceu:sodium22_dust')
        .notConsumable("kubejs:strongly_interacting_neutron_refector")
        .addData("type", "nu")
        .addData("speed", 20000)
        .addData('darkmatter', "electric")
        .itemOutputs('ctnhcore:radioactive_waste')
        .duration(200)
        .EUt(524288)
    ctnh.accelerator_upmode('anti_proton')
        .itemInputs('gtceu:dense_tungsten_steel_plate')
        .notConsumable('kubejs:adamantite_proton_source')
        .addData("type", "proton")
        .addData("speed", 20000)
        .addData('darkmatter', "proton")
        .itemOutputs('ctnhcore:radioactive_waste')
        .duration(200)
        .EUt(524288)
    ctnh.accelerator_upmode('waste')
        .itemInputs('gtceu:neutronium_plate')
        .notConsumable('kubejs:adamantite_proton_source')
        .addData("type", "element")
        .addData("speed", 19000)
        .itemOutputs('ctnhcore:radioactive_waste')
        .duration(80)
        .EUt(524288)
    // ctnh.assembly_line('ctnhcore:superconducting_penning_trap')
    //     .itemOutputs('ctnhcore:superconducting_penning_trap')
    //     .itemInputs('64x gtceu:superconducting_coil')
    //     .itemInputs('16x gtceu:superconducting_coil')
    //     .itemInputs('64x gtceu:zpm_fluid_regulator')
    //     .itemInputs('32x #gtceu:circuits/uhv')
    //     .itemInputs('48x #gtceu:circuits/uv')
    //     .itemInputs('64x gtceu:high_power_casing')
    //     .itemInputs('64x ctnhcore:naquadah_alloy_casing_block')
    //     .itemInputs('16x gtceu:neutronium_block')
    //     .itemInputs('64x #gtceu:circuits/zpm')
    //     .inputFluids('gtceu:molten_uranium_rhodium_dinaquadide 10000')
    //     .inputFluids('gtceu:adamantite_plasma 10000')
    //     .inputFluids('gtceu:bedrock_neutronium 10000')
    //     .inputFluids('gtceu:soldering_alloy 10000')
    //     .duration(2600)
    //     .EUt(524288)
    ctnh.accelerator_upmode('gtceu:adamantite_plasma')
        .inputFluids('gtceu:adamantite_plasma 10000')
        .notConsumable('kubejs:adamantite_proton_source')
        .addData("type", "proton")
        .addData("speed", 20000)
        .outputFluids('gtceu:compressed_adamantite_plasma 100')
        .duration(260)
        .EUt(524288)
    ctnh.accelerator_upmode("americium_and_naquadria_to_neutronium")
        .inputFluids('gtceu:naquadria 256')
        .inputFluids('gtceu:neutronium 256')
        .inputFluids("gtceu:tritanium 512")
        .notConsumable('kubejs:adamantite_proton_source')
        .addData("type", "proton")
        .addData("speed", 20000)
        .duration(200)
        .EUt(32678 * 4 * 4)
        .outputFluids('gtceu:neutronium 2048')
    ctnh.accelerator_upmode("ytoj")
        .itemInputs('10x gtceu:bedrock_dust_dust')
        .inputFluids("gtceu:aether 1024")
        .outputFluids("gtceu:adamantite_plasma 1024")
        .addData("type", "element")
        .addData("speed", 45000)
        .duration(200)
        .EUt(32678 * 4 * 4)


})