ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    ctnh.assembly_line('ctnhcore:advanced_bio_reactor_casing')
        .itemOutputs('7x ctnhcore:advanced_bio_reactor_casing')
        .itemInputs('7x gtnn:plate_radiation_protection')
        .itemInputs('56x gtceu:hastelloy_x_frame')
        .itemInputs('7x gtceu:dense_radiation_sight_alloy_x_plate')
        .itemInputs('2x #gtceu:circuits/uv')
        .itemInputs('7x ctnhcore:bio_reactor_casing')
        .itemInputs('7x gtceu:neutronium_plate')
        .inputFluids('gtceu:cerrobase_140 14370')
        .inputFluids('gtceu:naquadah_alloy 14370')
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:bio_reactor_casing'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(28))
        .duration(100)
        .EUt(32768)
    ctnh.assembly_line('ctnhcore:luv_neuro_compiler')
        .itemInputs('gtmthings:luv_huge_dual_hatch')
        .itemInputs('4x #gtceu:circuits/zpm')
        .itemInputs('7x gtceu:dense_naquadah_heat_resistant_ferrochrome_alloy_792_plate')
        .itemInputs('2x gtceu:luv_conveyor_module')
        .itemInputs('gtceu:luv_sensor')
        .itemInputs('7x gtceu:dense_radiation_sight_alloy_x_plate')
        .inputFluids('gtceu:naquadria 1000')
        .inputFluids('gtceu:kapton_k 1000')
        .itemOutputs('ctnhcore:luv_neuro_compiler')
        .duration(100)
        .EUt(32768)
    ctnh.assembly_line('ctnhcore:zpm_neuro_compiler')
        .itemInputs('gtmthings:zpm_huge_dual_hatch')
        .itemInputs('4x #gtceu:circuits/uv')
        .itemInputs('7x gtceu:dense_naquadah_heat_resistant_ferrochrome_alloy_792_plate')
        .itemInputs('2x gtceu:zpm_conveyor_module')
        .itemInputs('gtceu:zpm_sensor')
        .itemInputs('7x gtceu:dense_radiation_sight_alloy_x_plate')
        .inputFluids('gtceu:naquadria 1000')
        .inputFluids('gtceu:kapton_k 1000')
        .itemOutputs('ctnhcore:zpm_neuro_compiler')
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:luv_neuro_compiler'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(28))
        .duration(100)
        .duration(100)
        .EUt(32768 * 4)
    ctnh.assembly_line('ctnhcore:uv_neuro_compiler')
        .itemInputs('gtmthings:uv_huge_dual_hatch')
        .itemInputs('4x #gtceu:circuits/uhv')
        .itemInputs('7x gtceu:dense_naquadah_heat_resistant_ferrochrome_alloy_792_plate')
        .itemInputs('2x gtceu:uv_conveyor_module')
        .itemInputs('gtceu:uv_sensor')
        .itemInputs('7x gtceu:dense_radiation_sight_alloy_x_plate')
        .inputFluids('gtceu:naquadria 1000')
        .inputFluids('gtceu:kapton_k 1000')
        .itemOutputs('ctnhcore:uv_neuro_compiler')
        .duration(100)
        .EUt(32768 * 4 * 4)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:zpm_neuro_compiler'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(28))
    ctnh.assembly_line('ctnhcore:uhv_neuro_compiler')
        .itemInputs('gtmthings:uhv_huge_dual_hatch')
        .itemInputs('4x #gtceu:circuits/uev')
        .itemInputs('7x gtceu:dense_naquadah_heat_resistant_ferrochrome_alloy_792_plate')
        .itemInputs('2x gtceu:uhv_conveyor_module')
        .itemInputs('gtceu:uhv_sensor')
        .itemInputs('7x gtceu:dense_radiation_sight_alloy_inf_plate')
        .inputFluids('gtceu:naquadria 1000')
        .inputFluids('gtceu:kapton_k 1000')
        .itemOutputs('ctnhcore:uhv_neuro_compiler')
        .duration(100)
        .EUt(32768 * 4 * 4 * 4)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:uv_neuro_compiler'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UHV])
            .CWUt(56))
    ctnh.compiler_recipe("lm")
        .itemInputs('gtceu:soldering_alloy_dust')
        .itemInputs('ctnhcore:sculk_cell')
        .itemInputs('gtceu:long_radiation_sight_alloy_inf_rod')
        .itemInputs('extendedcrafting:crystaltine_ingot')
        .itemInputs('#gtceu:circuits/uev')
        .itemOutputs('ctnhcore:research_dataset_lm')
        .addData("1", 48)
        .addData("2", 15)
        .addData("3", 30)
        .addData("noisea", 20)
        .addData("noiseb", 2)
        .addData("range", 120)
        .duration(20 * 30)
        .EUt(1000000)
    ctnh.assembler("cold")
        .itemInputs('64x gtceu:fine_hssg_wire')
        .itemInputs('4x gtceu:iv_voltage_coil')
        .inputFluids('gtceu:cryotheum 10000')
        .itemOutputs('ctnhcore:supercooled_bloock')
        .EUt(8192)
        .duration(100)
})