ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    ctnh.assembly_line('ctnhcore:advanced_bio_reactor_casing')
        .itemOutputs('7x ctnhcore:advanced_bio_reactor_casing')
        .itemInputs('7x ctnhcore:plate_radiation_protection')
        .itemInputs('56x gtceu:hastelloy_x_frame')
        .itemInputs('7x gtceu:dense_radiation_sight_alloy_x_plate')
        .itemInputs('2x #gtceu:circuits/uv')
        .itemInputs('7x ctnhcore:bio_reactor_casing')
        .itemInputs('7x gtceu:neutronium_plate')
        .inputFluids('gtceu:cerrobase_140 14370')
        .inputFluids('gtceu:naquadah_alloy 14370')
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:bio_reactor_casing'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(28))
        .duration(100)
        .EUt(32768)
    ctnh.compiler_recipe("lm")
        .itemInputs('gtceu:soldering_alloy_dust')
        .itemInputs('ctnhcore:sculk_cell')
        .itemInputs('gtceu:long_radiation_sight_alloy_inf_rod')
        .itemInputs('avaritia:crystal_matrix_ingot')
        .itemInputs('#gtceu:circuits/uev')
        .itemOutputs('ctnhcore:research_dataset_lm')
        .addData("1", 48)
        .addData("2", 15)
        .addData("3", 30)
        .addData("noisea", 20)
        .addData("noiseb", 2)
        .addData("range", 120)
        .duration(20 * 30)
        .EUt(1000000)
    ctnh.assembler("cold")
        .itemInputs('64x gtceu:fine_hssg_wire')
        .itemInputs('4x gtceu:iv_voltage_coil')
        .inputFluids('gtceu:cryotheum 10000')
        .itemOutputs('ctnhcore:supercooled_bloock')
        .EUt(8192)
        .duration(100)
    ctnh.assembly_line('ctnhcore:bio_reactor')
        .itemInputs('64x ctnhcore:bio_reactor')
        .itemInputs('8x ctnhcore:advanced_bio_reactor_casing')
        .itemInputs('64x gtceu:ruthenium_trinium_americium_neutronate_plate')
        .itemInputs('7x gtceu:dense_radiation_sight_alloy_x_plate')
        .itemInputs('2x #gtceu:circuits/uhv')
        .itemInputs('2x #gtceu:circuits/uhv')
        .itemInputs('2x #gtceu:circuits/uhv')
        .itemInputs('2x #gtceu:circuits/uhv')
        .itemInputs('64x gtceu:zpm_electric_pump')
        .itemInputs('64x gtceu:zpm_electric_piston')
        .inputFluids('gtceu:cerrobase_140 10000')
        .inputFluids('gtceu:soldering_alloy 10000')
        .inputFluids('gtceu:naquadah_alloy 10000')
        .inputFluids('gtceu:bedrock_neutronium 10000')
        .itemOutputs('ctnhcore:neruo_martix_compiler')
        .EUt(81920)
        .duration(1000)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:bio_reactor'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(128))

})