ServerEvents.recipes(event => {
    Ingredient.of('#forge:foods').getItemTypes().forEach(food => {
            if (food.toString() != 'pumpkin_pie') {
                let nutrition = food.getFoodProperties().getNutrition()
                let saturation = food.getFoodProperties().getSaturationModifier()
                let rate = nutrition + saturation / 2
                event.recipes.gtceu.eternal_garden(food.toString() + '_gourmaryllis')
                    .EUt(512)
                    .itemInputs(food.asIngredient().getItemIds())
                    .notConsumable('botania:gourmaryllis')
                    .outputFluids(Fluid.of('gtceu:mana', 9 * Math.floor(Math.pow(rate, 3))))
                    .duration(30 * rate / 2)
                    .addData("type", "eat")
                    .addData("nutrition", nutrition + saturation * 0.5)
            }
        })
        //水绣球
    event.recipes.gtceu.eternal_garden('water1')
        .notConsumable('botania:hydroangeas')
        .inputFluids('minecraft:water 1000')
        .outputFluids(Fluid.of('gtceu:mana', 100))
        .duration(20)
        .EUt(256)
        .addData("type", "water")
    event.recipes.gtceu.eternal_garden('water2')
        .notConsumable('botania:hydroangeas')
        .inputFluids('gtceu:distilled_water 1000')
        .outputFluids(Fluid.of('gtceu:mana', 200))
        .duration(25)
        .EUt(512)
        .addData("type", "water")
        //炽玫瑰
    event.recipes.gtceu.eternal_garden('burn1')
        .notConsumable('botania:thermalily')
        .inputFluids('minecraft:lava 1000')
        .outputFluids(Fluid.of('gtceu:mana', 500))
        .duration(20)
        .EUt(2048)
        .addData("type", "blame")
    event.recipes.gtceu.eternal_garden('burn2')
        .notConsumable('botania:thermalily')
        .inputFluids('gtceu:blaze 1000')
        .outputFluids(Fluid.of('gtceu:mana', 500))
        .duration(25)
        .EUt(2048)
        .addData("type", "blame")
    event.recipes.gtceu.eternal_garden('burn3')
        .notConsumable('botania:thermalily')
        .inputFluids('gtceu:pyrotheum 1000')
        .outputFluids(Fluid.of('gtceu:mana', 2000))
        .duration(25)
        .EUt(2048)
        .addData("type", "blame")
        //火红莲
    event.recipes.gtceu.eternal_garden("fire1")
        .notConsumable('botania:endoflame')
        .itemInputs('minecraft:coal_block')
        .outputFluids(Fluid.of('gtceu:mana', 450))
        .duration(210)
        .EUt(512)
        .addData("type", "fire")
        .addData("temp", 900)
    event.recipes.gtceu.eternal_garden("fire2")
        .notConsumable('botania:endoflame')
        .itemInputs('minecraft:coal')
        .outputFluids(Fluid.of('gtceu:mana', 50))
        .duration(30)
        .EUt(512)
        .addData("type", "fire")
        .addData("temp", 100)
    event.recipes.gtceu.eternal_garden("fire3")
        .notConsumable('botania:endoflame')
        .itemInputs('gtceu:coal_dust')
        .outputFluids(Fluid.of('gtceu:mana', 25))
        .duration(30)
        .EUt(512)
        .addData("type", "fire")
        .addData("temp", 50)
    event.recipes.gtceu.eternal_garden("fire4")
        .notConsumable('botania:endoflame')
        .itemInputs('minecraft:charcoal')
        .outputFluids(Fluid.of('gtceu:mana', 24))
        .duration(30)
        .EUt(512)
        .addData("type", "fire")
        .addData("temp", 50)
    event.recipes.gtceu.eternal_garden("fire5")
        .notConsumable('botania:endoflame')
        .itemInputs('gtceu:charcoal_block')
        .outputFluids(Fluid.of('gtceu:mana', 192))
        .duration(180)
        .EUt(512)
        .addData("type", "fire")
        .addData("temp", 450)
    event.recipes.gtceu.eternal_garden("fire6")
        .notConsumable('botania:endoflame')
        .itemInputs('gtceu:charcoal_dust')
        .outputFluids(Fluid.of('gtceu:mana', 12))
        .duration(30)
        .EUt(512)
        .addData("type", "fire")
        .addData("temp", 25)
    event.recipes.gtceu.eternal_garden("fire7")
        .notConsumable('botania:endoflame')
        .itemInputs('gtceu:coke_gem')
        .outputFluids(Fluid.of('gtceu:mana', 100))
        .duration(35)
        .EUt(2048)
        .addData("type", "fire")
        .addData("temp", 200)
    event.recipes.gtceu.eternal_garden("fire8")
        .notConsumable('botania:endoflame')
        .itemInputs('gtceu:coke_dust')
        .outputFluids(Fluid.of('gtceu:mana', 50))
        .duration(35)
        .EUt(2048)
        .addData("type", "fire")
        .addData("temp", 75)
    event.recipes.gtceu.eternal_garden("fire9")
        .notConsumable('botania:endoflame')
        .itemInputs('gtceu:coke_block')
        .outputFluids(Fluid.of('gtceu:mana', 900))
        .duration(245)
        .EUt(2048)
        .addData("type", "fire")
        .addData("temp", 1800)
    event.recipes.gtceu.eternal_garden("fire10")
        .notConsumable('botania:endoflame')
        .itemInputs('18x gtceu:pyrotheum_dust')
        .outputFluids(Fluid.of('gtceu:mana', 1000))
        .duration(100)
        .EUt(8192)
        .addData("type", "fire")
        .addData("temp", 2000)
    event.recipes.gtceu.eternal_garden("fire_down")
        .addData("type", "fire")
        .notConsumable('botania:endoflame')
        .circuit(24)
        .duration(40)
        //热爆花
    event.recipes.gtceu.eternal_garden('entropinnyum1')
        .notConsumable('botania:entropinnyum')
        .itemInputs('minecraft:tnt')
        .outputFluids(Fluid.of('gtceu:mana', 240))
        .duration(5)
        .addData("type", "boom")
        .EUt(32678)
    event.recipes.gtceu.eternal_garden('entropinnyum2')
        .notConsumable('botania:entropinnyum')
        .itemInputs('gtceu:industrial_tnt')
        .outputFluids(Fluid.of('gtceu:mana', 700))
        .duration(5)
        .addData("type", "boom")
        .EUt(32678)
    event.recipes.gtceu.eternal_garden('entropinnyum3')
        .notConsumable('botania:entropinnyum')
        .itemInputs('gtceu:dynamite')
        .outputFluids(Fluid.of('gtceu:mana', 550))
        .duration(5)
        .addData("type", "boom")
        .EUt(32678)
    event.recipes.gtceu.eternal_garden('entropinnyum4')
        .notConsumable('botania:entropinnyum')
        .itemInputs('gtceu:powderbarrel')
        .outputFluids(Fluid.of('gtceu:mana', 150))
        .duration(5)
        .addData("type", "boom")
        .EUt(32678)
        //凋灵菟葵
    event.recipes.gtceu.eternal_garden('wither1')
        .notConsumable('mythicbotany:wither_aconite')
        .itemInputs('minecraft:nether_star')
        .outputFluids(Fluid.of('gtceu:mana', 150000))
        .duration(2000)
        .addData("type", "wither")
        .EUt(8192)
    event.recipes.gtceu.eternal_garden('wither2')
        .notConsumable('mythicbotany:wither_aconite')
        .itemInputs('gtceu:quantum_star')
        .outputFluids(Fluid.of('gtceu:mana', 500000))
        .duration(2500)
        .addData("type", "wither")
        .EUt(8192 * 4)
        //物落草
    event.recipes.gtceu.eternal_garden('botania:shulk_me_not')
        .notConsumable('botania:shulk_me_not')
        .circuit(1)
        .outputFluids(Fluid.of('gtceu:mana', 4))
        .duration(1)
        .addData("type", "fly")
        .EUt(4096)
    event.recipes.gtceu.mana_reactor('ctnhcore:eternal_garden')
        .itemOutputs('ctnhcore:eternal_garden')
        .itemInputs('botania:rune_spring')
        .itemInputs('botania:rune_summer')
        .itemInputs('botania:rune_autumn')
        .itemInputs('botania:rune_winter')
        .itemInputs('64x #botania:mystical_flowers')
        .itemInputs('kubejs:heart_of_flower')
        .inputFluids('gtceu:mana 10000')
        .EUt(512)
        .duration(8000)
    event.recipes.gtceu.mana_reactor('kubejs:heart_of_flower')
        .itemOutputs('kubejs:heart_of_flower')
        .itemInputs('32x ctnhcore:starlight_rune')
        .itemInputs('32x ctnhcore:twist_rune')
        .itemInputs('32x ctnhcore:horizen_rune')
        .itemInputs('64x ctnhcore:proliferation_rune')
        .itemInputs('128x gtceu:stem_cells')
        .itemInputs('64x gtceu:tiny_ultra_mana_dust')
        .inputFluids('gtceu:zenith_essence 10000')
        .EUt(32678 * 16)
        .duration(800)

})