ServerEvents.recipes(event => {
    event.remove({ id: 'create:pressing/iron_ingot' })
    //event.remove({output:'create:iron_sheet'})
    event.remove({type:'twilightforest:uncrafting_table'})
    event.remove({id:'create:crafting/materials/andesite_alloy_from_zinc'})
    event.remove({id:'create:crafting/materials/andesite_alloy'})
    event.remove({type:'create:mixing',output:'create:andesite_alloy'})
    event.remove({output:'create:shaft'})
    event.remove({output:'create:encased_fan'})
    event.remove({output:'#forge:plates', type:'minecraft:crafting_shaped'})
    event.remove({output:'create:windmill_bearing'})
    event.remove({output:'create:depot'})
    event.remove({output:'create:mechanical_press'})
    event.remove({id:'farmersdelight:paper_from_tree_bark'})
    event.remove({id:'create:pressing/sugar_cane'})
    event.remove({id:'create:crafting/kinetics/water_wheel'})
    event.remove({output:'create:large_cogwheel'})
    event.remove({id:'create:crafting/kinetics/large_water_wheel'})
    event.remove({id:'create:crafting/kinetics/mechanical_drill'})
    event.remove({id:'gtceu:shapeless/dust_brass'})
    event.remove({id:'gtceu:shapeless/dust_bronze'})
    event.remove({id:'gtceu:shapeless/potin_dust'})
    event.remove({id:'create:crafting/kinetics/mechanical_mixer'})
    event.remove({id:'create:crafting/materials/rose_quartz'})
    event.remove({id:'create:crafting/materials/electron_tube'})
    event.remove({id:'create:crafting/kinetics/deployer'})
    event.remove({id:'create:crafting/kinetics/contraption_controls'})
    event.remove({id:'create:mechanical_crafting/crushing_wheel'})
    event.remove({id:'create_new_age:shaped/redstone_magnet'})
    event.remove({output:'create_new_age:carbon_brushes'})
    event.remove({output:'create_new_age:generator_coil'})
    event.remove({id:'create_new_age:shapeless/energiser_t1'})
    event.remove({id:'minecraft:lightning_rod'})
    event.remove({id:'create_new_age:pressing/overcharged_gold'})
    event.remove({id:'create_new_age:pressing/overcharged_iron'})
    event.remove({id:'enderio:void_chassis'})
    event.remove({id:'gtceu:shaped/vacuum_tube'})
    event.remove({output:'tfmg:screw'})
    event.remove({id:'gtceu:shaped/steam_turbine_lv'})
    event.remove({output:'create:spout'})
    event.remove({id:'tfmg:sequenced_assembly/steel_mechanism'})
    event.remove({output:'tfmg:turbine_blade'})
    event.remove({id:'tfmg:sequenced_assembly/turbine_engine'})
    event.remove({id:'tfmg:distillation/heavy_oil'})
    event.remove({id:'create:milling/charcoal'})
    event.remove({id:/thermal:parts(.*)_gear/})
    event.remove({output:'thermal:constantan_ingot'})
    event.remove({input:'thermal:constantan_ingot'})
    event.remove({id:'botania:mana_fluxfield'})
    event.remove({output:/botania:apothecary_(.*)/})
    event.remove({id:'gtceu:shapeless/iron_magnetic_stick'})
    event.remove({id:'alexscaves:azure_neodymium_ingot'})
    event.remove({id:'alexscaves:scarlet_neodymium_ingot'})
    event.remove({output:'create:cogwheel'})
    event.remove({id:'create:crafting/kinetics/mechanical_bearing'})
    event.remove({output:'create:millstone'})
    event.remove({id:'aether:skyroot_piston'})
    event.remove({id:'sophisticatedbackpacks:netherite_backpack'})
    event.remove({id:'expandedstorage:obsidian_to_netherite_conversion_kit'})
    event.remove({id:'bclib:tag_piston'})
    event.remove({output:'enderio:soularium_ingot'})
    event.remove({output:'enderio:energetic_alloy_ingot'})
    event.remove({id:'enderio:alloy_smelting/pulsating_alloy_ingot'})
    event.remove({id:'enderio:alloy_smelting/vibrant_alloy_ingot'})
    event.remove({id:'enderio:alloy_smelting/copper_alloy_ingot'})
    event.remove({id:'enderio:alloy_smelting/redstone_alloy_ingot'})
    event.remove({id:'enderio:alloy_smelting/end_steel_ingot'})
    event.remove({id:'enderio:alloy_smelting/dark_steel_ingot'})
    event.remove({id:'enderio:alloy_smelting/conductive_alloy_ingot'})
    event.remove({id:'tetranichematerials:red_gold_powder'})
    event.remove({id:'gtceu:shaped/steam_turbine_mv'})
    event.remove({id:'gtceu:shaped/steam_turbine_hv'})
    event.remove({id:'enderio:copper_ingot_from_smelting'})
    event.remove({id:'tetranichematerials:copper_ingot_from_powder_smelting'})
    event.remove({id:'bloodmagic:smelting/ingot_copper'})
    event.remove({id:'tetranichematerials:copper_ingot_from_powder_blasting'})
    event.remove({id:'bloodmagic:smelting/blasting_ingot_copper'})
    event.remove({id:'enderio:iron_ingot_from_blasting'})
    event.remove({id:'tetranichematerials:iron_ingot_from_powder_blasting'})
    event.remove({id:'bloodmagic:smelting/ingot_iron'})
    event.remove({id:'enderio:iron_ingot_from_smelting'})
    event.remove({id:'tetranichematerials:iron_ingot_from_powder_smelting'})
    event.remove({id:'enderio:gold_ingot_from_smelting'})
    event.remove({id:'tetranichematerials:gold_ingot_from_powder_smelting'})
    event.remove({id:'bloodmagic:smelting/ingot_gold'})
    event.remove({id:'bloodmagic:smelting/blasting_ingot_gold'})
    event.remove({id:'tetranichematerials:gold_ingot_from_powder_blasting'})
    event.remove({id:'tetranichematerials:steel_ingot_from_powder_blasting'})
    event.remove({id:'tetranichematerials:steel_powder'})
    event.remove({id:'bclib:tag_bucket'})
    event.remove({id:'extendedcrafting:handheld_table'})
    event.remove({id:'create_new_age:shaped/layered_magnet'})
    event.remove({id:'enderio:stick'})
    event.remove({id:'enderio:wood_gear'})
    event.remove({id:'enderio:wood_gear_corner'})

    event.remove({ output: '#forge:chipped_gems', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: '#forge:flawed_gems', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: /gtceu:(.*)_gem/, type: 'minecraft:crafting_shapeless', input: /gtceu:flawless_(.*)_gem/ })
    event.remove({ output: '#forge:flawless_gems', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: '#forge:exquisite_gems', type: 'minecraft:crafting_shapeless' })

    let removeoutput = ['create:cart_assembler', 'create:portable_storage_interface', 'create:rotation_speed_controller', 'create:belt_connector', 'angelblockrenewed:angel_block', 'create:goggles', 'tetranichematerials:lockwood_ingot']
    for (let i of removeoutput) {
        event.remove({ output: `${i}` })
    }
})

