ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    ctnh.autoclave("sun1")
        .itemInputs('16x minecraft:glow_berries')
        .inputFluids('gtceu:uu_matter 16')
        .itemOutputs('16x gtceu:sunnarium_dust')
        .EUt(480)
        .duration(5 * 20 * 16)
    ctnh.autoclave("sun2")
        .itemInputs('64x minecraft:glow_ink_sac')
        .inputFluids('gtceu:uu_matter 16')
        .itemOutputs('16x gtceu:sunnarium_dust')
        .EUt(480)
        .duration(5 * 25 * 16)
    ctnh.autoclave("sun3")
        .itemInputs('16x alexscaves:bioluminesscence')
        .inputFluids('gtceu:uu_matter 16')
        .itemOutputs('16x gtceu:sunnarium_dust')
        .EUt(480)
        .duration(5 * 10 * 16)
    ctnh.autoclave("sun4")
        .inputFluids('gtceu:sunnarium_extract 576')
        .itemInputs('minecraft:glowstone_dust')
        .itemOutputs('gtceu:sunnarium_dust')
        .EUt(480)
        .duration(10 * 20)
    ctnh.mixer("sun1")
        .itemInputs('4x gtceu:thorium_dust')
        .itemInputs('4x botania:light_relay')
        .itemInputs('4x minecraft:glowstone_dust')
        .itemInputs('create:chromatic_compound')
        .itemOutputs('16x gtceu:sunnarium_dust')
        .EUt(480 * 4)
        .duration(120)
    ctnh.mixer("soda_glass")
        .itemInputs('2x gtceu:soda_ash_dust')
        .itemInputs('6x gtceu:silicon_dioxide_dust')
        .itemInputs('gtceu:calcite_dust')
        .itemOutputs('9x gtceu:soda_dust_dust')
        .EUt(120)
        .duration(200)
    ctnh.pvb_recipe('clgs')
        .itemInputs('3x gtceu:selenium_dust')
        .itemInputs('gtceu:copper_dust')
        .itemInputs('gtceu:gallium_dust')
        .itemInputs('gtceu:indium_dust')
        .itemInputs('gtceu:cryolite_dust')
        .outputFluids('gtceu:sodium_hexafluoroaluminate 144')
        .itemOutputs('gtceu:clgs_buffer_dust')
        .EUt(1280)
        .duration(200)
    ctnh.chemical_vapor_deposition('cds')
        .itemInputs('gtceu:cadmium_sulfide_dust')
        .itemInputs('gtceu:clgs_buffer_plate')
        .itemOutputs('gtceu:cds_buffer_plate')
        .EUt(8192)
        .duration(200)
    ctnh.pvb_recipe('zzz')
        .itemInputs('gtceu:molybdenum_disilicide_dust')
        .itemInputs('gtceu:double_soda_dust_plate')
        .itemInputs('5x gtceu:nickel_dust')
        .itemInputs('5x gtceu:aluminium_dust')
        .itemInputs('32x gtceu:sunnarium_foil')
        .itemInputs('32x gtceu:sunnarium_foil')
        .inputFluids('gtceu:polybenzimidazole 500')
        .itemOutputs('kubejs:clgs_electrode')
        .EUt(8192 * 4)
        .duration(400)
    ctnh.pvb_recipe('gtceu:magnetron_sputtering_target_material_plate')
        .itemOutputs('gtceu:magnetron_sputtering_target_material_plate')
        .itemInputs('11x gtceu:zinc_dust')
        .itemInputs('11x gtceu:aluminium_dust')
        .itemInputs('11x gtceu:sunnarium_dust')
        .EUt(8192 * 4)
        .duration(400)
    ctnh.assembler('sunny')
        .itemInputs('kubejs:clgs_electrode')
        .itemInputs('gtceu:cds_buffer_plate')
        .itemInputs('gtceu:magnetron_sputtering_target_material_plate')
        .itemInputs('4x gtceu:indium_tin_barium_titanium_cuprate_double_wire')
        .itemInputs('16x gtceu:blue_steel_plate')
        .inputFluids('gtceu:sunnarium 720')
        .itemOutputs('kubejs:clgs')
        .EUt(8192 * 4)
        .duration(800)
    ctnh.extractor("sun1")
        .itemInputs('minecraft:glow_berries')
        .chancedOutput('gtceu:sunnarium_extract_dust', 7000, 1000)
        .EUt(480)
        .duration(150)
    ctnh.extractor("sun2")
        .itemInputs('4x minecraft:glow_ink_sac')
        .chancedOutput('gtceu:sunnarium_extract_dust', 6000, 1000)
        .EUt(480)
        .duration(200)
    ctnh.extractor("sun3")
        .itemInputs('alexscaves:bioluminesscence')
        .chancedOutput('gtceu:sunnarium_extract_dust', 8000, 1000)
        .EUt(480)
        .duration(100)
    ctnh.fusion_reactor('sun')
        .inputFluids('gtceu:glowstone 1440')
        .inputFluids('gtceu:sunnarium_extract 144')
        .outputFluids('gtceu:sunnarium 1440')
        .fusionStartEU(150000000)
        .duration(100)
        .EUt(32678)
    ctnh.fusion_reactor('gtceu:sunnarium_plasma')
        .outputFluids('gtceu:sunnarium_plasma 1000')
        .inputFluids('gtceu:oxygen_plasma 1000')
        .inputFluids('gtceu:sunnarium 1000')
        .fusionStartEU(300000000)
        .duration(100)
        .EUt(32678 * 4)
    ctnh.assembler('gtceu:dense_calorite_plate')
        .itemInputs('gtceu:dense_optical_heat_resistant_ferrochrome_alloy_080_plate')
        .itemInputs('4x gtceu:incoloy_ma_956_plate')
        .itemInputs('gtceu:dense_calorite_plate')
        .itemInputs('4x gtceu:sunnarium_extract_dust')
        .itemInputs('gtceu:dense_naquadah_heat_resistant_ferrochrome_alloy_792_plate')
        .itemOutputs('kubejs:thermotolerant_dish')
        .duration(100)
        .EUt(32678 * 16)
    ctnh.cultivation_room('gtceu:radiation_sunnarium_extract_plasma')
        .outputFluids('gtceu:radiation_sunnarium_extract_plasma 1000')
        .inputFluids('enderio:liquid_sunshine 100')
        .inputFluids('gtceu:sterilebiologicalculturemediumstocksolution 200')
        .inputFluids('gtceu:sunnarium_extract 1000')
        .circuit(1)
        .duration(200)
        .EUt(32678 * 14)
        .chancedInput('kubejs:thermotolerant_dish', 2000, -1)
    ctnh.cultivation_room('gtceu:radiation_sunnarium_extract_plasma2')
        .outputFluids('gtceu:radiation_sunnarium_extract_plasma 6000')
        .inputFluids('enderio:liquid_sunshine 600')
        .inputFluids('gtceu:sterilebiologicalculturemediumstocksolution 1200')
        .inputFluids('gtceu:sunnarium_extract 6000')
        .itemInputs('kubejs:thermotolerant_dish')
        .circuit(2)
        .duration(1200)
        .EUt(32678 * 14)
    ctnh.plasma_condenser('gtceu:helium_plasma')
        .outputFluids('gtceu:helium_plasma 4000')
        .inputFluids('gtceu:liquid_helium 4000')
        .inputFluids('gtceu:radiation_sunnarium_extract_plasma 1000')
        .outputFluids('gtceu:radiation_sunnarium_extract 1000')
        .EUt(23678 * 4)
        .duration(100)
    ctnh.fusion_reactor("light")
        .inputFluids('gtceu:sunnarium_plasma 144')
        .inputFluids('gtceu:radiation_sunnarium_extract 144')
        .outputFluids('gtceu:hikarium_plasma 288')
        .fusionStartEU(600000000)
        .duration(100)
        .EUt(32678 * 4)
    ctnh.plasma_condenser('gtceu:hikarium_plasma')
        .notConsumable('minecraft:glowstone_dust')
        .outputFluids('gtceu:helium_plasma 4000')
        .inputFluids('gtceu:liquid_helium 4000')
        .inputFluids('gtceu:hikarium_plasma 1000')
        .outputFluids('gtceu:hikarium 1000')
        .EUt(23678 * 20)
        .duration(100)
    ctnh.assembler('ctnhcore:photon_press_cond_block')
        .itemOutputs('ctnhcore:photon_press_cond_block')
        .itemInputs('gtceu:neutron_reflector')
        .itemInputs('ctnhcore:plate_radiation_protection')
        .itemInputs('gtceu:dense_cadmium_sulfide_plate')
        .itemInputs('kubejs:measurement_pv_cell')
        .inputFluids('gtceu:sunnarium 576')
        .itemInputs('ctnhcore:reflect_light_casing')
        .EUt(32678)
        .duration(200)
    ctnh.assembly_line('ctnhcore:combined_vapor_deposition_facility')
        .itemInputs('ctnhcore:chemical_vapor_deposition_machine')
        .itemInputs('gtceu:high_power_casing')
        .itemInputs('gtceu:superconducting_coil')
        .itemInputs('6x gtceu:luv_conveyor_module')
        .itemInputs('6x gtceu:luv_electric_motor')
        .itemInputs('6x gtceu:luv_robot_arm')
        .itemInputs('64x gtceu:cadmium_sulfide_screw')
        .itemInputs('8x gtceu:indium_tin_barium_titanium_cuprate_quadruple_wire')
        .itemInputs('16x gtceu:ev_field_generator')
        .inputFluids('gtceu:pcb_coolant 1000')
        .inputFluids('gtceu:soldering_alloy 16000')
        .itemOutputs('ctnhcore:combined_vapor_deposition_facility')
        .EUt(32678)
        .duration(2000)
    ctnh.assembly_line('ctnhcore:lasersorder')
        .itemOutputs('ctnhcore:lasersorder')
        .itemInputs('gtceu:large_engraving_laser')
        .itemInputs('gtceu:diamond_lens')
        .itemInputs('gtceu:emerald_lens')
        .itemInputs('gtceu:ruby_lens')
        .itemInputs('gtceu:sapphire_lens')
        .itemInputs('gtceu:nether_star_lens')
        .itemInputs('gtceu:luv_emitter')
        .itemInputs('16x gtceu:optical_heat_resistant_ferrochrome_alloy_080_rod')
        .itemInputs('16x gtceu:optical_heat_resistant_ferrochrome_alloy_080_gear')
        .itemInputs('64x gtceu:long_heat_resistant_ferrochrome_alloy_ds_rod')
        .inputFluids('gtceu:cerrobase_140 1600')
        .inputFluids('gtceu:heat_resistant_ferrochrome_alloy_020 1600')
        .EUt(32678)
        .duration(800)
    ctnh.laser_sorter_recipe('kubejs:clgs2')
        .itemOutputs('kubejs:measurement_pv_cell')
        .itemInputs('2x kubejs:clgs')
        .notConsumable('gtceu:ruby_lens')
        .EUt(128)
        .addData("cwut", 16)

    .duration(60000)
    ctnh.pvb_recipe('clgs_quick')
        .itemInputs('3x gtceu:selenium_dust')
        .itemInputs('gtceu:copper_dust')
        .itemInputs('gtceu:gallium_dust')
        .itemInputs('gtceu:indium_dust')
        .inputFluids('gtceu:sodium_hexafluoroaluminate 144')
        .itemInputs('gtceu:cadmium_sulfide_dust')
        .outputFluids('gtceu:sodium_hexafluoroaluminate 144')
        .itemOutputs('gtceu:cds_buffer_plate')
        .EUt(32678 * 4)
        .duration(20)
    ctnh.assembler('ctnhcore:pv_coil')
        .itemOutputs('ctnhcore:pv_coil')
        .itemInputs('48x gtceu:sunnarium_foil')
        .itemInputs('64x gtceu:fine_electrum_wire')
        .itemInputs('6x gtceu:optical_heat_resistant_ferrochrome_alloy_080_frame')
        .itemInputs('kubejs:general_circuit_iv')
        .itemInputs('6x gtceu:ev_voltage_coil')
        .inputFluids('gtceu:vanadium_gallium 576')
        .EUt(32678)
        .duration(144)
    ctnh.photovoltaic_assember('ctnhcore:pv_coil')
        .itemOutputs('ctnhcore:pv_coil')
        .itemInputs('32x gtceu:sunnarium_foil')
        .itemInputs('32x gtceu:fine_electrum_wire')
        .itemInputs('4x gtceu:optical_heat_resistant_ferrochrome_alloy_080_frame')
        .itemInputs('1x gtceu:iv_voltage_coil')
        .inputFluids('gtceu:vanadium_gallium 576')
        .addData("input", 32678 * 4)
        .duration(20)
    ctnh.assembly_line('ctnhcore:stellar_radiation_router_casing')
        .itemOutputs('4x ctnhcore:stellar_radiation_router_casing')
        .inputFluids('gtceu:pcb_coolant 4000')
        .inputFluids('gtceu:cryotheum 4000')
        .inputFluids('gtceu:liquid_helium 4000')
        .itemInputs('4x gtceu:heat_vent')
        .itemInputs('32x gtceu:niobium_titanium_small_fluid_pipe')
        .itemInputs('gtceu:dense_heat_resistant_ferrochrome_alloy_ds_plate')
        .itemInputs('gtceu:dense_heat_resistant_ferrochrome_alloy_020_plate')
        .itemInputs('gtceu:dense_optical_heat_resistant_ferrochrome_alloy_080_plate')
        .itemInputs('4x gtceu:naquadah_heat_resistant_ferrochrome_alloy_792_frame')
        .EUt(32678)
        .duration(100)
    ctnh.assembler('ctnhcore:photovoltaic_drone_prototype')
        .itemOutputs('ctnhcore:photovoltaic_drone_prototype')
        .itemInputs('64x gtceu:sunnarium_frame')
        .itemInputs('64x gtceu:sunnarium_screw')
        .itemInputs('2x kubejs:clgs')
        .itemInputs('7x gtceu:dense_optical_heat_resistant_ferrochrome_alloy_080_plate')
        .itemInputs('2x kubejs:general_circuit_iv')
        .itemInputs('3x kubejs:general_circuit_luv')
        .itemInputs('4x kubejs:general_circuit_zpm')
        .EUt(32678)
        .duration(600)
    ctnh.laser_sorter_recipe('research_pvdrone')
        .itemInputs('8x ctnhcore:photovoltaic_drone_prototype')
        .itemInputs('64x kubejs:clgs')
        .itemInputs('64x #gtceu:circuits/luv')
        .itemOutputs('kubejs:pv_drone_research_1')
        .EUt(128)
        .addData("cwut", 8)
        .duration(100000 * 20)
    ctnh.laser_sorter_recipe('research_pvdone_2')
        .itemInputs('16x gtceu:energy_module')
        .itemInputs('64x kubejs:measurement_pv_cell')
        .itemInputs('32x ctnhcore:photovoltaic_drone_tier1')
        .itemInputs('32x #gtceu:circuits/uv')
        .inputFluids('gtceu:sunnarium_plasma 32000')
        .itemInputs('16x gtceu:exquisite_magneto_resonatic_gem')
        .itemInputs('16x ctnhcore:pv_coil')
        .itemOutputs('kubejs:pv_drone_research_2')
        .EUt(128)
        .addData("cwut", 8)
        .duration(1000000 * 20)
    ctnh.laser_sorter_recipe('research_pvdone_3')
        .itemInputs('64x gtceu:highly_advanced_soc_wafer')
        .itemInputs('64x kubejs:imprinted_resonatic_circuit_board')
        .itemInputs('32x ctnhcore:photovoltaic_drone_tier2')
        .itemInputs('32x #gtceu:circuits/uhv')
        .inputFluids('gtceu:sunnarium_plasma 32000')
        .itemInputs('32x gtceu:small_hikarium_gear')
        .itemOutputs('kubejs:pv_drone_research_3')
        .EUt(128)
        .addData("cwut", 12)
        .duration(100000000 * 20)
    ctnh.assembly_line('ctnhcore:photovoltaic_drone_tier1')
        .itemOutputs('ctnhcore:photovoltaic_drone_tier1')
        .itemInputs('2x kubejs:measurement_pv_cell')
        .itemInputs('2x gtceu:optical_heat_resistant_ferrochrome_alloy_080_gear')
        .itemInputs('2x gtceu:naquadah_heat_resistant_ferrochrome_alloy_792_gear')
        .itemInputs('2x #gtceu:circuits/luv')
        .itemInputs('2x #gtceu:circuits/zpm')
        .itemInputs('32x gtceu:sunnarium_screw')
        .itemInputs('4x gtceu:sunnarium_frame')
        .inputFluids('gtceu:pcb_coolant 2000')
        .inputFluids('gtceu:cryotheum 2000')
        .inputFluids('gtceu:liquid_helium 2000')
        .EUt(32678 * 4)
        .duration(400)
        .stationResearch(b => b.researchStack(Item.of('kubejs:pv_drone_research_1'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(36))
    ctnh.assembly_line('ctnhcore:photovoltaic_drone_tier2')
        .itemOutputs('ctnhcore:photovoltaic_drone_tier2')
        .itemInputs('gtceu:energy_module')
        .itemInputs('kubejs:measurement_pv_cell')
        .itemInputs('2x gtceu:exquisite_magneto_resonatic_gem')
        .itemInputs('2x #gtceu:circuits/uv')
        .itemInputs('gtceu:dense_calorite_plate')
        .itemInputs('gtceu:dense_optical_heat_resistant_ferrochrome_alloy_080_plate')
        .itemInputs('64x gtceu:sunnarium_frame')
        .itemInputs('64x gtceu:sunnarium_frame')
        .itemInputs('64x gtceu:sunnarium_frame')
        .inputFluids('gtceu:sunnarium_plasma 16000')
        .inputFluids('gtceu:cryotheum 2000')
        .inputFluids('gtceu:liquid_helium 2000')
        .EUt(32678 * 4 * 4)
        .duration(400)
        .stationResearch(b => b.researchStack(Item.of('kubejs:pv_drone_research_2'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(48))
    ctnh.photovoltaic_assember("pv_drone_tier1")
        .notConsumable('kubejs:pv_drone_research_2')
        .itemInputs('2x kubejs:measurement_pv_cell')
        .itemInputs('gtceu:dense_optical_heat_resistant_ferrochrome_alloy_080_plate')
        .itemInputs('32x gtceu:sunnarium_screw')
        .itemInputs('8x gtceu:crystal_soc')
        .inputFluids('gtceu:cryotheum 8000')
        .itemOutputs('ctnhcore:photovoltaic_drone_tier1')
        .duration(400)
        .addData("input", 32678 * 8)
    ctnh.photovoltaic_assember("pv_drone_tier2")
        .notConsumable('kubejs:pv_drone_research_3')
        .itemInputs('14x kubejs:measurement_pv_cell')
        .itemInputs('7x gtceu:dense_optical_heat_resistant_ferrochrome_alloy_080_plate')
        .itemInputs('112x gtceu:small_hikarium_gear')
        .itemInputs('14x gtceu:highly_advanced_soc_wafer')
        .itemInputs('14x gtceu:exquisite_magneto_resonatic_gem')
        .inputFluids('gtceu:cryotheum 28000')
        .itemOutputs('7x ctnhcore:photovoltaic_drone_tier2')
        .EUt(-1)
        .duration(400)
        .addData("input", 32678 * 8 * 8)
    ctnh.photovoltaic_assember("enderio:liquid_sunshine")
        .itemInputs('64x minecraft:glowstone_dust')
        .outputFluids('enderio:liquid_sunshine 10000')
        .duration(1000)
        .addData("input", 500000)
    ctnh.photovoltaic_assember('ctnhcore:pv_terminal')
        .itemOutputs('ctnhcore:pv_terminal')
        .itemInputs('gtceu:terminal')
        .itemInputs('gtceu:sunnarium_dust')
        .duration(1)
        .addData("input", 10)
    ctnh.assembly_line('ctnhcore:space_photovoltai_cbase_station')
        .itemOutputs('ctnhcore:space_photovoltai_cbase_station')
        .itemInputs('64x ctnhcore:photovoltaic_power_station_energetic')
        .itemInputs('64x ctnhcore:photovoltaic_power_station_pulsating')
        .itemInputs('64x ctnhcore:photovoltaic_power_station_vibrant')
        .itemInputs('64x kubejs:measurement_pv_cell')
        .itemInputs('64x ctnhcore:pv_coil')
        .itemInputs('32x #gtceu:circuits/uv')
        .itemInputs('32x ctnhcore:nq_excite_carbon_carbon_nanofiber_structural_block')
        .inputFluids('gtceu:cerrobase_140 16000')
        .inputFluids('gtceu:soldering_alloy 16000')
        .inputFluids('gtceu:cryotheum 16000')
        .EUt(32678 * 4)
        .duration(1000)
    ctnh.assembly_line('pvdrone')
        .itemInputs('ctnhcore:photovoltaic_drone_prototype')
        .itemInputs('7x gtceu:dense_heat_resistant_ferrochrome_alloy_ds_plate')
        .itemInputs('7x gtceu:dense_heat_resistant_ferrochrome_alloy_020_plate')
        .itemInputs('7x gtceu:dense_optical_heat_resistant_ferrochrome_alloy_080_plate')
        .itemInputs('7x gtceu:dense_naquadah_heat_resistant_ferrochrome_alloy_792_plate')
        .itemInputs('7x gtceu:dense_naquadah_alloy_plate')
        .itemInputs('9x minecraft:beacon')
        .itemInputs('64x ctnhcore:pv_coil')
        .itemInputs('32x #gtceu:circuits/uv')
        .inputFluids('gtceu:cerrobase_140 16000')
        .inputFluids('gtceu:soldering_alloy 16000')
        .inputFluids('gtceu:cryotheum 16000')
        .itemOutputs('ctnhcore:photovoltaic_drone_station')
        .EUt(32678 * 4)
        .duration(1000)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:drone_holder'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(48))
    ctnh.chemical_vapor_deposition("nano_c")
        .itemInputs('64x gtceu:activated_carbon_dust')
        .itemInputs('64x gtceu:carbon_fibers')
        .inputFluids('gtceu:glue 1000')
        .inputFluids('gtceu:polybenzimidazole 1000')
        .itemOutputs('16x gtceu:nami_c_dust')
        .duration(1000)
        .EUt(32768)
    ctnh.assembler('ctnhcore:nq_excite_carbon_carbon_nanofiber_structural_block')
        .itemInputs('gtceu:dense_naquadah_alloy_plate')
        .itemInputs('#gtceu:circuits/iv')
        .itemInputs('16x gtceu:nami_c_dust')
        .itemInputs("4x gtceu:ruridit_frame")
        .itemOutputs('2x ctnhcore:nq_excite_carbon_carbon_nanofiber_structural_block')
        .itemInputs('4x gtceu:double_hastelloy_c_276_plate')
        .duration(200)
        .EUt(32768)
})