const $IngotProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.IngotProperty')
GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create("andesitealloy")
    .ingot()
    .fluid()
    .color(0xA7AD9F).iconSet(GTMaterialIconSet.DULL)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("energetic_alloy")
    .ingot()
    .fluid()
    .cableProperties(GTValues.V[GTValues.MV], 1, 0, true)
    .color(0xF7CC69).iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("vibrant_alloy")
    .ingot()
    .fluid()
    .cableProperties(GTValues.V[GTValues.HV], 1, 0, true)
    .color(0xE6FB76).iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("conductive_alloy")
    .ingot()
    .fluid()
    .cableProperties(GTValues.V[GTValues.LV], 1, 0, true)
    .color(0xDAB0AA).iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("dark_steel")
    .ingot()
    .fluid()
    .color(0x858585).iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("solarium")
    .ingot()
    .fluid()
    .color(0x6C5A34).iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("end_steel")
    .ingot()
    .fluid()
    .cableProperties(GTValues.V[GTValues.EV], 1, 0, true)
    .color(0xCDC77C).iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("copper_alloy")
    .ingot()
    .fluid()
    .color(0xBB8418).iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("pulsating_alloy")
    .ingot()
    .fluid()
    .color(0x9AEBAD).iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("precious_alloy")
    .ingot()
    .ore()
    //.components('1x gold')
    .fluid()
    .color(0xA4801F).iconSet(GTMaterialIconSet.METALLIC)
    event.create("gold_alloy")
    .ingot()
    .color(0xA69226).iconSet(GTMaterialIconSet.METALLIC)
    event.create("cryolite")
    .dust()
    .ore()
    //.components('3x sodium','1x aluminum','6x fluorine')
    .color(0x8D8686)
    event.create('sodium_hexafluoroaluminate')
    .fluid()
    //.components('3x sodium','1x aluminum','6x fluorine')
    .color(0x75471F)
    event.create("gold_leach")
    .dust()
    .color(0x695D18)
    event.create("copper_leach")
    .dust()
    .color(0x70552D)
    event.create('chloroauric_acid')
    .fluid()
    .color(0xBAB02D)
    event.create('potassium_metabi_sulfite')
    .dust()
    .color(0x8D6939)
    //.components('2x sulfur','2x potassium','2x oxygen')
    event.create('alumina')
    .dust()
    .color(0x09474A)
    //.components('2x aluminum','3x oxygen')
    event.create('sodium_fluoride')
    .dust()
    .color(0x480214)
    //.components('1x sodium','1x fluorine')
    event.create('aluminium_trifluoride')
    .dust()
    .color(0x9B513E)
    //.components('1x aluminum','3x fluorine')
    event.create('sodium_hydroxide_bauxite')
    .fluid()
    .color(0xA46D2C)
    event.create('impure_aluminium_hydroxide_solution')
    .fluid()
    .color(0xC95D3A)
    event.create('pure_aluminium_hydroxide_solution')
    .fluid()
    .color(0x803DC2)
    event.create('red_mud')
    .fluid()
    .color(0xB2370D)
    event.create('neutralised_red_mud')
    .fluid()
    .color(0xAF3C15)
    event.create('red_slurry')
    .fluid()
    .color(0xAC401C)
    event.create('titanyl_sulfate')
    .fluid()
    .color(0xCC3C75)
    event.create('ferric_ree_chloride')
    .fluid()
    .color(0x3B3B2B)
    event.create('aluminium_hydroxide')
    .dust()
    .color(0x5E929D)
    event.create('sodium_hydroxide_solution')
    .fluid()
    .color(0x15286D)
    event.create('rare_earth_chloride_solution')
    .fluid()
    .color(0x393927)
    event.create('manasteel')
    .ingot()
    .color(0x438FFE)
    .secondaryColor(0x3962D7)
    .iconSet(GTMaterialIconSet.METALLIC)
    .cableProperties(GTValues.V[GTValues.LV],6,1,false)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_FRAME,GTMaterialFlags.GENERATE_RING)
    event.create('terrasteel')
    .ingot()
    .color(0x63D12F)
    .secondaryColor(0x2AB73A)
    .iconSet(GTMaterialIconSet.METALLIC)
    .cableProperties(GTValues.V[GTValues.HV],6,1,false)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_FRAME,GTMaterialFlags.GENERATE_RING)
    event.create('elementium')
    .ingot()
    .color(0xFF6CD3)
    .secondaryColor(0xDD82A3)
    .iconSet(GTMaterialIconSet.METALLIC)
    .cableProperties(GTValues.V[GTValues.MV],6,1,false)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_FRAME,GTMaterialFlags.GENERATE_RING)
    event.create('alfsteel')
    .ingot()
    .color(0xFD9D31)
    .iconSet(GTMaterialIconSet.METALLIC)
    .cableProperties(GTValues.V[GTValues.EV],6,1,false)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_FRAME,GTMaterialFlags.GENERATE_RING)
    event.create("mana_fused")
    .dust()
    .ore()
    .color(0x4FC1FF)
    event.create('iodine_enriched_solution')
    .fluid()
    .color(0x804E9B)
    event.create('netherite')
    .ingot()
    .color(0x595659)
    .secondaryColor(0x4C484C)
    .iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_FRAME,GTMaterialFlags.GENERATE_RING)
    event.create('unknown_mixture')
    .fluid()
    .color(0x979ea9)
    event.create('normal_yeast')
    .dust()
    .color(0xe3d7b7)
    event.create('normal_yeast_seed_liquid')
    .fluid()
    .color(0xe3d7b7)
    event.create('normal_yeast_liquid')
    .fluid()
    .color(0xD6C493)
    event.create('normal_yeast_extract_liquid')
    .fluid()
    .color(0xe3bb4f)
    event.create('crimson_yeast')
    .dust()
    .color(0xe58877)
    event.create('crimson_yeast_seed_liquid')
    .fluid()
    .color(0xe58877)
    event.create('crimson_yeast_liquid')
    .fluid()
    .color(0xe66f5a)
    event.create('crimson_yeast_extract_liquid')
    .fluid()
    .color(0xd85841)
    event.create('wraped_yeast')
    .dust()
    .color(0x6abbba)
    event.create('wraped_yeast_seed_liquid')
    .fluid()
    .color(0x6abbba)
    event.create('wraped_yeast_liquid')
    .fluid()
    .color(0x3a9795)
    event.create('wraped_yeast_extract_liquid')
    .fluid()
    .color(0x23807e)
    event.create('end_yeast')
    .dust()
    .color(0x8ef2eb)
    event.create('end_yeast_seed_liquid')
    .fluid()
    .color(0x8ef2eb)
    event.create('end_yeast_liquid')
    .fluid()
    .color(0x63f1e7)
    event.create('end_yeast_extract_liquid')
    .fluid()
    .color(0x3dc7bd)
    event.create('fluorescence_yeast')
    .dust()
    .color(0xe8f090)
    event.create('fluorescence_yeast_seed_liquid')
    .fluid()
    .color(0xe8f090)
    event.create('fluorescence_yeast_liquid')
    .fluid()
    .color(0xe5f163)
    event.create('fluorescence_yeast_extract_liquid')
    .fluid()
    .color(0xc7d24d)
    event.create('light_yeast')
    .dust()
    .color(0xc0e191)
    event.create('light_yeast_seed_liquid')
    .fluid()
    .color(0xc0e191)
    event.create('light_yeast_liquid')
    .fluid()
    .color(0xaae15b)
    event.create('light_yeast_extract_liquid')
    .fluid()
    .color(0x87bf38)
    event.create('waste_nutrition_liquid')
    .fluid()
    .color(0xf4db96)
    event.create('cellulose')
    .dust()
    .color(0xeee3bf)
    event.create('lignin')
    .dust()
    .color(0xb89320)
    event.create('lyase')
    .dust()
    .color(0xe4c86f)
    event.create('amino_acid')
    .fluid()
    .color(0xf4de5a)
    event.create('germanium')
    .ingot()
    .components('1x germanium')
    .color(0x434343)
    .iconSet(GTMaterialIconSet.SHINY)
    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_FRAME,GTMaterialFlags.GENERATE_RING)
    event.create('selenium')
    .dust()
    .components('1x selenium')
    .color(0xbbbc12)
    event.create('tellurium')
    .ingot()
    .components('1x tellurium')
    .iconSet(GTMaterialIconSet.METALLIC)
    .color(0xFFFFFF)
    .flags(GTMaterialFlags.GENERATE_PLATE)
    event.create('blue_vitriol_solution')
    .fluid()
    .color(0x48A5C0)
    event.create('chalcogen_anode_mud')
    .dust()
    .color(0x247a93)
    event.create('sodium_tellurite')
    .dust()
    .color(0x47d2e7)
    event.create('selenium_dioxide')
    .dust()
    .color(0xe4f437)
    event.create('tellurium_dioxide')
    .dust()
    .color(0xcbcd22)
    event.create('selenous_acid')
    .fluid()
    .color(0x8d1152)
})
StartupEvents.postInit(event =>{
    GTMaterials.get('cryolite').setFormula('Na3AlF6')
    GTMaterials.get('sodium_hexafluoroaluminate').setFormula('Na3AlF6')
    GTMaterials.get('precious_alloy').setFormula('Au?')
    GTMaterials.get('potassium_metabi_sulfite').setFormula('K2S2O2')
    GTMaterials.get('alumina').setFormula('Al2O3')
    GTMaterials.get('sodium_fluoride').setFormula('NaF')
    GTMaterials.get('aluminium_trifluoride').setFormula('AlF3')
    GTMaterials.get('sodium_hydroxide_bauxite').setFormula('(TiO2)Al2H10O29-Na(OH)2')
    GTMaterials.get('gold_leach').setFormula('(Au)')
    GTMaterials.get('copper_leach').setFormula('(Cu)')
    GTMaterials.get('chloroauric_acid').setFormula('AuCl3')
    GTMaterials.get('impure_aluminium_hydroxide_solution').setFormula('(Al(OH)3)')
    GTMaterials.get('pure_aluminium_hydroxide_solution').setFormula('Al(OH)3')
    GTMaterials.get('red_mud').setFormula('Ti?Fe?')
    GTMaterials.get('neutralised_red_mud').setFormula('Ti?Fe?')
    GTMaterials.get('red_slurry').setFormula('Ti?')
    GTMaterials.get('titanyl_sulfate').setFormula('TiO(SO4)')
    GTMaterials.get('ferric_ree_chloride').setFormula('(FeCl3)')
    GTMaterials.get('aluminium_hydroxide').setFormula('Al(OH)3')
    GTMaterials.get('sodium_hydroxide_solution').setFormula('NaOH')
    GTMaterials.get('precious_alloy').setFormula('Au?')
    GTMaterials.get('precious_alloy').setFormula('Au?')
    GTMaterials.get('precious_alloy').setFormula('Au?')
    GTMaterials.get('andesitealloy').setFormula('(Mg3Si2H4O9)4(KNO3)Fe')
    GTMaterials.get('cellulose').setFormula('(C6H10O5)n')
    GTMaterials.get('lignin').setFormula('(CH2ON?S?)n')
})
GTCEuStartupEvents.registry('gtceu:element', event => {
    event.create('germanium', 32, 40, -1, null, 'Ge', false) // 
    event.create('selenium',34,46,-1,null,'Se',false)
    event.create('tellurium',52,74,-1,null,'Te',false)

 })