// priority: 100
const $LocalizationUtils = Java.loadClass("com.lowdragmc.lowdraglib.utils.LocalizationUtils")
const $FluidBuilder = Java.loadClass("com.gregtechceu.gtceu.api.fluids.FluidBuilder")
const $WireProperties = Java.loadClass("com.gregtechceu.gtceu.api.data.chemical.material.properties.WireProperties")
const $BloodMagicAPI = Java.loadClass("wayoftime.bloodmagic.impl.BloodMagicAPI")
const $FoodEatenEventJS = Java.loadClass("dev.latvian.mods.kubejs.item.FoodEatenEventJS")
const $RangedAttribute = Java.loadClass("net.minecraft.world.entity.ai.attributes.RangedAttribute")
const $Registry = Java.loadClass("net.minecraft.core.Registry")
const $ServerLevel = Java.loadClass("net.minecraft.server.level.ServerLevel")
const $TagKey = Java.loadClass("net.minecraft.tags.TagKey")
const $EyeOfEnder = Java.loadClass("net.minecraft.world.entity.projectile.EyeOfEnder")
const $ItemStack = Java.loadClass("net.minecraft.world.item.ItemStack")
const $Entity = Java.loadClass("net.minecraft.world.entity.Entity")
const $HellForgeMachine = Java.loadClass("io.github.cpearl0.ctnhcore.common.machine.multiblock.magic.HellForgeMachine")

const $ArrayList = Java.loadClass("java.util.ArrayList")
