// 代码来源于Create Delights，原作者为SSW，已获得授权
Ponder.registry(event => {
    event.create(["ae2:crafting_unit"])
        .scene(
            "kubejs:crafting_processing_unit",
            "CPU的搭建",
            "kubejs:ponder_crafting_processing_unit",
        (builder, util) => {
            let scene = new $CreateSceneBuilder(builder)
                scene.world.showSection([0, 0, 0, 8, 0, 8], Direction.DOWN)
                scene.idle(20)
                scene.text(40, "CPU的搭建有一定的规则……")
                scene.idle(60)
                scene.world.showSection([1, 1, 1], Direction.DOWN)
                scene.idle(10)
                scene.world.showSection([3, 1, 1, 4, 1, 1], Direction.DOWN)
                scene.idle(10)
                scene.world.showSection([6, 1, 1, 7, 2, 1], Direction.DOWN)
                scene.idle(10)
                scene.text(40, "CPU的形体必须得是长方体")
                scene.idle(60)
                scene.rotateCameraY(90)
                scene.idle(20)
                scene.world.showSection([1, 1, 3, 2, 2, 4], Direction.DOWN)
                scene.idle(10)
                scene.world.showSection([4, 1, 3, 5, 1, 4], Direction.DOWN)
                scene.idle(10)
                scene.world.showSection([7, 1, 3, 8, 2, 4], Direction.DOWN)
                scene.idle(20)
                scene.text(40, "不为长方体的CPU则不会显示以成型的状态")
                scene.idle(60)
                scene.world.showSection([1, 1, 6, 2, 2, 7], Direction.DOWN)
                scene.idle(20)
                scene.overlay.showOutline("red", {}, [1, 1, 6, 2, 2, 7], 40)
                scene.text(60, "CPU结构内至少需要有一个合成存储器", [2, 3, 7])
                scene.idle(80)
                scene.world.showSection([4, 1, 6, 5, 2, 7], Direction.DOWN)
                scene.idle(20)
                scene.overlay.showOutline("green", {}, [4, 1, 6, 5, 2, 7], 40)
                scene.text(60, "其余部分则可使用合成单元，合成监控室，合成存储器，并行处理单元代替", [5, 3, 7])
                scene.idle(80)
            })
})