ServerEvents.recipes(event => {


    event.recipes.gtceu.mana_generator('gtceu:blood_fuel')
        .inputFluids('gtceu:blood_fuel 6666')
        .EUt(-32)
        .outputFluids('bloodmagic:life_essence_fluid 6666')
        .duration(80)
    event.recipes.gtceu.mana_generator('gtceu:blood_fuel_active')
        .inputFluids('gtceu:blood_fuel_active 666')
        .EUt(-78)
        .outputFluids('gtceu:blood_fuel_exhausted 666')
        .duration(100)
    event.recipes.gtceu.mana_generator('gtceu:elf_fuel')
        .inputFluids('gtceu:elf_fuel 100')
        .EUt(-64)
        .outputFluids('gtceu:mana 5')
        .outputFluids('gtceu:neon 10')
        .duration(200)
    event.recipes.gtceu.mana_generator('gtceu:elf_active_fuel')
        .inputFluids('gtceu:elf_active_fuel 100')
        .EUt(-108)
        .outputFluids('gtceu:mana_stable_cooldown 3')
        .outputFluids('gtceu:elf_fuel 1')
        .duration(200)
    event.recipes.gtceu.mana_generator('gtceu:starlight_fuel')
        .inputFluids('gtceu:starlight_fuel 100')
        .EUt(-128)
        .outputFluids('gtceu:mana_stable_cooldown 6')
        .duration(120)
    event.recipes.gtceu.mana_generator('gtceu:starlight_fuel_active')
        .inputFluids('gtceu:starlight_fuel_active 100')
        .EUt(-168)
        .outputFluids('gtceu:starlight_fuel_exhausted 100')
        .duration(240)
    event.recipes.gtceu.mana_generator('gtceu:mana_up_fuel_active')
        .inputFluids('gtceu:mana_up_fuel_active 100')
        .EUt(-384)
        .outputFluids('gtceu:mana_up_fuel_exhausted 100')
        .duration(280)
    event.recipes.gtceu.mana_generator('gtceu:mana_up_fuel')
        .inputFluids('gtceu:mana_up_fuel 100')
        .EUt(-128)
        .outputFluids('gtceu:mana_up_fuel 5')
        .duration(120)

})