// ServerEvents.recipes(event => {
//     //存放着所有戴森光束的配方
//     let ctnh = event.recipes.gtceu
//     event.recipes.gtceu.assembly_line("beams")
//         .itemInputs('32x kubejs:zenith_star')
//         .itemInputs('32x #gtceu:circuits/uv')
//         .itemInputs('64x gtceu:ultra_mana_frame')
//         .itemInputs('32x gtceu:superconducting_coil')
//         .itemInputs('64x kubejs:mana_circuit_board')
//         .itemInputs('8x ctnhcore:ulta_mana_coil_block')
//         .itemInputs('64x gtceu:ultra_mana_quadruple_cable')
//         .itemInputs('64x gtceu:ender_pearl_block')
//         .itemInputs('8x ctnhcore:starlight_rune')
//         .itemInputs('4x ctnhcore:twist_rune')
//         .itemInputs('8x ctnhcore:horizen_rune')
//         .itemInputs('ctnhcore:quasar_rune')
//         .itemInputs('32x gtceu:high_power_casing')
//         .inputFluids(Fluid.of('gtceu:zenith_essence', 14400))
//         .inputFluids(Fluid.of('gtceu:mana_radiation_mixture', 144000))
//         .inputFluids(Fluid.of('bloodmagic:life_essence_fluid', 144000))
//         .inputFluids(Fluid.of('gtceu:enriched_naquadah', 1440))
//         .itemOutputs('ctnhcore:nicoll_dyson_beams')
//         .stationResearch(b => b.researchStack(Item.of('kubejs:zenith_star'))
//             .dataStack(Item.of("gtceu:data_orb"))
//             .EUt(GTValues.VA[GTValues.ZPM])
//             .CWUt(32))
//         .EUt(524288)
//         .duration(1000)
//     event.recipes.gtceu.beams("iron_1")
//         .itemInputs('512x minecraft:iron_ingot')
//         .circuit(1)
//         .addData("required_mana", 100000)
//         .addData("mana", 10000)
//         .itemOutputs('512x botania:manasteel_ingot')
//         .duration(50)
//     event.recipes.gtceu.beams("iron_2")
//         .itemInputs('512x minecraft:iron_ingot')
//         .circuit(2)
//         .addData("required_mana", 500000)
//         .addData("mana", 100000)
//         .itemOutputs('512x botania:elementium_ingot')
//         .duration(100)
//         .EUt(1)

//     event.recipes.gtceu.beams("iron_3")
//         .itemInputs('512x minecraft:iron_ingot')
//         .circuit(3)
//         .addData("required_mana", 1000000)
//         .addData("mana", 500000)
//         .itemOutputs('512x mythicbotany:alfsteel_ingot')
//         .duration(200)
//         .EUt(1)

//     .EUt(1)
//     event.recipes.gtceu.beams("eve")
//         .itemInputs('8x ctnhcore:twist_rune')
//         .addData("required_mana", 5000000)
//         .addData("mana", 2000000)
//         .inputFluids(Fluid.of('gtceu:mana_radiation_mixture', 1000000))
//         .outputFluids(Fluid.of('gtceu:eve_plasma', 100000))
//         .duration(200)
//         .EUt(200000)
//     event.recipes.gtceu.beams("nq_1")
//         .itemInputs('128x gtceu:naquadah_ingot')
//         .addData("required_mana", 5000000)
//         .addData("mana", 1000000)
//         .inputFluids(Fluid.of('gtceu:eve_plasma', 1000))
//         .itemOutputs('64x gtceu:naquadria_ingot')
//         .duration(200)
//         .EUt(1000000)
//     event.recipes.gtceu.beams("nq_2")
//         .itemInputs('640x gtceu:naquadah_ingot')
//         .addData("required_mana", 5000000)
//         .addData("mana", 1000000)
//         .inputFluids(Fluid.of('gtceu:eve_plasma', 1000))
//         .itemOutputs('480x gtceu:enriched_naquadah')
//         .duration(200)
//         .EUt(1000000)
//     event.recipes.gtceu.beams('botania:placeholder')
//         .itemInputs('1024x botania:placeholder')
//         .itemOutputs('1024x botania:rune_mana')
//         .addData("required_mana", 500000)
//         .addData("mana", 100000)
//         .duration(200)
//         .EUt(1)
//     event.recipes.gtceu.beams("mana_1")
//         .itemInputs('64x gtceu:mana_plus_ingot')
//         .addData("required_mana", 2000000)
//         .addData("mana", 1000000)
//         .itemOutputs('64x gtceu:mana_super_plus_ingot')
//         .circuit(1)
//         .duration(200)
//         .EUt(1)
//     event.recipes.gtceu.beams("mana_2")
//         .itemInputs('64x gtceu:mana_plus_ingot')
//         .addData("required_mana", 5000000)
//         .addData("mana", 4000000)
//         .inputFluids(Fluid.of('gtceu:mana_radiation_mixture', 10000))
//         .itemOutputs('64x gtceu:ultra_mana_ingot')
//         .duration(200)
//         .EUt(10000)
//     event.recipes.gtceu.beams("mana_3")
//         .itemInputs('128x gtceu:mana_plus_ingot')
//         .addData("required_mana", 10000000)
//         .addData("mana", 5000000)
//         .inputFluids(Fluid.of('gtceu:eve_plasma', 10000))
//         .itemOutputs('128x gtceu:ultra_mana_ingot')
//         .duration(500)
//         .EUt(1000000)
//     event.recipes.gtceu.beams('rune10')
//         .itemInputs("1024x botania:livingrock")
//         .addData("required_mana", 500000)
//         .addData("mana", 100000)
//         .itemOutputs('1024x bloodmagic:blankslate')
//         .duration(200)
//         .EUt(1)
//     event.recipes.gtceu.beams('rune20')
//         .itemInputs('1024x bloodmagic:blankslate')
//         .addData("required_mana", 500000)
//         .addData("mana", 200000)
//         .itemOutputs('1024x bloodmagic:reinforcedslate')
//         .duration(200)
//         .EUt(1)
//     event.recipes.gtceu.beams('rune30')
//         .itemInputs('1024x bloodmagic:reinforcedslate')
//         .addData("required_mana", 750000)
//         .addData("mana", 400000)
//         .itemOutputs('1024x bloodmagic:infusedslate')
//         .duration(200)
//         .EUt(1960)
//     event.recipes.gtceu.beams('rune40')
//         .itemInputs('512x bloodmagic:infusedslate')
//         .addData("required_mana", 1000000)
//         .addData("mana", 500000)
//         .itemOutputs('512x bloodmagic:demonslate')
//         .duration(400)
//         .EUt(19600)
//     event.recipes.gtceu.beams('rune5')
//         .itemInputs('256x bloodmagic:demonslate')
//         .addData("required_mana", 1250000)
//         .addData("mana", 500000)
//         .itemOutputs('256x bloodmagic:etherealslate')
//         .duration(400)
//         .EUt(7680)
//     event.recipes.gtceu.beams('rune6')
//         .itemInputs('128x bloodmagic:etherealslate')
//         .addData("required_mana", 2500000)
//         .addData("mana", 1000000)
//         .itemOutputs('128x kubejs:endslate')
//         .duration(1000)
//         .EUt(1000000)
//     event.recipes.gtceu.beams('nq_up1')
//         .itemInputs('1280x gtceu:naquadah_oxide_mixture_dust')
//         .addData("required_mana", 1000000)
//         .addData("mana", 500000)
//         .outputFluids(Fluid.of('gtceu:naquadah', 172800))
//         .duration(180)
//         .EUt(100000)
//     event.recipes.gtceu.beams('nq_up2')
//         .itemInputs('1680x gtceu:enriched_naquadah_oxide_mixture_dust')
//         .addData("required_mana", 3000000)
//         .addData("mana", 2000000)
//         .outputFluids(Fluid.of('gtceu:enriched_naquadah', 172800))
//         .duration(180)
//         .EUt(400000)
//     event.recipes.gtceu.beams('nq_up3')
//         .itemInputs('1280x gtceu:naquadria_oxide_mixture_dust')
//         .addData("required_mana", 5000000)
//         .addData("mana", 4000000)
//         .outputFluids(Fluid.of('gtceu:naquadria', 115200))
//         .duration(400)
//         .EUt(1000000)
//     event.recipes.gtceu.beams('minecraft:amethyst_cluster')
//         .itemInputs('1280x minecraft:amethyst_shard')
//         .notConsumable('kubejs:endslate')
//         .itemOutputs('640x bloodmagic:defaultcrystal')
//         .duration(20)
//         .addData("required_mana", 5000000)
//         .addData("mana", 2000000)
//         .EUt(100000)
//     event.recipes.gtceu.beams('gtceu:adamantite_dust')
//         .itemInputs('128x gtceu:adamantite_dust')
//         .itemInputs('128x gtceu:taranium_powder_dust')
//         .itemInputs('128x gtceu:ultra_mana_dust')
//         .inputFluids(Fluid.of('gtceu:star_fuel', 50000))
//         .outputFluids(Fluid.of('gtceu:star_fuel_active', 90000))
//         .addData("required_mana", 15000000)
//         .addData("mana", 10000000)
//         .duration(400)
//         .EUt(1000000)
//     event.recipes.gtceu.beams('bloodmagic:weakbloodshard')
//         .itemInputs('256x bloodmagic:strong_tau')
//         .itemOutputs('512x bloodmagic:weakbloodshard')
//         .addData("required_mana", 2000000)
//         .addData("mana", 1000000)
//         .duration(200)
//         .EUt(10000)
//     event.recipes.gtceu.beams('kubejs:mana_circuit_board')
//         .itemOutputs('256x kubejs:mana_circuit_board')
//         .itemInputs('256x gtceu:reinforced_epoxy_resin_plate')
//         .itemInputs('256x gtceu:ultra_mana_foil')
//         .inputFluids(Fluid.of('gtceu:zenith_essence', 16000))
//         .addData("required_mana", 5000000)
//         .addData("mana", 1000000)
//         .duration(200)
//         .EUt(40000)

//     event.recipes.gtceu.beams('gtceu:agn_fuel_active_plasma_endless')
//         .outputFluids(Fluid.of('gtceu:agn_fuel_active_plasma', 100))
//         .inputFluids(Fluid.of('gtceu:agn_fuel_plasma', 1000))
//         .itemInputs('ctnhcore:eye_of_quasar')
//         .addData("required_mana", 500000000)
//         .addData("mana", 100000000)
//         .duration(2000)
//         .EUt(40000000)
//     event.recipes.gtceu.beams("mana_radiation_mixture")
//         .itemInputs('300x gtceu:thorium_dust')
//         .itemInputs('300x gtceu:uranium_235_dust')
//         .itemInputs('300x gtceu:plutonium_241_dust')
//         .itemInputs('300x gtceu:naquadah_dust')
//         .inputFluids(Fluid.of('gtceu:zenith_essence', 30000))
//         .outputFluids(Fluid.of("gtceu:mana_radiation_mixture", 400000))
//         .EUt(55555)
//         .addData("required_mana", 5000000)
//         .addData("mana", 5000000)
//         .duration(400)
//     event.recipes.gtceu.beams('zenith')
//         .itemInputs('100x apotheosis:infused_breath')
//         .itemInputs("100x ars_nouveau:source_gem_block")
//         .inputFluids(Fluid.of("gtceu:mana", 10000))
//         .outputFluids(Fluid.of("gtceu:zenith_essence", 300000))
//         .duration(400)
//         .addData("required_mana", 5000000)
//         .addData("mana", 1000000)
//         .EUt(66666)
//     event.recipes.gtceu.beams('kubejs:umlhpic_wafer')
//         .itemOutputs('320x kubejs:umlhpic_wafer')
//         .itemInputs('320x gtceu:uhpic_wafer')
//         .itemInputs('10x ctnhcore:twist_rune')
//         .itemInputs('100x gtceu:ultra_mana_dust')
//         .inputFluids(Fluid.of('gtceu:zenith_essence', 40000))
//         .EUt(32678 * 8)
//         .addData("required_mana", 10000000)
//         .addData("mana", 5000000)
//         .duration(400)
// })