GTCEuStartupEvents.registry("gtceu:element", event => {
    event.create('mana_lp_mixed')
        .symbol('Ma??lp')
    event.create('mana_demon_mixed')
        .symbol('Ma?lp+')
    event.create('mana_mixed')
        .symbol('Ma???')
})
GTCEuStartupEvents.registry("gtceu:material", event => {
    GTMaterials.get("darmstadtium").addFlags(GTMaterialFlags.GENERATE_GEAR)
    GTMaterials.get('neutronium').addFlags(GTMaterialFlags.GENERATE_SMALL_GEAR)
})

GTCEuStartupEvents.registry("gtceu:material", event => {
    event.create("dark_steel")
        .ingot()
        .liquid()
        .components("1x steel", "1x obsidian")
        .blastTemp(1400, "low", 480, 200)
        .color(0x858585).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("soularium")
        .ingot()
        .liquid()
        .color(0x6C5A34).iconSet(GTMaterialIconSet.DULL)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("copper_alloy")
        .ingot()
        .liquid()
        .color(0xBB8418).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("redstone_alloy")
        .ingot()
        .liquid()
        .color(0xed3b50)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("pulsating_alloy")
        .ingot()
        .liquid()
        .color(0x9AEBAD).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("gold_alloy")
        .ingot()
        .color(0xA69226).iconSet(GTMaterialIconSet.METALLIC)
    event.create("sodium_hexafluoroaluminate")
        .liquid()
        //.components("3x sodium","1x aluminum","6x fluorine")
        .color(0x75471F)
    event.create("gold_leach")
        .dust()
        .color(0x695D18)
    event.create("copper_leach")
        .dust()
        .color(0x70552D)
    event.create("chloroauric_acid")
        .liquid()
        .color(0xBAB02D)
    event.create("potassium_metabi_sulfite")
        .dust()
        .color(0x8D6939)
        //.components("2x sulfur","2x potassium","2x oxygen")
    event.create("sodium_fluoride")
        .dust()
        .color(0x480214)
        //.components("1x sodium","1x fluorine")
    event.create("aluminium_trifluoride")
        .dust()
        .color(0x9B513E)
        //.components("1x aluminum","3x fluorine")
    event.create("sodium_hydroxide_bauxite")
        .liquid()
        .color(0xA46D2C)
    event.create("impure_aluminium_hydroxide_solution")
        .liquid()
        .color(0xC95D3A)
    event.create("pure_aluminium_hydroxide_solution")
        .liquid()
        .color(0x803DC2)
    event.create("red_mud")
        .liquid()
        .color(0xB2370D)
    event.create("neutralised_red_mud")
        .liquid()
        .color(0xAF3C15)
    event.create("red_slurry")
        .liquid()
        .color(0xAC401C)
    event.create("titanyl_sulfate")
        .liquid()
        .color(0xCC3C75)
    event.create("ferric_ree_chloride")
        .liquid()
        .color(0x3B3B2B)
    event.create("aluminium_hydroxide")
        .dust()
        .color(0x5E929D)
    event.create("sodium_hydroxide_solution")
        .liquid()
        .color(0x15286D)
    event.create("rare_earth_chloride_solution")
        .liquid()
        .color(0x393927)
    event.create("iodine_enriched_solution")
        .liquid()
        .color(0x804E9B)
    event.create("unknown_mixture")
        .liquid()
        .color(0x979ea9)
    event.create("normal_yeast")
        .dust()
        .color(0xe3d7b7)
    event.create("normal_yeast_seed_liquid")
        .liquid()
        .color(0xe3d7b7)
    event.create("normal_yeast_liquid")
        .liquid()
        .color(0xD6C493)
    event.create("normal_yeast_extract_liquid")
        .liquid()
        .color(0xe3bb4f)
    event.create("crimson_yeast")
        .dust()
        .color(0xe58877)
    event.create("crimson_yeast_seed_liquid")
        .liquid()
        .color(0xe58877)
    event.create("crimson_yeast_liquid")
        .liquid()
        .color(0xe66f5a)
    event.create("crimson_yeast_extract_liquid")
        .liquid()
        .color(0xd85841)
    event.create("warped_yeast")
        .dust()
        .color(0x6abbba)
    event.create("warped_yeast_seed_liquid")
        .liquid()
        .color(0x6abbba)
    event.create("warped_yeast_liquid")
        .liquid()
        .color(0x3a9795)
    event.create("warped_yeast_extract_liquid")
        .liquid()
        .color(0x23807e)
    event.create("end_yeast")
        .dust()
        .color(0x8ef2eb)
    event.create("end_yeast_seed_liquid")
        .liquid()
        .color(0x8ef2eb)
    event.create("end_yeast_liquid")
        .liquid()
        .color(0x63f1e7)
    event.create("end_yeast_extract_liquid")
        .liquid()
        .color(0x3dc7bd)
    event.create("fluorescence_yeast")
        .dust()
        .color(0xe8f090)
    event.create("fluorescence_yeast_seed_liquid")
        .liquid()
        .color(0xe8f090)
    event.create("fluorescence_yeast_liquid")
        .liquid()
        .color(0xe5f163)
    event.create("fluorescence_yeast_extract_liquid")
        .liquid()
        .color(0xc7d24d)
    event.create("light_yeast")
        .dust()
        .color(0xc0e191)
    event.create("light_yeast_seed_liquid")
        .liquid()
        .color(0xc0e191)
    event.create("light_yeast_liquid")
        .liquid()
        .color(0xaae15b)
    event.create("light_yeast_extract_liquid")
        .liquid()
        .color(0x87bf38)
    event.create("polluted_fluorescence_yeast")
        .dust()
        .color(0x217523)
    event.create("radiation_mutated_yeast")
        .dust()
        .color(0x567a22)
    event.create("radiation_mutated_yeast_seed_liquid")
        .liquid()
        .color(0x567a22)
    event.create("radiation_mutated_yeast_liquid")
        .liquid()
        .color(0x46661a)
    event.create("radiation_mutated_yeast_extract_liquid")
        .liquid()
        .color(0x466916)
    event.create("waste_nutrition_liquid")
        .liquid()
        .color(0xf4db96)
    event.create("cellulose")
        .dust()
        .color(0xeee3bf)
    event.create("lignin")
        .dust()
        .color(0xb89320)
    event.create("lyase")
        .dust()
        .color(0xe4c86f)
    event.create("amino_acid")
        .liquid()
        .color(0xf4de5a)
    event.create("blue_vitriol_solution")
        .liquid()
        .color(0x48A5C0)
    event.create("chalcogen_anode_mud")
        .dust()
        .color(0x247a93)
    event.create("sodium_tellurite")
        .dust()
        .color(0x47d2e7)
    event.create("selenium_dioxide")
        .dust()
        .color(0xe4f437)
        .components('selenium', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("tellurium_dioxide")
        .dust()
        .color(0xcbcd22)
        .components('tellurium', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("selenous_acid")
        .liquid()
        .color(0x8d1152)
        .components('2x hydrogen', 'selenium', '3x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("ammonium_sulfate")
        .liquid()
        .color(0x2759e7)
        .components('2x ammonia', 'sulfur', '4x oxygen')
    event.create("ammonium_carbonate")
        .dust()
        .color(0x2654d8)
        .components('2x ammonia', 'carbon', '3x oxygen')
    event.create("potassium_bisulfite")
        .dust()
        .color(0xb0afa5)
        .components("1x potassium", "1x sulfur", "1x hydrogen", "3x oxygen")
    event.create("potassium_nitrite")
        .dust()
        .color(0xc5c3b2)
    event.create("nitrous_acid")
        .liquid()
        .color(0xe2deb2)
        .components("1x hydrogen", "1x nitrogen", "2x oxygen")
    event.create("sodium_acetate")
        .liquid()
        .color(0x80e566)
    event.create("potassium_hydroxylamine_disulfonate")
        .dust()
        .color(0x3f7a30)
        .components("2x potassium", "1x nitrogen", "1x hydrogen", "2x sulfur", "7x oxygen")
    event.create("hydroxylammonium_sulfate")
        .dust()
        .color(0xa0a591)
        .components("2x nitrogen", "8x hydrogen", "1x sulfur", "6x oxygen")
    event.create("barium_chloride")
        .dust()
        .color(0xd26d4f)
        .components("1x barium", "2x chlorine")
    event.create("barium_sulfate_solution")
        .liquid()
        .color(0xa7c6e6)
    event.create("hydroxylamine_hydrochloride")
        .liquid()
        .color(0xe33333)
    event.create("succinic_acid")
        .dust()
        .color(0x0f6f6d)
    event.create("succinic_anhydride")
        .dust()
        .color(0x634010)
    event.create("acetylene")
        .gas()
        .color(0x8eb256)
        .components("2x carbon", "2x hydrogen")
    event.create("tetrahydrofuran")
        .liquid()
        .color(0x8fe5bc)
    event.create("nhydroxy_succinimide")
        .dust()
        .color(0x997db2)
    event.create("triethylamine")
        .liquid()
        .color(0x52686a)
    event.create("succinimidyl_acetate")
        .dust()
        .color(0x855c75)
    event.create("glyoxal")
        .liquid()
        .color(0xf0ed4d)
        .components("2x carbon", "2x hydrogen", "2x oxygen")
    event.create("ammonium_acetate")
        .dust()
        .color(0x73a3a7)
    event.create("acetamide")
        .dust()
        .color(0x638e92)
    event.create("acetonitrile")
        .dust()
        .color(0x889fb5)
        .components('carbon', '3x hydrogen', 'carbon', 'nitrogen')
    event.create("benzyl_chloride")
        .liquid()
        .color(0x85e7e7)
        .components("7x carbon", "7x hydrogen", "1x chlorine")
    event.create("hexamethylenetetramine")
        .dust()
        .color(0x5a6261)
        .components("6x carbon", "12x hydrogen", "4x nitrogen")
    event.create("benzylamine")
        .liquid()
        .color(0x5b6363)
        .components("7x carbon", "9x hydrogen", "1x nitrogen")
    event.create("hexabenzylhexaazaisowurtzitane")
        .dust()
        .color(0x4a2367)
        .components("48x carbon", "48x hydrogen", "6x nitrogen")
    event.create("palladium_chloride")
        .dust()
        .color(0xcfcfcf)
        .components("1x palladium", "2x chlorine")
    event.create("dibenzyl_tetraacetylhexaazaisowurtzitane")
        .dust()
        .color(0x8ea268)
        .components("28x carbon", "32x hydrogen", "6x nitrogen", "4x oxygen")
    event.create("succinimide")
        .dust()
        .color(0x21a7c5)
    event.create("boron_fluoride")
        .liquid()
        .components("1x boron", "3x fluorine")
        .color(0xcecad0)
    event.create("nitronium_tetrafluoroborate")
        .dust()
        .color(0x3c3f40)
        .components("1x nitrogen", "2x oxygen", "1x boron", "4x fluorine")
    event.create("nitrosonium_tetrafluoroborate")
        .dust()
        .color(0x485054)
        .components("1x nitrogen", "1x oxygen", "1x boron", "4x fluorine")
    event.create("tetraacetyldinitrosohexaazaisowurtzitane")
        .dust()
        .color(0x500449)
    event.create("tetrafluoroboric_acid")
        .liquid()
        .color(0x7c8915)
    event.create("benzaldehyde")
        .liquid()
        .color(0x905a1b)
        .components("7x carbon", "6x hydrogen", "1x oxygen")
    event.create("crude_hexanitro_hexaazaisowurtzitane")
        .dust()
        .color(0x19586d)
    event.create("ethylenediamine")
        .liquid()
        .color(0x1b5d74)
        .components("2x carbon", "8x hydrogen", "2x nitrogen")
    event.create("silica_gel")
        .dust()
        .color(0x57c3e4)
    event.create("hexanitro_hexaazaisowurtzitane")
        .dust()
        .color(0x3d464b)
    event.create("boric_acid")
        .liquid()
        .color(0x8fbc8f)
    event.create("dimethylformamide")
        .liquid()
        .color(0x34f4a5)
    event.create("sodium_periodate")
        .dust()
        .color(0x1438bb)
        .components("1x sodium", "1x iodine", "4x oxygen")
        .iconSet(GTMaterialIconSet.METALLIC)
    event.create("calcium_carbide")
        .dust()
        .color(0x3e4133)
        .components("1x carbon", "1x calcium")
    event.create("escherichia_coli")
        .dust()
        .color(0x014d15)
    event.create("sodium_iodate")
        .dust()
        .color(0x0e2887)
    event.create("sodium_sulfate_solution")
        .liquid()
        .color(0x454141)
    event.create("sodium_iodide")
        .dust()
        .color(0x335187)
        .components("1x sodium", "1x iodine")
    event.create("aeternium")
        .dust()
        .color(0x376169)
        .secondaryColor(0x2c7d74)
    event.create("ancient_debris")
        .dust()
        .color(0x59342a)
        .secondaryColor(0x734437)
    event.create("ancient_debris_leach")
        .liquid()
        .color(0x7a4437)
    event.create("hydrobromic_acid")
        .liquid()
        .color(0xd1593e)
        .components("1x hydrogen", "1x bromine")
    event.create("boron_oxide")
        .dust()
        .color(0x87cfed)
        .components("2x boron", "3x oxygen")
    event.create("flinak")
        .dust()
        .liquid()
        .color(0x5c5757)
        .components("3x fluorine", "1x lithium", "1x sodium", "1x potassium")
    event.create("silicon_chloride")
        .liquid()
        .color(0x8ba4b0)
    event.create("barium_hydroxide")
        .dust()
        .color(0x58c95c)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("mesityl_oxide")
        .liquid()
        .color(0x97f78b)
    event.create("methyl_isobutyl_ketone")
        .liquid()
        .color(0x56d652)
    event.create("thiocyanic_acid")
        .liquid()
        .color(0xfffc64)
        .components("1x sulfur", "1x hydrogen_cyanide")
    event.create("zr_hf_separation_mix")
        .liquid()
        .color(0xcff760)
    event.create("zr_hf_chloride")
        .liquid()
        .color(0x65f04a)
    event.create("zircon_chlorinating_residue")
        .liquid()
        .color(0x50ba3a)
    event.create("zr_hf_oxy_chloride")
        .liquid()
        .color(0x70b063)
    event.create("cubic_zirconia")
        .dust()
        .color(0xf9e0fc)
        .components("1x zirconium", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("hafnium_oxide")
        .dust()
        .color(0x6b6e6b)
        .components("1x hafnium", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("hafnium_chloride")
        .dust()
        .color(0x9da19c)
        .components("1x hafnium", "4x chlorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("uranyl_chloride_solution")
        .liquid()
        .color(0xc5de56)
    event.create("uranyl_nitrate_solution")
        .liquid()
        .color(0xcae065)
    event.create("purified_uranyl_nitrate")
        .liquid()
        .color(0xe5f552)
    event.create("uranium_sulfate_waste_solution")
        .liquid()
        .color(0x9eb837)
    event.create("uranium_diuranate")
        .liquid()
        .color(0xc7db42)
    event.create("potassium_uranyl_tricarbonate")
        .dust()
        .color(0xd4e04c)
    event.create("piranha_solution")
        .liquid()
        .color(0x6c5ff5)
    event.create("uranium_refinement_waste_solution")
        .liquid()
        .color(0xc6db5b)
    event.create("uranium_peroxide_thorium_oxide")
        .dust()
        .color(0x5b5c5a)
    event.create("caesium_hydroxide")
        .dust()
        .color(0xdadbd6)
        .components("1x caesium", "1x oxygen", "1x hydrogen")
    event.create("molybdenum_trioxide")
        .dust()
        .color(0x8f8ae5)
        .components("1x molybdenum", "3x oxygen")
    event.create("uranium_thorium_oxide")
        .dust()
        .color(0x666665)
    event.create("uranyl_thorium_sulfate")
        .dust()
        .color(0xdced3f)
    event.create("uranyl_thorium_nitrate")
        .dust()
        .color(0xdff236)
    event.create("uranium_oxide_thorium_nitrate")
        .dust()
        .color(0x62f236)
    event.create("uranium_dioxide")
        .dust()
        .color(0x4ecf26)
        .components("1x uranium", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("thorium_nitrate_solution")
        .liquid()
        .color(0x4bab2d)
        .components("1x thorium", "1x nitrogen", "3x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("thorium_oxide")
        .dust()
        .color(0x757373)
        .components("1x thorium", "1x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("dirty_hexafluorosilicic_acid")
        .liquid()
        .color(0xdb6767)
    event.create("dilute_hexafluorosilicic_acid")
        .liquid()
        .color(0x7ae880)
    event.create("stone_residue")
        .dust()
        .color(0xa1a19e)
    event.create("fluorosilicic_acid")
        .liquid()
        .color(0x40ed57)
        .components("2x hydrogen", "1x silicon", "6x fluorine")
    event.create("uncommon_residues")
        .dust()
        .color(0x4f86c9)
    event.create("dioxygendifluoride")
        .liquid()
        .color(0x4fbbc9)
        .components("2x fluorine", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("partially_oxidized_residues")
        .dust()
        .color(0x853525)
    event.create("inert_residues")
        .dust()
        .color(0x9d85a6)
    event.create("oxidized_residual_solution")
        .liquid()
        .color(0x83f2e1)
    event.create("oxidized_residues")
        .dust()
        .color(0x5e2b87)
    event.create("heavy_oxidized_residues")
        .dust()
        .color(0x5d208f)
    event.create("metallic_residues")
        .dust()
        .color(0x22a372)
    event.create("heavy_metallic_residues")
        .dust()
        .color(0x3488b5)
    event.create("diamagnetic_residues")
        .dust()
        .color(0x4cd98e)
    event.create("paramagnetic_residues")
        .dust()
        .color(0x4cbfd9)
    event.create("ferromagnetic_residues")
        .dust()
        .color(0x32b065)
    event.create("heavy_diamagnetic_residues")
        .dust()
        .color(0x3269b0)
    event.create("heavy_paramagnetic_residues")
        .dust()
        .color(0x2d9e4d)
    event.create("heavy_ferromagnetic_residues")
        .dust()
        .color(0x1e873b)
    event.create("exotic_heavy_residues")
        .dust()
        .color(0x26a2b5)
    event.create("clean_inert_residues")
        .dust()
        .color(0x0ebd54)
    event.create("dilute_hydrofluoric_acid")
        .liquid()
        .color(0xc7d7de)
        .components("1x hydrogen", "1x fluorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("helium3_hydride")
        .liquid()
        .color(0xd7e36a)
        .components("1x helium_3", "1x hydrogen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("ultraacidic_residue_solution")
        .liquid()
        .color(0x59ff7d)
    event.create("liquid_fluorine")
        .liquid(new $FluidBuilder()
            .temperature(100))
        .color(0x26a4e8)
        .components("1x fluorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    //event.create("ultra_mana")
    //    .ingot()
    //    .color(0x4ac6e6)
    //    .blastTemp(7200, "highest", 122222, 1000)
    //    .cableProperties(GTValues.V[GTValues.ZPM], 8, 1, false)
    //    .iconSet(GTMaterialIconSet.METALLIC)
    //    .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
    //    .element(GTElements.get('mana_ultra'))
    event.create("sodium_carbonate_solution")
        .liquid()
        .color(0x636389)
    event.create("sodium_chromate_solution")
        .liquid()
        .color(0xbbb310)
    event.create("sodium_dichromate_solution")
        .liquid()
        .color(0xb55a10)
    event.create("chromium_oxide")
        .dust()
        .color(0x3dc34d).iconSet(GTMaterialIconSet.DULL)
        .components("2x chromium", "3x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("bitumen")
        .liquid()
        .color(0x51524a)
    event.create("petroleum_coke")
        .gem()
        .liquid()
        .color(0x545252)
        .iconSet(GTMaterialIconSet.LIGNITE)
        .burnTime(3200)
    event.create("dried_salt")
        .dust()
        .color(0x919182)
    event.create("emulsified_bitumen")
        .liquid()
        .color(0x848572)
    event.create("emulsified_bitumen_slurry")
        .liquid()
        .color(0x5b5c4c)
    event.create("simple_emulgator")
        .liquid()
        .color(0xd9de7c)
    event.create("simple_demulsifier")
        .liquid()
        .color(0xa2a659)
    event.create("emulgator")
        .liquid()
        .color(0xdce34f)
    event.create("butyl_acetate")
        .liquid()
        .color(0xffde49)
    event.create("pure_bitumen")
        .liquid()
        .color(0x696969)
    event.create("penicillin")
        .dust()
        .color(0x56bab5)
    event.create("oil_refined_residues")
        .dust()
        .color(0x828277)
    event.create("rich_soil")
        .dust()
        .color(0x613a0d)
        .iconSet(GTMaterialIconSet.DULL)
    event.create("ethanol_mixture")
        .liquid()
        .color(0xde671e)
    event.create("raw_bio_diesel")
        .liquid()
        .color(0xe8a548)
    event.create("rich_soul_soil")
        .dust()
        .color(0x426362)
        .iconSet(GTMaterialIconSet.DULL)
    event.create("aether_air")
        .gas()
        .color(0x8fddf2)
    event.create("liquid_aether_air")
        .liquid(new $FluidBuilder()
            .temperature(30))
        .color(0x7cb9c9)
    event.create("alfheim_air")
        .gas()
        .color(0xd798eb)
    //event.create("liquid_alfheim_air")
    //    .liquid(new $FluidBuilder()
    //        .temperature(74))
    //    .color(0xb981c9)
    event.create("twilightforest_air")
        .gas()
        .color(0xaded9c)
    event.create("liquid_twilightforest_air")
        .liquid(new $FluidBuilder()
            .temperature(112))
        .color(0x8dc27f)
    event.create("venus_air")
        .liquid(new $FluidBuilder()
            .temperature(25))
        .color(0xede07d)
    event.create("liquid_venus_air")
        .liquid()
        .color(0xdbcf73)
    event.create("slag")
        .liquid()
        .ingot()
        .color(0x9e570a)
    event.create("calcium_sulfide")
        .dust()
        .components("calcium", "sulfur")
        .color(0xffffdc)
    event.create("asurine")
        .dust()
        .color(0x50a0de)
    event.create("crimsite")
        .dust()
        .color(0xbf4848)
    event.create("ochrum")
        .dust()
        .color(0xc9af03)
    event.create("veridium")
        .dust()
        .color(0x43b567)
    event.create("asurine_slurry")
        .liquid()
        .color(0x50a0de)
    event.create("crimsite_slurry")
        .liquid()
        .color(0xbf4848)
    event.create("ochrum_slurry")
        .liquid()
        .color(0xc9af03)
    event.create("veridium_slurry")
        .liquid()
        .color(0x43b567)
    event.create("dirt")
        .dust()
        .color(0x9e7d0e)
    event.create("rhizobium")
        .dust()
        .color(0x5e3a03)
    event.create("azotase")
        .dust()
        .color(0xaade4b)
    event.create("rhizobium_extract")
        .liquid()
        .color(0x5e3a03)
    event.create("carbonate_buffer")
        .liquid()
        .color(0xfffcd6)
    event.create("phosphate_buffer")
        .liquid()
        .color(0xffdddd)
    event.create("sodium_dihydrogen_phosphate")
        .dust()
        .color(0xe6ff67)
        .components('sodium', '2x hydrogen', 'phosphate')
    event.create("dibasic_sodium_phosphate")
        .dust()
        .color(0xd2eb54)
        .components('2x sodium', 'hydrogen', 'phosphate')
    event.create("staballoy")
        .ingot()
        .liquid()
        .color(0x444B42)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
        .components('9x uranium', 'titanium')
        .blastTemp(3450, "mid", 7680, 300)
    event.create("magneto_resonatic")
        .gem()
        .color(0xFF97FF)
        .iconSet(GTMaterialIconSet.MAGNETIC)
        .components('zanite', 'ambrosium', 'skyjade', 'cubic_zirconia', 'magnetic_steel')
    event.create("quartz_glass")
        .dust()
        .components("glass", "certus_quartz")
        .color(0xd1f1fa)
    event.create('oxydianiline_sludge')
        .liquid()
        .color(0x68d6cb)
    event.create('oxydianiline')
        .liquid()
        .color(0x87f2e8)
    event.create('pyrometillic_dianhydride')
        .liquid()
        .color(0xe89c9c)
    event.create('kapton_k')
        .ingot()
        .liquid()
        .color(0x97f5a5)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create('kapton_e')
        .ingot()
        .liquid()
        .color(0xf0f597)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create('cobalt_bromide')
        .liquid()
        .color(0x9983e8)
        .components('cobalt', 'bromine')
    event.create('manganese_bromide')
        .liquid()
        .color(0xe883e1)
        .components('manganese', 'bromine')
    event.create('manganese_acetate')
        .liquid()
        .color(0xcded99)
        //.components('manganese','acetate_acid')
    event.create('co_mn_br_catalyst')
        .liquid()
        .color(0xdbe875)
    event.create('bis_trichloromethyl_benzene')
        .liquid()
        .color(0x75bae8)
    event.create('terephthalic_acid')
        .liquid()
        .color(0x75e8a3)
    event.create('terephthaloyl_chloride')
        .liquid()
        .color(0x90e0c7)
    event.create('nitroaniline')
        .liquid()
        .color(0xe090a8)
    event.create('para_phenylenediamine')
        .liquid()
        .color(0x4bb34d)
    event.create('para_aramid')
        .ingot()
        .liquid()
        .color(0x30cf7a)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create('fiber_glass')
        .ingot()
        .liquid()
        .color(0xe0fffc)
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("tantalum_alkaline_mixture")
        .liquid()
        .color(0x46A3FF)
    event.create("tantalite_oxide")
        .dust()
        .color(0x46A3FF)
        .components("2x tantalum", "5x oxygen")
    event.create("tantalite_fluorine")
        .liquid()
        .color(0x46A3AA)
    event.create("potassium_fluoride")
        .dust()
        .color(0xFF6666)
        .components("1x potassium", "1x fluorine")
    event.create("niobium_oxide")
        .dust()
        .color(0xB2A9A9)
        .components("2x niobium", "5x oxygen")
    event.create("niobium_tantalite")
        .liquid()
        .color(0xCCFFFF)
    event.create("ammonium_fluoride")
        .liquid()
        .color(0xFFCCCC)
    event.create("dibismuthhydroborat")
        .dust()
        .color(0x0ed138)
        .components('boron', 'hydrogen', '2x bismuth')
    event.create("bismuth_tellurite")
        .dust()
        .color(0x95eb88)
        .components('2x bismuth', '3x tellurium')
    event.create("circuit_compound")
        .dust()
        .color(0x4a4a4a)
        .components('3x dibismuthhydroborat', '2x bismuth_tellurite', 'indium_gallium_phosphide')
    event.create("thermoduric_bacteria")
        .dust()
        .color(0xf77272)
    event.create("taq_enzyme")
        .dust()
        .color(0xfcbebe)
    event.create("thermoduric_bacteria_extract")
        .liquid()
        .color(0xd98484)
    event.create("escherichia_coli_extract")
        .liquid()
        .color(0x08632e)
    event.create("cellulase")
        .dust()
        .color(0x9fd4b5)
    event.create("rare_earth_fe_one")
        .dust()
        .color(0x6d6531)
    event.create("rare_earth_fe_two")
        .dust()
        .color(0x6d5231)
    event.create("rare_earth_intensive_research")
        .dust()
        .color(0x8a5d28)
    event.create("rare_earth_mixture")
        .dust()
        .color(0xcf8226)
    event.create("rare_earth_mixture_oh")
        .liquid()
        .color(0xdbb88f)
    event.create("rare_earth_crystals")
        .dust()
        .color(0x5f7632)
    event.create("rare_earth_chloride_boil")
        .liquid()
        .color(0x595b24)
    event.create("rare_earth_high_affinity")
        .liquid()
        .color(0x535612)
    event.create("rare_earth_low_affinty")
        .liquid()
        .color(0x34351d)
    event.create("rare_earth_high")
        .dust()
        .color(0x70723b)
    event.create("rare_earth_low")
        .dust()
        .color(0x94982a)
    event.create("rare_earth_middle")
        .dust()
        .color(0xbcbe79)
    event.create("rare_earth_high_fluoride")
        .liquid()
        .color(0xcfd534)
    event.create("rare_earth_middle_fluoride")
        .liquid()
        .color(0x919447)
    event.create("rare_earth_low_fluoride")
        .liquid()
        .color(0x9ea40a)
    event.create("rare_earth_low_fluoride_steam")
        .liquid()
        .color(0xefafcd)
    event.create("rare_earth_middle_fluoride_steam")
        .liquid()
        .color(0xe0e65c)
    event.create("rare_earth_high_fluoride_steam")
        .liquid()
        .color(0xe1e3a0)
    event.create("lanthanum_cerium_praseodymium_neodymium_oxygen_mixture")
        .dust()
        .color(0xeaebd1)
    event.create("europium_gadolinium_terbium_dysprosium_oxygen_mixture")
        .dust()
        .color(0xe7ea8f)
    event.create("yttrium_holmium_erbium_thulium_ytterbium_oxygen_lutetium_mixture")
        .dust()
        .color(0x9aa108)
    event.create("lan_cer_pra_neo_chloride")
        .dust()
        .color(0x5ea108)
    event.create("eur_gado_ter_dyspr_chloride")
        .dust()
        .color(0xb7f665)
    event.create("ytt_hol_erb_thu_ytt_chloride")
        .dust()
        .color(0x3f5d18)
    event.create('snow_steel')
        .ingot()
        .liquid()
        .color(0x00ffff)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create("refining_titanium_tetrachloride")
        .liquid()
        .color(0x631cab)
    event.create("aluminium_chloride")
        .dust()
        .color(0x045681)
    event.create("titanium_tetrachloride_v")
        .liquid()
        .color(0x024789)
    event.create("tungsten_trioxide")
        .dust()
        .color(0x474444)
    event.create("graphite_steam")
        .liquid()
        .color(0x000000)
    event.create("graphite_ir_plate")
        .ingot()
        .color(0x000000)
        .flags(GTMaterialFlags.GENERATE_PLATE)
    event.create("superfuelmk1")
        .liquid()
        .color(0xA52A2A)
    event.create("superfuelmk2")
        .liquid()
        .color(0xFF69B4)
    event.create("superfuelmk3")
        .liquid()
        .color(0x8A2BE2)
    event.create("nq_fuelmk1")
        .liquid()
        .color(0x54FF9F)
    event.create("nq_fuelmk2")
        .liquid()
        .color(0x9AFF9A)
    event.create("nq_fuelmk3")
        .liquid()
        .color(0x00FF7F)
    event.create("taranliquid")
        .gas()
        .color(0x8B7E66)
    event.create("bedrock_fog")
        .gas()
        .color(0xDCDCDC)
    event.create("bedrock_smoke")
        .gas()
        .color(0xBEBEBE)
    event.create("bedrock_gas") //
        .gas()
        .color(0xD3D3D3)
    event.create("bedrock_fog_re")
        .gas()
        .color(0xDCDC33)
    event.create("bedrock_fog_re_l")
        .gas()
        .color(0xDCDC22)
    event.create("bedrock_fog_re_m")
        .gas()
        .color(0xDCDC11)
    event.create("bedrock_fog_re_h")
        .gas()
        .color(0xDCDC00)
    event.create("bedrock_smoke_re_l")
        .gas()
        .color(0xDC1111)
    event.create("bedrock_smoke_re_m")
        .gas()
        .color(0xDC2222)
    event.create("bedrock_smoke_re_h")
        .gas()
        .color(0xDC3333)
    event.create("bedrock_smoke_re")
        .gas()
        .color(0xDC4444)
    event.create("bedrock_gas_re_l")
        .gas()
        .color(0xDC1111)
    event.create("bedrock_gas_re_m")
        .gas()
        .color(0xDC2222)
    event.create("bedrock_gas_re_h")
        .gas()
        .color(0xDC3333)
    event.create("bedrock_gas_re")
        .gas()
        .color(0xDC4444)
    event.create("taranliquidfuel_l")
        .liquid()
        .color(0x8B1111)
    event.create("taranliquidfuel_m")
        .liquid()
        .color(0x8B2222)
    event.create("taranliquidfuel_h")
        .liquid()
        .color(0x8B3333)
    //event.create("adamantiteliquid")
    //    .liquid()
    //    .color(0x125555)
    event.create("tungstencu_diamond_plating")
        .gem()
        .color(0x223A40)
        .flags(GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_PLATE)
    event.create("stearic_acid")
        .liquid()
        .color(0xeef52b)
    event.create("palmitic_acid")
        .liquid()
        .color(0xf4ff7e)
    event.create("oleic_acid")
        .liquid()
        .color(0xc6f24e)
    event.create("spectrin")
        .dust()
        .color(0xcf5252)
    event.create("hemoglobin")
        .dust()
        .color(0xab2121)
    event.create("bedrock_dust_solution")
        .liquid()
        .color(0x66A499)
    event.create("bedrock_dust")
        .ingot()
        .dust()
        .liquid()
        .blastTemp(10200)
        .color(0x7C7878)
        .cableProperties(GTValues.V[GTValues.ZPM], 16, 1)
        .flags(GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FOIL)
    event.create("bedrock_soot_solution")
        .liquid()
        .color(0x164039)
    event.create("taranmix")
        .dust()
        .color(0x463030)
    event.create("f_bedrock_smoke_re")
        .liquid()
        .color(0x24a156)
    event.create("dr_bedrock_gas_re")
        .liquid()
        .color(0x123aaa)
    event.create("ax_jiyanqi")
        .gas()
        .color(0x325ade)
    event.create("radioactive_metals_mix")
        .dust()
        .color(0x66adad)
    event.create("boundless")
        .ingot()
        .dust()
        .liquid()
        .blastTemp(100000)
        .rotorStats(600, 550, 10, 2000000)
        .radioactiveHazard(3)
        .cableProperties(GTValues.V[GTValues.UXV], 16, 1)
        .color(0xFFFFFF).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FOIL)
    event.create("bedrock_neutronium")
        .ingot()
        .dust()
        .liquid()
        .blastTemp(10200)
        .radioactiveHazard(20)
        .cableProperties(GTValues.V[GTValues.UV], 16, 1)
        .color(0xFFFFFA).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FOIL)
    event.create("enrich_radioactive_waste")
        .dust()
        .color(0xFF5733)
    event.create("neutron_irradiation_of_radioactive_waste")
        .liquid()
        .color(0x33FF57)
    event.create("radioactive_ion_solution")
        .liquid()
        .color(0x5733FF)
    event.create("radioactive_metal_ingot")
        .ingot()
        .color(0xFFD700)
    event.create("radiation_dust")
        .dust()
        .color(0xFF33FF)
    event.create("low_level_radioactive_dust")
        .gas()
        .color(0xFFAA33)
    event.create("high_level_radioactive_dust")
        .gas()
        .color(0xAA33FF)
    event.create("concentrated_low_level_radioactive_dust")
        .gas()
        .color(0x33AAFF)
    event.create("concentrated_high_level_radioactive_dust")
        .gas()
        .color(0xFFFF33)
    event.create("nuclear_waste_water")
        .liquid()
        .color(0x33FF33)
    event.create("aether")
        .dust()
        .ingot(5)
        .liquid()
        .plasma()
        .radioactiveHazard(3)
        .blastTemp(12600)
        .color(0x00FF80)
        .secondaryColor(0x2DCB7C)
        .iconSet(GTMaterialIconSet.METALLIC)
        .cableProperties(GTValues.V[GTValues.UEV], 16, 1)
        .flags(GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FOIL)
    event.create("taranium_dirty_helium3")
        .gas()
        .color(0xFF5733)
    event.create("taranium_enriched_liquid_helium3")
        .liquid()
        .color(0x33FF57)
    event.create("taranium_half_life_liquid_helium3")
        .liquid()
        .color(0x3357FF)
    event.create("taranium_depleted_liquid_helium3")
        .liquid()
        .color(0xFF3333)
    event.create("taranium_enriched_dirty_helium_plasma")
        .plasma()
        .color(0x33FFFF)
    event.create("taranium_enriched_helium4_plasma")
        .plasma()
        .color(0x5733FF)
    event.create("taranium_depleted_helium_plasma")
        .plasma()
        .color(0xFF33FF)
    event.create("taranium_enriched_liquid_helium4")
        .liquid()
        .color(0x33FF33)
    event.create("taranium_depleted_liquid_helium")
        .liquid()
        .color(0x33FF33)
    event.create("adamant_mud")
        .dust()
        .color(0xFFCC33)
    event.create("p507_extractant")
        .liquid()
        .color(0x33FF57)
    event.create("di_2_ethylhexyl_phosphite")
        .liquid()
        .color(0x33AADD)
    event.create("1_chloro_2_ethylhexane")
        .liquid()
        .color(0x33FF57)
    event.create("phosphonate")
        .liquid()
        .color(0x3333FF)
    event.create("chlorocyclohexane")
        .liquid()
        .color(0x33AADD)
    event.create("beta_aminophosphonate")
        .liquid()
        .color(0xFFCC33)
    event.create("dimethyl_phosphite")
        .liquid()
        .color(0x33AADD)
    event.create("2_ethylhexanol")
        .liquid()
        .color(0x33FF57)
    event.create("copper_chromium_catalyst")
        .dust()
        .color(0x33FF57)
    event.create("phosphorous_acid")
        .liquid()
        .color(0xFF5733)
    event.create("refined_gold_aq")
        .liquid()
        .color(0x325547)
    event.create("refined_gold_aq_low")
        .liquid()
        .color(0x16477A)
    event.create("samarium_dysprosium_terbium_permanent_magnet_alloy")
        .ingot()
        .blastTemp(10200)
        .iconSet(GTMaterialIconSet.METALLIC)
        .cableProperties(GTValues.V[GTValues.UV], 16, 1)
        .components('samarium', 'dysprosium', 'terbium')
        .color(0x124435)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create("samarium_dysprosium_terbium_permanent_magnet_alloy_magnetic")
        .ingot()
        .blastTemp(10200)
        .iconSet(GTMaterialIconSet.MAGNETIC)
        .cableProperties(GTValues.V[GTValues.UV], 16, 1)
        .components('samarium', 'dysprosium', 'terbium')
        .color(0x148072)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)

    event.create("cement")
        .liquid()
        .color(0xD2B48C);
    event.create('fefarite')
        .ore()
        .gem()
        .dust()
        .color(0x046ed7)
        .iconSet(GTMaterialIconSet.LIGNITE)
    event.create('fefarite_intermediate_body')
        .liquid()
        .color(0x28358A)
    event.create('nether_essence_crystal_fluid')
        .liquid()
        .color(0x046ed7)
    event.create('kevlar_stone_growth_liquid')
        .liquid()
        .color(0xAAAAAA)
    event.create("mana_fused_mixed")
        .dust()
        .element(GTElements.get('mana_mixed'))
        .color(0x4FC1FF)
    event.create("mana_fused_lp_mixed")
        .dust()
        .element(GTElements.get('mana_lp_mixed'))
        .color(0x0000A0)
    event.create("mana_fused_demon_mixed")
        .dust()
        .element(GTElements.get('mana_demon_mixed'))
        .color(0x0000A0)
    event.create("shock_resistant_alloy")
        .dust()
        .ingot()
        .color(0xFFD700)
        .liquid()
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
    event.create("mana_unstable_plus")
        .dust()
        .color(0xe6ea0)
    event.create("mana_infused_plus")
        .dust()
        .color(0xe6ea0)
    event.create("mana_zenith_plus")
        .dust()
        .color(0x201263)
    event.create("mana_stable_plus")
        .dust()
        .color(0x8aa8c)
    event.create('unknown_super_mana')
        .dust()
        .color(0x8aa8c)
    event.create('twist_mana')
        .dust()
        .color(0X0066FF)
    event.create('twist_power_mana')
        .dust()
        .ingot()
        .liquid()
        .color(0X0000FF)
    event.create("mana_remain")
        .dust()
        .color(0xe6ea0)
    event.create('cracking_silica_rock_based_fuel')
        .liquid()
        .color(0x5abcc)
    event.create('cracking_enriched_silica_rock_based_fuel')
        .liquid()
        .color(0x6bcca)
    event.create('cracking_super_energy_silica_rock_based_fuel')
        .liquid()
        .color(0x7bacb)
    event.create('charged_silica_rock_based_fluid_fuel_mk_i')
        .liquid()
        .color(0x55555)
    event.create('charged_silica_rock_based_fluid_fuel_mk_ii')
        .liquid()
        .color(0x55555)
    event.create('charged_silica_rock_based_fluid_fuel_mk_iii')
        .liquid()
        .color(0x55555)
    event.create("high_energy_fuel")
        .liquid()
        .color(0x351aa)
    event.create("acid_garbage")
        .liquid()
        .color(0x44444)
    event.create("eglin_steel_ingot")
        .dust()
        .ingot()
        .color(0x23312)
        .components('5x invar', '4x iron', 'kanthal')
    event.create('sodium22')
        .dust()
        .color((0x4682B4))
        .radioactiveHazard(3)
    event.create('hiddenechofungus')
        .color((0x306080))
        .dust()
    event.create('hiddenechofungussolution')
        .color((0x306080))
    event.create('soda_dust')
        .dust()
        .ingot()
        .flags(GTMaterialFlags.GENERATE_PLATE)
        .color(0xFFFFFF)
    event.create('clgs_buffer')
        .flags(GTMaterialFlags.GENERATE_PLATE)
        .dust()
        .color(0xFFFFFF)
    event.create('cds_buffer')
        .flags(GTMaterialFlags.GENERATE_PLATE)
        .dust()
        .color(0xFFD700)
    event.create('magnetron_sputtering_target_material')
        .flags(GTMaterialFlags.GENERATE_PLATE)
        .dust()
        .color(0xFFFFBA)
    event.create('sunnarium_extract')
        .dust()
        .liquid()
        .color(0XFFFF01)
    event.create('radiation_sunnarium_extract')
        .color(0XFFFF01)
        .liquid()
        .plasma()
    event.create('cadmium_sulfide')
        .ingot()
        .blastTemp(3600)
        .dust()
        .iconSet(GTMaterialIconSet.METALLIC)
        .components('cadmium', 'sulfur')
        .color(0XFFFACD)
        .flags(GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create('heat_resistant_ferrochrome_alloy_ds')
        .ingot()
        .dust()
        .liquid()
        .color(0X8A9B7A)
        .components('23x iron', '9x cobalt', '9x chromium', '9x nickel')
        .blastTemp(5400 - 1800, 'low', GTValues.VA[GTValues.HV], 500)
        .flags(GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create('heat_resistant_ferrochrome_alloy_020')
        .ingot()
        .dust()
        .liquid()
        .components('10x iron', '1x copper', '5x chromium', '9x nickel')
        .blastTemp(1800 * 3, 'mid', GTValues.VA[GTValues.EV], 800)
        .color(0X4E7D6D)
        .flags(GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create('optical_heat_resistant_ferrochrome_alloy_080')
        .ingot()
        .dust()
        .liquid()
        .components('10x iron', '5x chromium', '9x nickel', '4x titanium', '9x sunnarium')
        .blastTemp(1800 * 4, 'mid', GTValues.VA[GTValues.LuV], 1000)
        .color(0X4E7D9D)
        .flags(GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create('naquadah_heat_resistant_ferrochrome_alloy_792')
        .ingot()
        .dust()
        .liquid()
        .components('70x iron', '20x chromium', '5x nickel', '5x manganese', '10x naquadah')
        .blastTemp(1800 * 4, 'mid', GTValues.VA[GTValues.LuV], 3000)
        .color(0X2A2A1A)
        .flags(GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create('nami_c')
        .dust()
        .liquid()
        .color(0X0000)
    event.create('radiation_sight_alloy_x')
        .ingot()
        .dust()
        .liquid()
        .components('9x iridium', '4x dysprosium', '6x staballoy', '8x gtceu:uranium_rhodium_dinaquadide', '7x gtceu:neptunium', '2x gtceu:mendelevium')
        .blastTemp(1800 * 5, 'high', GTValues.VA[GTValues.ZPM], 1000)
        .color(0X2D3A2A)
        .flags(GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create('quantum_alloy')
        .ingot()
        .dust()
        .liquid()
        .components('3x ultimet', '3x lapotron', '3x americium', '7x silicon_carbide', '2x palladium', '1x aether', '4x germanium', '2x neutronium')
        .blastTemp(1800 * 6, 'high', GTValues.VA[GTValues.UV], 33333)
        .color(0X808080)
        .flags(GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create('radiation_sight_alloy_inf')
        .ingot()
        .dust()
        .liquid()
        .components('3x quantum_alloy', '2x radiation_sight_alloy_x', '7x naquadria', '2x hidden_alloy', '3x boundless', '3x aeternium', "2x adamantite")
        .blastTemp(1800 * 7, 'high', GTValues.VA[GTValues.UHV], 2500)
        .color(0X2D3A2A)
        .flags(GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_LONG_ROD)
    event.create('living_metal_pre')
        .liquid()
        .color(0XC0C0C0)
    event.create("alkaline_complex_ore_slurry")
        .liquid()
        .color(0x40E0D0)
    event.create("alkaline_slag")
        .dust()
        .color(0x505050)
    event.create("strontium_chloride")
        .dust()
        .color(0xFFC0CB)
    event.create("oracle")
        .dust()
        .ingot()
        .liquid()
        .plasma()
        .color(0xFFC0CB)
    event.create("advanced_mana_steel")
        .dust()
        .ingot()
        .liquid()
        .plasma()
        .color(0xE6E6FA)
    event.create('steel_precursor') 
        .dust()                   
        .color(0x4A4A4A)           
    event.create('high_temp_wrought_precursor')
        .dust()
        .ingot()
        .iconSet(GTMaterialIconSet.METALLIC)
        .color(0x8C7853)
        .blastTemp(7200 , 'high', GTValues.VA[GTValues.UHV], 2500)
    event.create("perrhenic_acid")
        .liquid()
        .color(0x654aaa)

})

StartupEvents.postInit(event => {
    TagPrefix.ingot.setIgnored(GTMaterials.get("ignitium"), "cataclysm:ignitium_ingot")
    TagPrefix.block.setIgnored(GTMaterials.get("ignitium"), "cataclysm:ignitium_block")
    function setFormula(material, formula) {
        const mat = GTMaterials.get(material)
        if (mat === null)
            return
        mat.setFormula(formula)
    }
    setFormula("high_temp_wrought_precursor", "Fe")
    setFormula("steel_precursor", "Fe8C3")
    setFormula("sodium_hexafluoroaluminate", "Na3AlF6")
    setFormula("potassium_metabi_sulfite", "K2S2O2")
    setFormula("alumina", "Al2O3")
    setFormula("sodium_fluoride", "NaF")
    setFormula("aluminium_trifluoride", "AlF3")
    setFormula("sodium_hydroxide_bauxite", "(TiO2)Al2H10O29-Na(OH)2")
    setFormula("gold_leach", "(Au)")
    setFormula("copper_leach", "(Cu)")
    setFormula("chloroauric_acid", "AuCl3")
    setFormula("impure_aluminium_hydroxide_solution", "(Al(OH)3)")
    setFormula("pure_aluminium_hydroxide_solution", "Al(OH)3")
    setFormula("red_mud", "Ti?Fe?")
    setFormula("neutralised_red_mud", "Ti?Fe?")
    setFormula("red_slurry", "Ti?")
    setFormula("titanyl_sulfate", "TiO(SO4)")
    setFormula("ferric_ree_chloride", "(FeCl3)")
    setFormula("aluminium_hydroxide", "Al(OH)3")
    setFormula("sodium_hydroxide_solution", "NaOH")
    setFormula("cellulose", "(C6H10O5)n")
    setFormula("lignin", "(CH2ON?S?)n")
    setFormula("combustible_ice", "(CH4)(H2O)")
    setFormula("ammonium_sulfate", "(NH4)2SO4")
    setFormula("niobium_tantalite", "Ta-Nb")
    setFormula("ammonium_fluoride", "NH4F")
    setFormula("rare_earth_fe_one", "Fe4?")
    setFormula("rare_earth_fe_two", "Fe2?")
    setFormula("rare_earth_intensive_research", "???")
    setFormula("rare_earth_crystals", "??")
    setFormula("rare_earth_high", "GdTbDyHoErTmYbLuY?")
    setFormula("rare_earth_low", "LaCePrNd?")
    setFormula("rare_earth_middle", "PmEuSm?")
    setFormula("snow_steel", "SNOWCITY")
    setFormula("refining_titanium_tetrachloride", "Re-TiCl4")
    setFormula("aluminium_chloride", "AlCl3")
    setFormula("titanium_tetrachloride_v", "V-TiCl4")
    setFormula("tungsten_trioxide", "WO3")
    setFormula("boundless", "∞-")
    setFormula("xuanlvjin", "Xg")
    setFormula("phosphorous_acid", "H3PO3")
    setFormula("refined_gold_aq", "Ad?*Nq*?")
    setFormula('fefarite', "KeF")
    setFormula('unknown_super_mana', 'Ma+++++???????')
    setFormula('twist_mana', "(.*?)Ma(.*?)")
    setFormula('twist_power_mana', "M?????A")
    setFormula('shock_resistant_alloy', "🚁HeLiCoPtEr🚁")
    setFormula("bedrock_neutronium", "NtBR*")
    setFormula("clgs", "Cu(In, Ga)Se2")
    setFormula('aeternium', "AT")
    setFormula('lapotron', "⬟")
    setFormula("living_metal_pre", "Sn?Pb?&LMα")
    setFormula("strontium_chloride", "SrCl2")
    setFormula("oracle", "THANKS_FOR_YOUR_PLAYING")
    setFormula("advanced_mana_steel", "MAGIC+")
    setFormula("perrhenic_acid", "HReO4")
})