GTCEuStartupEvents.registry("gtceu:element", event => {
    event.create("adamantine", 119, 134, -1, null, "Ad", false)
    event.create("starmetal", 120, 138, -1, null, "St", false)
    event.create("taranium", 121, 140, -1, null, "Tn", false)
    event.create("my_infinity", 114514, 1919810, -1, null, "∞", false)
    //event.create("helium_3", 2, 1, -1, null, "He-3", true)
    event.create("super_mana", 169, 169, -1, null, "Ma", false)
})
GTCEuStartupEvents.registry("gtceu:material", event => {
    function radioactive(multiplier) {
        return new HazardProperty(HazardProperty.HazardTrigger.ANY,
            GTMedicalConditions.CARCINOGEN, multiplier, true)
    }
    GTMaterials.Iodine.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Osmiridium.addFlags(GTMaterialFlags.GENERATE_FRAME)
    GTMaterials.TreatedWood.addFlags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_RING)
    GTMaterials.Zinc.setProperty(PropertyKey.ORE, new $OreProperty())
    GTMaterials.Brass.addFlags(GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_GEAR)
    GTMaterials.Magnalium.addFlags(GTMaterialFlags.GENERATE_GEAR)
    GTMaterials.Silver.addFlags(GTMaterialFlags.GENERATE_FRAME)
    GTMaterials.StainlessSteel.addFlags(GTMaterialFlags.GENERATE_DENSE)
    GTMaterials.VanadiumSteel.addFlags(GTMaterialFlags.GENERATE_DENSE)
    GTMaterials.Stellite100.addFlags(GTMaterialFlags.GENERATE_GEAR)
    GTMaterials.NaquadahAlloy.addFlags(GTMaterialFlags.GENERATE_FINE_WIRE)
    GTMaterials.RutheniumTriniumAmericiumNeutronate.addFlags(GTMaterialFlags.GENERATE_FINE_WIRE)
    GTMaterials.TitaniumTungstenCarbide.addFlags(GTMaterialFlags.GENERATE_GEAR)
    GTMaterials.Trinium.addFlags(GTMaterialFlags.GENERATE_FRAME)
    GTMaterials.Europium.addFlags(GTMaterialFlags.GENERATE_SPRING_SMALL)
    GTMaterials.Germanium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Germanium.addFlags(GTMaterialFlags.GENERATE_PLATE)
    GTMaterials.Sodium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Seaborgium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Seaborgium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Seaborgium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Seaborgium.addFlags(GTMaterialFlags.GENERATE_ROTOR, GTMaterialFlags.GENERATE_FRAME)
    GTMaterials.Dubnium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Dubnium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Dubnium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Dubnium.addFlags(GTMaterialFlags.GENERATE_FINE_WIRE)
    GTMaterials.Rhenium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Rhenium.addFlags(GTMaterialFlags.GENERATE_PLATE)
    GTMaterials.Calcium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Gadolinium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Terbium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Dysprosium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Dysprosium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Holmium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Erbium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Thulium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Thulium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Ytterbium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Scandium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Scandium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Naquadria.addFlags(GTMaterialFlags.GENERATE_FRAME)
    GTMaterials.NaquadahEnriched.addFlags(GTMaterialFlags.GENERATE_FRAME)
    GTMaterials.NickelZincFerrite.addFlags(GTMaterialFlags.GENERATE_FOIL)
    GTMaterials.Promethium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Polonium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Polonium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Polonium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Hafnium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Hafnium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.EnderEye.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.EnderPearl.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Protactinium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Protactinium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Protactinium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Neptunium.addFlags(GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_SMALL_GEAR)
    GTMaterials.Neptunium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Neptunium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Neptunium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Curium.addFlags(GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_SMALL_GEAR)
    GTMaterials.Curium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Curium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Curium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Berkelium.addFlags(GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_SMALL_GEAR)
    GTMaterials.Berkelium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Berkelium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Berkelium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Einsteinium.addFlags(GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_SMALL_GEAR)
    GTMaterials.Einsteinium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Einsteinium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Einsteinium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Californium.addFlags(GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_SMALL_GEAR)
    GTMaterials.Californium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Californium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Fermium.addFlags(GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_SMALL_GEAR)
    GTMaterials.Fermium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Fermium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Fermium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Mendelevium.addFlags(GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_SMALL_GEAR)
    GTMaterials.Mendelevium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Mendelevium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Mendelevium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Oganesson.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Oganesson.setProperty(PropertyKey.HAZARD, radioactive(1.5))
    GTMaterials.Oganesson.addFlags(GTMaterialFlags.GENERATE_PLATE)
    GTMaterials.Flerovium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Flerovium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Flerovium.setProperty(PropertyKey.HAZARD, radioactive(1.5))
    GTMaterials.Nobelium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Nobelium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Lawrencium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Lawrencium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Nobelium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Lawrencium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Hassium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Hassium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Hassium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Hassium.addFlags(GTMaterialFlags.GENERATE_PLATE)
    GTMaterials.Rubidium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Rubidium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Technetium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Technetium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Technetium.addFlags(GTMaterialFlags.GENERATE_PLATE)
    GTMaterials.Francium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Francium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Strontium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Zirconium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Zirconium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Radium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Radium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Radium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Tellurium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Actinium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Actinium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Actinium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Rutherfordium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Rutherfordium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Selenium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Astatine.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Astatine.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Astatine.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Bohrium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Bohrium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Bohrium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Thallium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Thallium.setProperty(PropertyKey.HAZARD, new HazardProperty(HazardProperty.HazardTrigger.INHALATION, GTMedicalConditions.POISON, 1, false))
    GTMaterials.Meitnerium.setProperty(PropertyKey.DUST, new $DustProperty())
    GTMaterials.Meitnerium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Meitnerium.setProperty(PropertyKey.HAZARD, radioactive(1))
    GTMaterials.Roentgenium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Copernicium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Nihonium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Moscovium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Livermorium.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Tennessine.setProperty(PropertyKey.INGOT, new $IngotProperty())
    GTMaterials.Roentgenium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Copernicium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Nihonium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Moscovium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Livermorium.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Tennessine.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.Roentgenium.setProperty(PropertyKey.HAZARD, radioactive(1.5))
    GTMaterials.Copernicium.setProperty(PropertyKey.HAZARD, radioactive(1.5))
    GTMaterials.Nihonium.setProperty(PropertyKey.HAZARD, radioactive(1.5))
    GTMaterials.Moscovium.setProperty(PropertyKey.HAZARD, radioactive(1.5))
    GTMaterials.Livermorium.setProperty(PropertyKey.HAZARD, radioactive(1.5))
    GTMaterials.Tennessine.setProperty(PropertyKey.HAZARD, radioactive(1.5))
    GTMaterials.ReinforcedEpoxyResin.addFlags(GTMaterialFlags.GENERATE_ROD)
    GTMaterials.Phosphorus.setProperty(PropertyKey.FLUID, new $FluidProperty(GTFluidStorageKeys.LIQUID, new $FluidBuilder()))
    GTMaterials.get("andesite_alloy").addFlags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    GTMaterials.get("andesite_alloy").setMaterialARGB(0xA7AD9F)
    GTMaterials.get("andesite_alloy").setMaterialIconSet(GTMaterialIconSet.DULL)

    GTMaterials.get("mana_steel").addFlags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
    GTMaterials.get("mana_steel").setMaterialARGB(0x438FFE)
    GTMaterials.get("mana_steel").setMaterialSecondaryARGB(0x3962D7)
    GTMaterials.get("mana_steel").setMaterialIconSet(GTMaterialIconSet.METALLIC)
    GTMaterials.get("mana_steel").setProperty(PropertyKey.WIRE, new $WireProperties(GTValues.V[GTValues.LV], 6, 1))
    GTMaterials.get("terra_steel").addFlags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
    GTMaterials.get("terra_steel").setMaterialARGB(0x63D12F)
    GTMaterials.get("terra_steel").setMaterialSecondaryARGB(0x2AB73A)
    GTMaterials.get("terra_steel").setMaterialIconSet(GTMaterialIconSet.METALLIC)
    GTMaterials.get("terra_steel").setProperty(PropertyKey.WIRE, new $WireProperties(GTValues.V[GTValues.HV], 6, 1))
    GTMaterials.get("elementium").addFlags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
    GTMaterials.get("elementium").setMaterialARGB(0xf762a3)
    GTMaterials.get("elementium").setMaterialSecondaryARGB(0xf768d1)
    GTMaterials.get("elementium").setMaterialIconSet(GTMaterialIconSet.METALLIC)
    GTMaterials.get("elementium").setProperty(PropertyKey.WIRE, new $WireProperties(GTValues.V[GTValues.MV], 6, 1))
})

GTCEuStartupEvents.registry("gtceu:material", event => {
    event.create("energetic_alloy")
        .ingot()
        .liquid()
        .components("1x redstone", "1x glowstone", "2x gold")
        .blastTemp(1200, "low", 120, 200)
        .cableProperties(GTValues.V[GTValues.MV], 1, 0, true)
        .color(0xf79b33).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("vibrant_alloy")
        .ingot()
        .liquid()
        .components("1x energetic_alloy", "1x ender_pearl")
        .blastTemp(1600, "low", 480, 200)
        .cableProperties(GTValues.V[GTValues.HV], 1, 0, true)
        .color(0xbbe87c).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("conductive_alloy")
        .ingot()
        .liquid()
        .cableProperties(GTValues.V[GTValues.LV], 1, 0, true)
        .color(0xf5c4bd).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR,GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("dark_steel")
        .ingot()
        .liquid()
        .components("1x steel", "1x obsidian")
        .blastTemp(1400, "low", 480, 200)
        .color(0x858585).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("soularium")
        .ingot()
        .liquid()
        .color(0x6C5A34).iconSet(GTMaterialIconSet.DULL)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("end_steel")
        .ingot()
        .liquid()
        .components("1x dark_steel", "1x endstone", "1x obsidian")
        .blastTemp(2500, "mid", 1920, 200)
        .cableProperties(GTValues.V[GTValues.EV], 1, 0, true)
        .color(0xe8e08b).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("chorusite_alloy")
        .ingot()
        .liquid()
        .color(0xc576ed)
        .blastTemp(3000, "low", 480, 260)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("melodic_alloy")
        .ingot()
        .liquid()
        .components("1x chorusite_alloy", "1x end_steel")
        .blastTemp(3200, "mid", 7680, 280)
        .cableProperties(GTValues.V[GTValues.IV], 1, 0, true)
        .color(0xd271db).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("stellar_alloy")
        .ingot()
        .liquid()
        .components("1x nether_star", "1x melodic_alloy", "1x refined_radiance")
        .blastTemp(5000, "mid", 30720, 260)
        .cableProperties(GTValues.V[GTValues.LuV], 1, 0, true)
        .color(0xe5f7f7).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("copper_alloy")
        .ingot()
        .liquid()
        .color(0xBB8418).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("redstone_alloy")
        .ingot()
        .liquid()
        .color(0xed3b50)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("pulsating_alloy")
        .ingot()
        .liquid()
        .color(0x9AEBAD).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create("precious_alloy")
        .ingot()
        .ore()
        //.components("1x gold")
        .liquid()
        .color(0xA4801F).iconSet(GTMaterialIconSet.METALLIC)
    event.create("gold_alloy")
        .ingot()
        .color(0xA69226).iconSet(GTMaterialIconSet.METALLIC)
    event.create("cryolite")
        .dust()
        .ore()
        .addOreByproducts(GTMaterials.Sodium, GTMaterials.BlueTopaz)
        //.components("3x sodium","1x aluminum","6x fluorine")
        .color(0x8D8686)
    event.create("sodium_hexafluoroaluminate")
        .liquid()
        //.components("3x sodium","1x aluminum","6x fluorine")
        .color(0x75471F)
    event.create("gold_leach")
        .dust()
        .color(0x695D18)
    event.create("copper_leach")
        .dust()
        .color(0x70552D)
    event.create("chloroauric_acid")
        .liquid()
        .color(0xBAB02D)
    event.create("potassium_metabi_sulfite")
        .dust()
        .color(0x8D6939)
    //.components("2x sulfur","2x potassium","2x oxygen")
    event.create("alumina")
        .dust()
        .color(0x09474A)
    //.components("2x aluminum","3x oxygen")
    event.create("sodium_fluoride")
        .dust()
        .color(0x480214)
    //.components("1x sodium","1x fluorine")
    event.create("aluminium_trifluoride")
        .dust()
        .color(0x9B513E)
    //.components("1x aluminum","3x fluorine")
    event.create("sodium_hydroxide_bauxite")
        .liquid()
        .color(0xA46D2C)
    event.create("impure_aluminium_hydroxide_solution")
        .liquid()
        .color(0xC95D3A)
    event.create("pure_aluminium_hydroxide_solution")
        .liquid()
        .color(0x803DC2)
    event.create("red_mud")
        .liquid()
        .color(0xB2370D)
    event.create("neutralised_red_mud")
        .liquid()
        .color(0xAF3C15)
    event.create("red_slurry")
        .liquid()
        .color(0xAC401C)
    event.create("titanyl_sulfate")
        .liquid()
        .color(0xCC3C75)
    event.create("ferric_ree_chloride")
        .liquid()
        .color(0x3B3B2B)
    event.create("aluminium_hydroxide")
        .dust()
        .color(0x5E929D)
    event.create("sodium_hydroxide_solution")
        .liquid()
        .color(0x15286D)
    event.create("rare_earth_chloride_solution")
        .liquid()
        .color(0x393927)
    event.create("alfsteel")
        .ingot()
        .color(0xFD9D31)
        .iconSet(GTMaterialIconSet.METALLIC)
        .cableProperties(GTValues.V[GTValues.EV], 6, 1, false)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
    event.create("mana_fused")
        .dust()
        .ore()
        .color(0x4FC1FF)
    event.create("iodine_enriched_solution")
        .liquid()
        .color(0x804E9B)
    event.create("netherite")
        .ingot()
        .liquid()
        .color(0x595659)
        .secondaryColor(0x4C484C)
        .iconSet(GTMaterialIconSet.DULL)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
    event.create("unknown_mixture")
        .liquid()
        .color(0x979ea9)
    event.create("normal_yeast")
        .dust()
        .color(0xe3d7b7)
    event.create("normal_yeast_seed_liquid")
        .liquid()
        .color(0xe3d7b7)
    event.create("normal_yeast_liquid")
        .liquid()
        .color(0xD6C493)
    event.create("normal_yeast_extract_liquid")
        .liquid()
        .color(0xe3bb4f)
    event.create("crimson_yeast")
        .dust()
        .color(0xe58877)
    event.create("crimson_yeast_seed_liquid")
        .liquid()
        .color(0xe58877)
    event.create("crimson_yeast_liquid")
        .liquid()
        .color(0xe66f5a)
    event.create("crimson_yeast_extract_liquid")
        .liquid()
        .color(0xd85841)
    event.create("warped_yeast")
        .dust()
        .color(0x6abbba)
    event.create("warped_yeast_seed_liquid")
        .liquid()
        .color(0x6abbba)
    event.create("warped_yeast_liquid")
        .liquid()
        .color(0x3a9795)
    event.create("warped_yeast_extract_liquid")
        .liquid()
        .color(0x23807e)
    event.create("end_yeast")
        .dust()
        .color(0x8ef2eb)
    event.create("end_yeast_seed_liquid")
        .liquid()
        .color(0x8ef2eb)
    event.create("end_yeast_liquid")
        .liquid()
        .color(0x63f1e7)
    event.create("end_yeast_extract_liquid")
        .liquid()
        .color(0x3dc7bd)
    event.create("fluorescence_yeast")
        .dust()
        .color(0xe8f090)
    event.create("fluorescence_yeast_seed_liquid")
        .liquid()
        .color(0xe8f090)
    event.create("fluorescence_yeast_liquid")
        .liquid()
        .color(0xe5f163)
    event.create("fluorescence_yeast_extract_liquid")
        .liquid()
        .color(0xc7d24d)
    event.create("light_yeast")
        .dust()
        .color(0xc0e191)
    event.create("light_yeast_seed_liquid")
        .liquid()
        .color(0xc0e191)
    event.create("light_yeast_liquid")
        .liquid()
        .color(0xaae15b)
    event.create("light_yeast_extract_liquid")
        .liquid()
        .color(0x87bf38)
    event.create("polluted_fluorescence_yeast")
        .dust()
        .color(0x217523)
    event.create("radiation_mutated_yeast")
        .dust()
        .color(0x567a22)
    event.create("radiation_mutated_yeast_seed_liquid")
        .liquid()
        .color(0x567a22)
    event.create("radiation_mutated_yeast_liquid")
        .liquid()
        .color(0x46661a)
    event.create("radiation_mutated_yeast_extract_liquid")
        .liquid()
        .color(0x466916)
    event.create("waste_nutrition_liquid")
        .liquid()
        .color(0xf4db96)
    event.create("cellulose")
        .dust()
        .color(0xeee3bf)
    event.create("lignin")
        .dust()
        .color(0xb89320)
    event.create("lyase")
        .dust()
        .color(0xe4c86f)
    event.create("amino_acid")
        .liquid()
        .color(0xf4de5a)
    event.create("blue_vitriol_solution")
        .liquid()
        .color(0x48A5C0)
    event.create("chalcogen_anode_mud")
        .dust()
        .color(0x247a93)
    event.create("sodium_tellurite")
        .dust()
        .color(0x47d2e7)
    event.create("selenium_dioxide")
        .dust()
        .color(0xe4f437)
        .components('selenium','2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("tellurium_dioxide")
        .dust()
        .color(0xcbcd22)
        .components('tellurium','2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("selenous_acid")
        .liquid()
        .color(0x8d1152)
        .components('2x hydrogen','selenium','3x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("ammonium_sulfate")
        .liquid()
        .color(0x2759e7)
        .components('2x ammonia','sulfur','4x oxygen')
    event.create("ammonium_carbonate")
        .dust()
        .color(0x2654d8)
        .components('2x ammonia','carbon','3x oxygen')
    event.create("potassium_bisulfite")
        .dust()
        .color(0xb0afa5)
        .components("1x potassium", "1x sulfur", "1x hydrogen", "3x oxygen")
    event.create("potassium_nitrite")
        .dust()
        .color(0xc5c3b2)
    event.create("nitrous_acid")
        .liquid()
        .color(0xe2deb2)
        .components("1x hydrogen", "1x nitrogen", "2x oxygen")
    event.create("sodium_acetate")
        .liquid()
        .color(0x80e566)
    event.create("potassium_hydroxylamine_disulfonate")
        .dust()
        .color(0x3f7a30)
        .components("2x potassium", "1x nitrogen", "1x hydrogen", "2x sulfur", "7x oxygen")
    event.create("hydroxylammonium_sulfate")
        .dust()
        .color(0xa0a591)
        .components("2x nitrogen", "8x hydrogen", "1x sulfur", "6x oxygen")
    event.create("barium_chloride")
        .dust()
        .color(0xd26d4f)
        .components("1x barium", "2x chlorine")
    event.create("barium_sulfate_solution")
        .liquid()
        .color(0xa7c6e6)
    event.create("hydroxylamine_hydrochloride")
        .liquid()
        .color(0xe33333)
    event.create("succinic_acid")
        .dust()
        .color(0x0f6f6d)
    event.create("succinic_anhydride")
        .dust()
        .color(0x634010)
    event.create("acetylene")
        .gas()
        .color(0x8eb256)
        .components("2x carbon", "2x hydrogen")
    event.create("tetrahydrofuran")
        .liquid()
        .color(0x8fe5bc)
    event.create("nhydroxy_succinimide")
        .dust()
        .color(0x997db2)
    event.create("triethylamine")
        .liquid()
        .color(0x52686a)
    event.create("succinimidyl_acetate")
        .dust()
        .color(0x855c75)
    event.create("glyoxal")
        .liquid()
        .color(0xf0ed4d)
        .components("2x carbon", "2x hydrogen", "2x oxygen")
    event.create("ammonium_acetate")
        .dust()
        .color(0x73a3a7)
    event.create("acetamide")
        .dust()
        .color(0x638e92)
    event.create("acetonitrile")
        .dust()
        .color(0x889fb5)
        .components('carbon','3x hydrogen','carbon','nitrogen')
    event.create("benzyl_chloride")
        .liquid()
        .color(0x85e7e7)
        .components("7x carbon", "7x hydrogen", "1x chlorine")
    event.create("hexamethylenetetramine")
        .dust()
        .color(0x5a6261)
        .components("6x carbon", "12x hydrogen", "4x nitrogen")
    event.create("benzylamine")
        .liquid()
        .color(0x5b6363)
        .components("7x carbon", "9x hydrogen", "1x nitrogen")
    event.create("hexabenzylhexaazaisowurtzitane")
        .dust()
        .color(0x4a2367)
        .components("48x carbon", "48x hydrogen", "6x nitrogen")
    event.create("palladium_chloride")
        .dust()
        .color(0xcfcfcf)
        .components("1x palladium", "2x chlorine")
    event.create("dibenzyl_tetraacetylhexaazaisowurtzitane")
        .dust()
        .color(0x8ea268)
        .components("28x carbon", "32x hydrogen", "6x nitrogen", "4x oxygen")
    event.create("succinimide")
        .dust()
        .color(0x21a7c5)
    event.create("boron_fluoride")
        .liquid()
        .components("1x boron", "3x fluorine")
        .color(0xcecad0)
    event.create("nitronium_tetrafluoroborate")
        .dust()
        .color(0x3c3f40)
        .components("1x nitrogen", "2x oxygen", "1x boron", "4x fluorine")
    event.create("nitrosonium_tetrafluoroborate")
        .dust()
        .color(0x485054)
        .components("1x nitrogen", "1x oxygen", "1x boron", "4x fluorine")
    event.create("tetraacetyldinitrosohexaazaisowurtzitane")
        .dust()
        .color(0x500449)
    event.create("tetrafluoroboric_acid")
        .liquid()
        .color(0x7c8915)
    event.create("benzaldehyde")
        .liquid()
        .color(0x905a1b)
        .components("7x carbon", "6x hydrogen", "1x oxygen")
    event.create("crude_hexanitro_hexaazaisowurtzitane")
        .dust()
        .color(0x19586d)
    event.create("ethylenediamine")
        .liquid()
        .color(0x1b5d74)
        .components("2x carbon", "8x hydrogen", "2x nitrogen")
    event.create("silica_gel")
        .dust()
        .color(0x57c3e4)
    event.create("hexanitro_hexaazaisowurtzitane")
        .dust()
        .color(0x3d464b)
    event.create("boric_acid")
        .liquid()
        .color(0x8fbc8f)
    event.create("dimethylformamide")
        .liquid()
        .color(0x34f4a5)
    event.create("acetaldehyde")
        .liquid()
        .color(0xf9954a)
    event.create("sodium_periodate")
        .dust()
        .color(0x1438bb)
        .components("1x sodium", "1x iodine", "4x oxygen")
        .iconSet(GTMaterialIconSet.METALLIC)
    event.create("calcium_carbide")
        .dust()
        .color(0x3e4133)
        .components("1x carbon", "1x calcium")
    event.create("escherichia_coli")
        .dust()
        .color(0x014d15)
    event.create("sodium_iodate")
        .dust()
        .color(0x0e2887)
    event.create("sodium_sulfate_solution")
        .liquid()
        .color(0x454141)
    event.create("sodium_iodide")
        .dust()
        .color(0x335187)
        .components("1x sodium", "1x iodine")
    event.create("aeternium")
        .dust()
        .color(0x376169)
        .secondaryColor(0x2c7d74)
    event.create("ancient_debris")
        .dust()
        .color(0x59342a)
        .secondaryColor(0x734437)
    event.create("ancient_debris_leach")
        .liquid()
        .color(0x7a4437)
    event.create("jasper")
        .gem()
        .ore()
        .color(0xC85050)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD)
        .iconSet(GTMaterialIconSet.EMERALD)
    event.create("eglin_alloy")
        .ingot()
        .liquid()
        .color(0x6e3204)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
        .iconSet(GTMaterialIconSet.METALLIC)
        .blastTemp(1048)
        .components("5x invar", "4x iron", "1x kanthal", "1x sulfur", "1x silver", "1x carbon")
    event.create("inconel_625")
        .ingot()
        .liquid()
        .color(0x6eab6c)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
        .iconSet(GTMaterialIconSet.METALLIC)
        .blastTemp(6200)
        .components("2x nickel", "2x aluminium", "1x niobium", "1x nichrome")
    event.create("abyssalalloy")
        .ingot()
        .liquid()
        .blastTemp(10800, "higher", GTValues.VA[GTValues.UV], 1800)
        .components("5x stainless_steel", "5x tungsten_carbide", "5x nichrome", "5x bronze", "5x incoloy_ma_956", "1x iodine", "1x germanium", "1x radon", "1x hafnium")
        .color(0x9e706a)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.DISABLE_DECOMPOSITION)
        .cableProperties(GTValues.V[GTValues.UHV], 4, 64)
    event.create("titansteel")
        .ingot()
        .liquid()
        .blastTemp(12600, "higher", GTValues.VA[GTValues.UHV], 1200)
        .components("4x titanium_tungsten_carbide", "1x plutonium_241", "2x einsteinium", "1x rhenium", "1x erbium", "3x jasper")
        .color(0xe60000)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.DISABLE_DECOMPOSITION)
        .cableProperties(GTValues.V[GTValues.UEV], 4, 64)
    event.create("pikyonium")
        .ingot()
        .liquid()
        .radioactiveHazard(3)
        .blastTemp(14400, "higher")
        .components("8x inconel_625", "5x eglin_alloy", "4x enriched_naquadah", "4x tungsten_steel", "3x cerium", "2x antimony", "2x platinum", "1x ytterbium")
        .color(0x67abff)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE)
        .cableProperties(GTValues.V[GTValues.UIV], 4, 128)
    event.create("black_titanium")
        .ingot()
        .liquid()
        .blastTemp(16200, "highest", GTValues.VA[GTValues.UXV], 1400)
        .components("26x titanium", "6x lanthanum", "4x tungsten", "3x cobalt", "2x manganese", "2x phosphorus", "2x palladium", "1x niobium", "5x argon")
        .color(0x6C003B)
        .iconSet(GTMaterialIconSet.DULL)
        .flags(GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.DISABLE_DECOMPOSITION)
        .cableProperties(GTValues.V[GTValues.UXV], 4, 128)
    event.create("starmetal")
        .ingot()
        .liquid()
        .plasma()
        .addOreByproducts(GTMaterials.Sapphire, GTMaterials.Polonium)
        .radioactiveHazard(6)
        .blastTemp(21800, "highest")
        .element(GTElements.get("starmetal"))
        .color(0x0000e6)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE)
        .cableProperties(GTValues.V[GTValues.OpV], 4, 256)
    event.create("my_infinity")
        .ingot()
        .radioactiveHazard(20)
        .blastTemp(32000, "highest")
        .element(GTElements.get("my_infinity"))
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_FRAME)
        .cableProperties(GTValues.V[GTValues.MAX], 8192, 0, true)
    event.create("combustible_ice")
        .gem()
        .iconSet(GTMaterialIconSet.LIGNITE)
        .color(0xebfbfc)
        .burnTime(6000)
        .ore()
    event.create("mana")
        .liquid()
        .color(0x43e7ed)
    event.create("pyrotheum")
        .dust()
        .liquid(new $FluidBuilder()
            .temperature(5700)
            .customStill())
        .color(0xe8a62b)
    event.create("cryotheum")
        .dust()
        .liquid(new $FluidBuilder()
            .temperature(20)
            .customStill())
        .color(0x34daf7)
    event.create("hydrobromic_acid")
        .liquid()
        .color(0xd1593e)
        .components("1x hydrogen", "1x bromine")
    event.create("boron_oxide")
        .dust()
        .color(0x87cfed)
        .components("2x boron", "3x oxygen")
    event.create("flinak")
        .dust()
        .liquid()
        .color(0x5c5757)
        .components("3x fluorine", "1x lithium", "1x sodium", "1x potassium")
    event.create("silicon_fluoride")
        .liquid()
        .color(0x76868a)
        .components("1x silicon", "4x fluorine")
    event.create("carbon_fluoride")
        .liquid()
        .color(0xb8956d)
        .components("1x carbon", "4x fluorine")
    event.create("zirconium_tetrachloride")
        .dust()
        .color(0xd0db7d)
        .components("1x zirconium", "4x chlorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("silicon_carbide")
        .dust()
        .color(0x6edade)
        .components("1x silicon", "1x carbon")
    event.create("hot_steam")
        .liquid()
        .color(0xd4d4d4)
    event.create("hot_deuterium")
        .liquid()
        .color(0xe6e857)
    event.create("hot_sodium")
        .liquid()
        .color(0x237ad1)
    event.create("hot_sodium_potassium")
        .liquid()
        .color(0x39cf89)
    event.create("silicon_chloride")
        .liquid()
        .color(0x8ba4b0)
    event.create("barium_hydroxide")
        .dust()
        .color(0x58c95c)
    event.create("zircon")
        .gem()
        .ore()
        .addOreByproducts(GTMaterials.SiliconDioxide, GTMaterials.Yttrium)
        .color(0xEB9E3F)
        .iconSet(GTMaterialIconSet.GEM_VERTICAL)
        .components("1x zirconium", "1x silicon", "4x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("mesityl_oxide")
        .liquid()
        .color(0x97f78b)
    event.create("methyl_isobutyl_ketone")
        .liquid()
        .color(0x56d652)
    event.create("thiocyanic_acid")
        .liquid()
        .color(0xfffc64)
        .components("1x sulfur", "1x hydrogen_cyanide")
    event.create("zr_hf_separation_mix")
        .liquid()
        .color(0xcff760)
    event.create("zr_hf_chloride")
        .liquid()
        .color(0x65f04a)
    event.create("zircon_chlorinating_residue")
        .liquid()
        .color(0x50ba3a)
    event.create("zirkelite")
        .dust()
        .ore()
        .color(0x525e50)
        .components("2x calcium", "2x thorium", "1x cerium", "7x zirconium", "2x rutile", "4x niobium", "10x oxygen")
    event.create("zr_hf_oxy_chloride")
        .liquid()
        .color(0x70b063)
    event.create("cubic_zirconia")
        .dust()
        .color(0xf9e0fc)
        .components("1x zirconium", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("hafnium_oxide")
        .dust()
        .color(0x6b6e6b)
        .components("1x hafnium", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("hafnium_chloride")
        .dust()
        .color(0x9da19c)
        .components("1x hafnium", "4x chlorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("uranyl_chloride_solution")
        .liquid()
        .color(0xc5de56)
    event.create("uranyl_nitrate_solution")
        .liquid()
        .color(0xcae065)
    event.create("purified_uranyl_nitrate")
        .liquid()
        .color(0xe5f552)
    event.create("uranium_sulfate_waste_solution")
        .liquid()
        .color(0x9eb837)
    event.create("uranium_diuranate")
        .liquid()
        .color(0xc7db42)
    event.create("potassium_uranyl_tricarbonate")
        .dust()
        .color(0xd4e04c)
    event.create("piranha_solution")
        .liquid()
        .color(0x6c5ff5)
    event.create("uranium_refinement_waste_solution")
        .liquid()
        .color(0xc6db5b)
    event.create("uranium_peroxide_thorium_oxide")
        .dust()
        .color(0x5b5c5a)
    event.create("caesium_hydroxide")
        .dust()
        .color(0xdadbd6)
        .components("1x caesium", "1x oxygen", "1x hydrogen")
    event.create("molybdenum_trioxide")
        .dust()
        .color(0x8f8ae5)
        .components("1x molybdenum", "3x oxygen")
    event.create("uranium_thorium_oxide")
        .dust()
        .color(0x666665)
    event.create("uranyl_thorium_sulfate")
        .dust()
        .color(0xdced3f)
    event.create("uranyl_thorium_nitrate")
        .dust()
        .color(0xdff236)
    event.create("uranium_oxide_thorium_nitrate")
        .dust()
        .color(0x62f236)
    event.create("uranium_dioxide")
        .dust()
        .color(0x4ecf26)
        .components("1x uranium", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("thorium_nitrate_solution")
        .liquid()
        .color(0x4bab2d)
        .components("1x thorium", "1x nitrogen", "3x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("thorium_oxide")
        .dust()
        .color(0x757373)
        .components("1x thorium", "1x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("dirty_hexafluorosilicic_acid")
        .liquid()
        .color(0xdb6767)
    event.create("dilute_hexafluorosilicic_acid")
        .liquid()
        .color(0x7ae880)
    event.create("stone_residue")
        .dust()
        .color(0xa1a19e)
    event.create("fluorosilicic_acid")
        .liquid()
        .color(0x40ed57)
        .components("2x hydrogen", "1x silicon", "6x fluorine")
    event.create("uncommon_residues")
        .dust()
        .color(0x4f86c9)
    event.create("dioxygendifluoride")
        .liquid()
        .color(0x4fbbc9)
        .components("2x fluorine", "2x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("partially_oxidized_residues")
        .dust()
        .color(0x853525)
    event.create("inert_residues")
        .dust()
        .color(0x9d85a6)
    event.create("oxidized_residual_solution")
        .liquid()
        .color(0x83f2e1)
    event.create("oxidized_residues")
        .dust()
        .color(0x5e2b87)
    event.create("heavy_oxidized_residues")
        .dust()
        .color(0x5d208f)
    event.create("metallic_residues")
        .dust()
        .color(0x22a372)
    event.create("heavy_metallic_residues")
        .dust()
        .color(0x3488b5)
    event.create("diamagnetic_residues")
        .dust()
        .color(0x4cd98e)
    event.create("paramagnetic_residues")
        .dust()
        .color(0x4cbfd9)
    event.create("ferromagnetic_residues")
        .dust()
        .color(0x32b065)
    event.create("heavy_diamagnetic_residues")
        .dust()
        .color(0x3269b0)
    event.create("heavy_paramagnetic_residues")
        .dust()
        .color(0x2d9e4d)
    event.create("heavy_ferromagnetic_residues")
        .dust()
        .color(0x1e873b)
    event.create("exotic_heavy_residues")
        .dust()
        .color(0x26a2b5)
    event.create("clean_inert_residues")
        .dust()
        .color(0x0ebd54)
    event.create("dilute_hydrofluoric_acid")
        .liquid()
        .color(0xc7d7de)
        .components("1x hydrogen", "1x fluorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("helium3_hydride")
        .liquid()
        .color(0xd7e36a)
        .components("1x helium_3", "1x hydrogen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("ultraacidic_residue_solution")
        .liquid()
        .color(0x59ff7d)
    event.create("liquid_fluorine")
        .liquid(new $FluidBuilder()
            .temperature(100))
        .color(0x26a4e8)
        .components("1x fluorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("super_mana")
        .ingot()
        .color(0x4ac6e6)
        .cableProperties(GTValues.V[GTValues.IV], 6, 1, false)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
        .element(GTElements.get("super_mana"))
    event.create("sodium_carbonate_solution")
        .liquid()
        .color(0x636389)
    event.create("sodium_chromate_solution")
        .liquid()
        .color(0xbbb310)
    event.create("sodium_dichromate_solution")
        .liquid()
        .color(0xb55a10)
    event.create("chromium_oxide")
        .dust()
        .color(0x3dc34d).iconSet(GTMaterialIconSet.DULL)
        .components("2x chromium", "3x oxygen")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("impure_oil")
        .liquid()
        .color(0x171717)
    event.create("bitumen")
        .liquid()
        .color(0x51524a)
    event.create("petroleum_coke")
        .gem()
        .liquid()
        .color(0x545252)
        .iconSet(GTMaterialIconSet.LIGNITE)
        .burnTime(3200)
    event.create("dried_salt")
        .dust()
        .color(0x919182)
    event.create("emulsified_bitumen")
        .liquid()
        .color(0x848572)
    event.create("emulsified_bitumen_slurry")
        .liquid()
        .color(0x5b5c4c)
    event.create("simple_emulgator")
        .liquid()
        .color(0xd9de7c)
    event.create("simple_demulsifier")
        .liquid()
        .color(0xa2a659)
    event.create("emulgator")
        .liquid()
        .color(0xdce34f)
    event.create("butyl_acetate")
        .liquid()
        .color(0xffde49)
    event.create("pure_bitumen")
        .liquid()
        .color(0x696969)
    event.create("penicillin")
        .dust()
        .color(0x56bab5)
    event.create("oil_refined_residues")
        .dust()
        .color(0x828277)
    event.create("rich_soil")
        .dust()
        .color(0x613a0d)
        .iconSet(GTMaterialIconSet.DULL)
    event.create("ethanol_mixture")
        .liquid()
        .color(0xde671e)
    event.create("raw_bio_diesel")
        .liquid()
        .color(0xe8a548)
    event.create("rich_soul_soil")
        .dust()
        .color(0x426362)
        .iconSet(GTMaterialIconSet.DULL)
    event.create("aether_air")
        .gas()
        .color(0x8fddf2)
    event.create("liquid_aether_air")
        .liquid(new $FluidBuilder()
            .temperature(30))
        .color(0x7cb9c9)
    event.create("alfheim_air")
        .gas()
        .color(0xd798eb)
    event.create("liquid_alfheim_air")
        .liquid(new $FluidBuilder()
            .temperature(74))
        .color(0xb981c9)
    event.create("twilightforest_air")
        .gas()
        .color(0xaded9c)
    event.create("liquid_twilightforest_air")
        .liquid(new $FluidBuilder()
            .temperature(112))
        .color(0x8dc27f)
    event.create("venus_air")
        .liquid(new $FluidBuilder()
            .temperature(25))
        .color(0xede07d)
    event.create("liquid_venus_air")
        .liquid()
        .color(0xdbcf73)
    event.create("slag")
        .liquid()
        .ingot()
        .color(0x9e570a)
    event.create("calcium_sulfide")
        .dust()
        .components("calcium", "sulfur")
        .color(0xffffdc)
    event.create("asurine")
        .dust()
        .color(0x50a0de)
    event.create("crimsite")
        .dust()
        .color(0xbf4848)
    event.create("ochrum")
        .dust()
        .color(0xc9af03)
    event.create("veridium")
        .dust()
        .color(0x43b567)
    event.create("asurine_slurry")
        .liquid()
        .color(0x50a0de)
    event.create("crimsite_slurry")
        .liquid()   
        .color(0xbf4848)
    event.create("ochrum_slurry")
        .liquid()
        .color(0xc9af03)
    event.create("veridium_slurry")
        .liquid()
        .color(0x43b567)
    event.create("dirt")
        .dust()
        .color(0x9e7d0e)
    event.create("rhizobium")
        .dust()
        .color(0x5e3a03)
    event.create("azotase")
        .dust()
        .color(0xaade4b)
    event.create("rhizobium_extract")
        .liquid()
        .color(0x5e3a03)
    event.create("carbonate_buffer")
        .liquid()
        .color(0xfffcd6)
    event.create("phosphate_buffer")
        .liquid()
        .color(0xffdddd)
    event.create("trisodium_phosphate")
        .dust()
        .color(0xdbff67)
        .ore()
        .addOreByproducts(GTMaterials.Phosphate,GTMaterials.Salt)
        .components('3x sodium','phosphate')
    event.create("sodium_dihydrogen_phosphate")
        .dust()
        .color(0xe6ff67)
        .components('sodium','2x hydrogen','phosphate')
    event.create("dibasic_sodium_phosphate")
        .dust()
        .color(0xd2eb54)
        .components('2x sodium','hydrogen','phosphate')
    event.create("staballoy")
        .ingot()
        .liquid()
        .color(0x444B42)
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_RING)
        .components('9x uranium','titanium')
        .blastTemp(3450, "mid", 7680, 300)
    event.create("magneto_resonatic")
        .gem()
        .color(0xFF97FF)
        .iconSet(GTMaterialIconSet.MAGNETIC)
        .components('zanite','ambrosium','skyjade','cubic_zirconia','magnetic_steel')
    event.create("quartz_glass")
        .dust()
        .components("glass","certus_quartz")
        .color(0xd1f1fa)
    event.create('nickeline')
        .dust()
        .ore()
        .addOreByproducts(GTMaterials.get('arsenic_trioxide'))
        .components('nickel','arsenic')
    event.create('oxydianiline_sludge')
        .liquid()
        .color(0x68d6cb)
    event.create('oxydianiline')
        .liquid()
        .color(0x87f2e8)
    event.create('pyrometillic_dianhydride')
        .liquid()
        .color(0xe89c9c)
    event.create('kapton_k')
        .ingot()
        .liquid()
        .color(0x97f5a5)
        .flags(GTMaterialFlags.GENERATE_PLATE,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create('kapton_e')
        .ingot()
        .liquid()
        .color(0xf0f597)
        .flags(GTMaterialFlags.GENERATE_PLATE,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create('cobalt_bromide')
        .liquid()
        .color(0x9983e8)
        .components('cobalt','bromine')
    event.create('manganese_bromide')
        .liquid()
        .color(0xe883e1)
        .components('manganese','bromine')
    event.create('manganese_acetate')
        .liquid()
        .color(0xcded99)
        //.components('manganese','acetate_acid')
    event.create('co_mn_br_catalyst')
        .liquid()
        .color(0xdbe875)
    event.create('bis_trichloromethyl_benzene')
        .liquid()
        .color(0x75bae8)
    event.create('terephthalic_acid')
        .liquid()
        .color(0x75e8a3)
    event.create('terephthaloyl_chloride')
        .liquid()
        .color(0x90e0c7)
    event.create('nitroaniline')
        .liquid()
        .color(0xe090a8)
    event.create('para_phenylenediamine')
        .liquid()
        .color(0x4bb34d)
    event.create('para_aramid')
        .ingot()
        .liquid()
        .color(0x30cf7a)
        .flags(GTMaterialFlags.GENERATE_PLATE,GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_ROD,GTMaterialFlags.GENERATE_GEAR,GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create('fiber_glass')
        .ingot()    
        .liquid()
        .color(0xe0fffc)
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create("tantalum_alkaline_mixture")
        .liquid()
        .color(0x46A3FF)
    event.create("tantalite_oxide")
        .dust()
        .color(0x46A3FF)
        .components("2x tantalum", "5x oxygen")
    event.create("tantalite_fluorine")
        .liquid()
        .color(0x46A3AA)
    event.create("potassium_fluoride")
        .dust()
        .color(0xFF6666)
        .components("1x potassium", "1x fluorine")
    event.create("ammonium_hydroxide")
        .liquid()
        .color(0xE0E0E0)
    event.create("niobium_oxide")
        .dust()
        .color(0xB2A9A9)
        .components("2x niobium", "5x oxygen")
    event.create("niobium_tantalite")
        .liquid()
        .color(0xCCFFFF)
    event.create("ammonium_fluoride")
        .liquid()
        .color(0xFFCCCC)
    event.create("dibismuthhydroborat")
        .dust()
        .color(0x0ed138)
        .components('boron','hydrogen','2x bismuth')
    event.create("bismuth_tellurite")
        .dust()
        .color(0x95eb88)
        .components('2x bismuth','3x tellurium')
    event.create("circuit_compound")
        .dust()
        .color(0x4a4a4a)
        .components('3x dibismuthhydroborat','2x bismuth_tellurite','indium_gallium_phosphide')
    event.create("mystery_fluid")
        .liquid()
        .color(0x4ded1c)
    event.create("thermoduric_bacteria")
        .dust()
        .color(0xf77272)
    event.create("taq_enzyme")
        .dust()
        .color(0xfcbebe)
    event.create("thermoduric_bacteria_extract")
        .liquid()
        .color(0xd98484)
    event.create("escherichia_coli_extract")
        .liquid()
        .color(0x08632e)
    event.create("cellulase")
        .dust()
        .color(0x9fd4b5)
    event.create("rare_earth_fe_one")
        .dust()
        .color(0x6d6531)
    event.create("rare_earth_fe_two")
        .dust()
        .color(0x6d5231)
    event.create("rare_earth_intensive_research")
        .dust()
        .color(0x8a5d28)
    event.create("rare_earth_mixture")
        .dust()
        .color(0xcf8226)
    event.create("rare_earth_mixture_oh")
        .liquid()
        .color(0xdbb88f)
    event.create("rare_earth_crystals")
        .dust()
        .color(0x5f7632)
    event.create("rare_earth_chloride_boil")
        .liquid()
        .color(0x595b24)
    event.create("rare_earth_high_affinity")
        .liquid()
        .color(0x535612)
    event.create("rare_earth_low_affinty")
        .liquid()
        .color(0x34351d)
    event.create("rare_earth_high")
        .dust()
        .color(0x70723b)
    event.create("rare_earth_low")
        .dust()
        .color(0x94982a)
    event.create("rare_earth_middle")
        .dust()
        .color(0xbcbe79)
    event.create("rare_earth_high_fluoride")
        .liquid()
        .color(0xcfd534)
    event.create("rare_earth_middle_fluoride")
        .liquid()
        .color(0x919447)
    event.create("rare_earth_low_fluoride")
        .liquid()
        .color(0x9ea40a)
    event.create("rare_earth_low_fluoride_steam")
        .liquid()
        .color(0xefafcd)
    event.create("rare_earth_middle_fluoride_steam")
        .liquid()
        .color(0xe0e65c)
    event.create("rare_earth_high_fluoride_steam")
        .liquid()
        .color(0xe1e3a0)
    event.create("lanthanum_cerium_praseodymium_neodymium_oxygen_mixture")
        .dust()
        .color(0xeaebd1)
    event.create("europium_gadolinium_terbium_dysprosium_oxygen_mixture")
        .dust()
        .color(0xe7ea8f)
    event.create("yttrium_holmium_erbium_thulium_ytterbium_oxygen_lutetium_mixture")
        .dust()
        .color(0x9aa108)
    event.create("lan_cer_pra_neo_chloride")
        .dust()
        .color(0x5ea108)
    event.create("eur_gado_ter_dyspr_chloride")
        .dust()
        .color(0xb7f665)
    event.create("ytt_hol_erb_thu_ytt_chloride")
        .dust()
        .color(0x3f5d18)
    event.create('snow_steel')
        .ingot()
        .liquid()
        .color(0x00ffff)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create("refining_titanium_tetrachloride")
        .liquid()
        .color(0x631cab)
    event.create("aluminium_chloride")
        .dust()
        .color(0x045681)
    event.create("titanium_tetrachloride_V")
        .liquid()
        .color(0x024789)
    event.create("tungsten_trioxide")
        .dust()
        .color(0x474444)
})

StartupEvents.postInit(event => {
    TagPrefix.ingot.setIgnored(GTMaterials.get("mana_steel"), "botania:manasteel_ingot")
    TagPrefix.nugget.setIgnored(GTMaterials.get("mana_steel"), "botania:manasteel_nugget")
    TagPrefix.block.setIgnored(GTMaterials.get("mana_steel"), "botania:manasteel_block")
    TagPrefix.ingot.setIgnored(GTMaterials.get("terra_steel"), "botania:terrasteel_ingot")
    TagPrefix.nugget.setIgnored(GTMaterials.get("terra_steel"), "botania:terrasteel_nugget")
    TagPrefix.block.setIgnored(GTMaterials.get("terra_steel"), "botania:terrasteel_block")
    TagPrefix.ingot.setIgnored(GTMaterials.get("elementium"), "botania:elementium_ingot")
    TagPrefix.nugget.setIgnored(GTMaterials.get("elementium"), "botania:elementium_nugget")
    TagPrefix.block.setIgnored(GTMaterials.get("elementium"), "botania:elementium_block")
    TagPrefix.ingot.setIgnored(GTMaterials.get("alfsteel"), "mythicbotany:alfsteel_ingot")
    TagPrefix.nugget.setIgnored(GTMaterials.get("alfsteel"), "mythicbotany:alfsteel_nugget")
    TagPrefix.block.setIgnored(GTMaterials.get("alfsteel"), "mythicbotany:alfsteel_block")
    TagPrefix.gem.setIgnored(GTMaterials.CertusQuartz,'ae2:certus_quartz_crystal')
    TagPrefix.block.setIgnored(GTMaterials.CertusQuartz,'ae2:quartz_block')

    function setFormula(material, formula) {
        const mat = GTMaterials.get(material)
        if (mat === null)
            return
        mat.setFormula(formula)
    }
    setFormula("cryolite", "Na3AlF6")
    setFormula("sodium_hexafluoroaluminate", "Na3AlF6")
    setFormula("precious_alloy", "Au?")
    setFormula("potassium_metabi_sulfite", "K2S2O2")
    setFormula("alumina", "Al2O3")
    setFormula("sodium_fluoride", "NaF")
    setFormula("aluminium_trifluoride", "AlF3")
    setFormula("sodium_hydroxide_bauxite", "(TiO2)Al2H10O29-Na(OH)2")
    setFormula("gold_leach", "(Au)")
    setFormula("copper_leach", "(Cu)")
    setFormula("chloroauric_acid", "AuCl3")
    setFormula("impure_aluminium_hydroxide_solution", "(Al(OH)3)")
    setFormula("pure_aluminium_hydroxide_solution", "Al(OH)3")
    setFormula("red_mud", "Ti?Fe?")
    setFormula("neutralised_red_mud", "Ti?Fe?")
    setFormula("red_slurry", "Ti?")
    setFormula("titanyl_sulfate", "TiO(SO4)")
    setFormula("ferric_ree_chloride", "(FeCl3)")
    setFormula("aluminium_hydroxide", "Al(OH)3")
    setFormula("sodium_hydroxide_solution", "NaOH")
    setFormula("precious_alloy", "Au?")
    setFormula("cellulose", "(C6H10O5)n")
    setFormula("lignin", "(CH2ON?S?)n")
    setFormula("combustible_ice", "(CH4)(H2O)")
    setFormula("ammonium_sulfate", "(NH4)2SO4")
    setFormula("ammonium_hydroxide", "NH4OH")
    setFormula("niobium_tantalite", "Ta-Nb")
    setFormula("ammonium_fluoride", "NH4F")
    setFormula("rare_earth_fe_one", "Fe4?")
    setFormula("rare_earth_fe_two", "Fe2?")
    setFormula("rare_earth_intensive_research", "???")
    setFormula("rare_earth_crystals", "??")
    setFormula("rare_earth_high", "GdTbDyHoErTmYbLuY?")
    setFormula("rare_earth_low", "LaCePrNd?")
    setFormula("rare_earth_middle", "PmEuSm?")
    setFormula("snow_steel", "SNOWCITY")
    setFormula("refining_titanium_tetrachloride", "Re-TiCl4")
    setFormula("aluminium_chloride", "AlCl3")
    setFormula("titanium_tetrachloride_V", "V-TiCl4")
    setFormula("tungsten_trioxide", "WO3")
})
