GTCEuStartupEvents.registry('gtceu:machine', event =>{
    event.create('mana_macerator','multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('macerator')
        //.appearanceBlock(GTBlocks.get('kubejs:manasteel_casing'))
        .recipeModifier(GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("ABBA", "ABBA", "ABBA") 
            .aisle("ABBA", "ACCA", "ABBA") 
            .aisle("ABBA", "A@BA", "ABBA") 
            .where("A", Predicates.blocks("botania:polished_livingrock")
                    .or(Predicates.autoAbilities(definition.getRecipeTypes())))
            .where("B", Predicates.blocks("kubejs:manasteel_casing"))
            .where("C", Predicates.blocks("gtceu:steel_gearbox"))
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .build()
        )
        .workableCasingRenderer('kubejs:block/manasteel_casing',  'gtceu:block/multiblock/generator/large_steam_turbine', false)
})
