GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('meadow')
        .setMaxIOSize(3, 3, 3, 3)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('meadow', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('meadow')
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("#BBBBBBBBBB", "JCCCJCCCCCC", "J###J######", "JJJJJD#####", "EEEEE######", "###########") 
            .aisle("BBBBFFFBBBB", "CEE####GG#C", "#E#####GG##", "J###JD#####", "EEEEE######", "#EEE#######") 
            .aisle("BBBBFFFBBBB", "CE#####GG#C", "###########", "J###JD#####", "EEEEE######", "#EEE#######") 
            .aisle("BBBBFFFBBBB", "C#######G#C", "###########", "J###JD#####", "EEEEE######", "#EEE#######") 
            .aisle("BBBBBFFBBBB", "J###J#####C", "J###J######", "JJJJJD#####", "EEEEE######", "###########") 
            .aisle("BEEBFFFHHHB", "C#########C", "###########", "DDDDDD#####", "###########", "###########") 
            .aisle("BEEBFFFHHHB", "C######II#C", "###########", "###########", "###########", "###########") 
            .aisle("BEEBFFFHHHB", "C#######I#C", "###########", "###########", "###########", "###########") 
            .aisle("BEEBFFFBHHB", "C#########C", "###########", "###########", "###########", "###########") 
            .aisle("BEEBFFFBHHB", "C########IC", "###########", "###########", "###########", "###########") 
            .aisle("BBBBB@BBBBB", "CCCCCCCCCCC", "###########", "###########", "###########", "###########") 
            .where("B", Predicates.blocks("minecraft:dirt")
                        .or(Predicates.blocks("minecraft:grass_block")))
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .where("C", Predicates.blocks("minecraft:oak_fence"))
            .where("#", Predicates.any())
            .where("D", Predicates.blocks("minecraft:oak_stairs"))
            .where("E", Predicates.blocks("minecraft:hay_block"))
            .where("F", Predicates.blocks("minecraft:dirt_path"))
            .where("G", Predicates.blocks("farmersdelight:rich_soil"))
            .where("H", Predicates.blocks("minecraft:water"))
            .where("I", Predicates.blocks("minecraft:lily_pad"))
            .where("J",Predicates.blocks("minecraft:oak_log"))
            .build()
        )
        .workableCasingRenderer('minecraft:block/dirt', 'gtceu:block/multiblock/implosion_compressor', false)
})
