JEIEvents.information(event => {
    event.addItem('gtceu:hv_emitter', Text.translate('ctnh.blood_magic_gregtech_hv'))
    event.addItem('kubejs:stone_process_catalyst', Text.translate('ctnh.stone_process_catalyst'))
    event.addItem('kubejs:metallurgical_catalyst', Text.translate('ctnh.metallurgical_catalyst'))
    event.addItem('ctnhcore:bauxite_process_catalyst', Text.translate('ctnh.bauxite_process_catalyst'))
    event.addItem('kubejs:platinum_metal_catalyst_shard1', Text.translate('ctnh.platinum_metal_catalyst_shard1'))
    event.addItem('kubejs:platinum_metal_catalyst_shard2', Text.translate('ctnh.platinum_metal_catalyst_shard2'))
    event.addItem('gtceu:psionic_medulla_gem', Text.translate('ctnh.psionic_medulla'))
    event.addItem('bloodmagic:doubt_bucket', Text.translate('ctnh.doubt'))
})