ServerEvents.recipes(event => {

    event.recipes.gtceu.assembler('altar')
        .itemInputs('16x bloodmagic:ingot_hellforged')
        .itemInputs('16x bloodmagic:blankrune')
        .itemInputs('bloodmagic:altar')
        .itemInputs('2x bloodmagic:reagentbloodlight')
        .itemInputs('bloodmagic:etherealslate')
        .itemInputs('16x bloodmagic:defaultcrystal')
        .inputFluids(Fluid.of(Fluid.of("bloodmagic:life_essence_fluid"), 10000))
        .itemOutputs('ctnhcore:industrial_altar')
        .duration(1000)
        .EUt(1960)
    event.recipes.gtceu.industrial_altar('rune1')
        .itemInputs("botania:livingrock")
        .addData("addlp", -750)
        .itemOutputs('bloodmagic:blankslate')
        .duration(200)
        .EUt(480)
    event.recipes.gtceu.industrial_altar('rune2')
        .itemInputs('bloodmagic:blankslate')
        .addData("addlp", -1500)
        .itemOutputs('bloodmagic:reinforcedslate')
        .duration(400)
        .EUt(960)
    event.recipes.gtceu.industrial_altar('rune3')
        .itemInputs('bloodmagic:reinforcedslate')
        .addData("addlp", -3750)
        .itemOutputs('bloodmagic:infusedslate')
        .duration(150)
        .EUt(1960)
    event.recipes.gtceu.industrial_altar('rune4')
        .itemInputs('bloodmagic:infusedslate')
        .addData("addlp", -11250)
        .itemOutputs('bloodmagic:demonslate')
        .duration(250)
        .EUt(1960)
    event.recipes.gtceu.industrial_altar('rune5')
        .itemInputs('bloodmagic:demonslate')
        .addData("addlp", -22500)
        .itemOutputs('bloodmagic:etherealslate')
        .duration(200)
        .EUt(7680)
    event.recipes.gtceu.industrial_altar('rune6')
        .itemInputs('bloodmagic:etherealslate')
        .addData("addlp", -50000)
        .itemOutputs('kubejs:endslate')
        .duration(1000)
        .EUt(12222)
    event.recipes.gtceu.industrial_altar('blood_casing')
        .itemInputs('gtceu:solid_machine_casing')
        .addData("addlp", -7500)
        .itemOutputs('ctnhcore:blood_casing')
        .duration(200)
        .EUt(1960)
    event.recipes.gtceu.industrial_altar('bloodmagic:strong_tau')
        .itemInputs('bloodmagic:weak_tau')
        .addData("addlp", -3750)
        .itemOutputs('bloodmagic:strong_tau')
        .duration(200)
        .EUt(1960)
    event.recipes.gtceu.industrial_altar('bloodmagic:weakbloodshard')
        .itemInputs('bloodmagic:strong_tau')
        .addData("addlp", -37500)
        .itemOutputs('bloodmagic:weakbloodshard')
        .duration(400)
        .EUt(6666)
    event.recipes.gtceu.industrial_altar('bloodmagic:apprenticebloodorb')
        .itemInputs('minecraft:redstone_block')
        .addData("addlp", -3750)
        .itemOutputs('bloodmagic:apprenticebloodorb')
        .duration(800)
        .EUt(960)
    event.recipes.gtceu.industrial_altar('bloodmagic:weakbloodorb')
        .itemInputs('botania:terrasteel_ingot')
        .addData("addlp", -1500)
        .itemOutputs('bloodmagic:weakbloodorb')
        .duration(800)
        .EUt(480)
    event.recipes.gtceu.industrial_altar('bloodmagic:masterbloodorb')
        .itemInputs('bloodmagic:weakbloodshard')
        .addData("addlp", -30000)
        .itemOutputs('bloodmagic:masterbloodorb')
        .duration(400)
        .EUt(6666)
    event.recipes.gtceu.industrial_altar('bloodmagic:apprenticebloodorbx')
        .itemInputs('minecraft:gold_block')
        .addData("addlp", -22500)
        .itemOutputs('bloodmagic:magicianbloodorb')
        .duration(800)
        .EUt(1960)
    event.recipes.gtceu.industrial_altar('bloodmagic:apprenticebloodorby')
        .itemInputs('bloodmagic:dungeon_metal')
        .addData("addlp", -80000)
        .itemOutputs('bloodmagic:archmagebloodorb')
        .duration(200)
        .EUt(12222)
    event.recipes.gtceu.industrial_altar("addlp0")
        .circuit(0)
        .inputFluids(Fluid.of(Fluid.of("bloodmagic:life_essence_fluid"), 10000))
        .addData("addlp", 10000)
        .duration(800)
        .EUt(960)
    event.recipes.gtceu.industrial_altar("addlp1")
        .circuit(1)
        .inputFluids(Fluid.of(Fluid.of("bloodmagic:life_essence_fluid"), 25000))
        .itemInputs('bloodmagic:ingot_hellforged')
        .addData("addlp", 25000)
        .EUt(1960)
        .duration(100)
    event.recipes.gtceu.industrial_altar("addlp2")
        .circuit(2)
        .inputFluids(Fluid.of(Fluid.of("bloodmagic:life_essence_fluid"), 100000))
        .itemInputs('bloodmagic:ingot_hellforged')
        .itemInputs('bloodmagic:etherealslate')
        .addData("addlp", 175000)
        .EUt(7680)
        .duration(50)
    event.recipes.gtceu.industrial_altar("addlp3")
        .circuit(3)
        .inputFluids(Fluid.of(Fluid.of("bloodmagic:life_essence_fluid"), 1000000))
        .itemInputs('bloodmagic:ingot_hellforged')
        .itemInputs('ctnhcore:horizen_rune')
        .addData("addlp", 1000000)
        .EUt(20000)
        .duration(20)
    event.recipes.gtceu.industrial_altar('gtceu:blood_fuel')
        .outputFluids('gtceu:blood_fuel 66666')
        .itemInputs('8x bloodmagic:defaultcrystal')
        .addData("addlp", 66666)
        .EUt(7680)
        .duration(80)
})