ServerEvents.recipes(event => {

    event.recipes.gtceu.assembler('alter')
        .itemInputs('16x bloodmagic:ingot_hellforged')
        .itemInputs('16x bloodmagic:blankrune')
        .itemInputs('bloodmagic:altar')
        .itemInputs('2x bloodmagic:reagentbloodlight')
        .itemInputs('bloodmagic:etherealslate')
        .itemInputs('16x bloodmagic:defaultcrystal')
        .inputFluids(Fluid.of(Fluid.of("bloodmagic:life_essence_fluid"), 10000))
        .itemOutputs('ctnhcore:alter')
        .duration(1000)
        .EUt(1960)
    event.recipes.gtceu.alter('rune1')
        .itemInputs("botania:livingrock")
        .addData("addlp", -750)
        .itemOutputs('bloodmagic:blankslate')
        .duration(200)
        .EUt(480)
    event.recipes.gtceu.alter('rune2')
        .itemInputs('bloodmagic:blankslate')
        .addData("addlp", -1500)
        .itemOutputs('bloodmagic:reinforcedslate')
        .duration(400)
        .EUt(960)
    event.recipes.gtceu.alter('rune3')
        .itemInputs('bloodmagic:reinforcedslate')
        .addData("addlp", -3750)
        .itemOutputs('bloodmagic:infusedslate')
        .duration(150)
        .EUt(1960)
    event.recipes.gtceu.alter('rune4')
        .itemInputs('bloodmagic:infusedslate')
        .addData("addlp", -11250)
        .itemOutputs('bloodmagic:demonslate')
        .duration(250)
        .EUt(1960)
    event.recipes.gtceu.alter('rune5')
        .itemInputs('bloodmagic:demonslate')
        .addData("addlp", -22500)
        .itemOutputs('bloodmagic:etherealslate')
        .duration(200)
        .EUt(7680)
    event.recipes.gtceu.alter('rune6')
        .itemInputs('bloodmagic:etherealslate')
        .addData("addlp", -50000)
        .itemOutputs('bloodmagic:endslate')
        .duration(1000)
        .EUt(12222)
    event.recipes.gtceu.alter('blood_casing')
        .itemInputs('gtceu:solid_machine_casing')
        .addData("addlp", -7500)
        .itemOutputs('kubejs:blood_casing')
        .duration(200)
        .EUt(1960)
    event.recipes.gtceu.alter('bloodmagic:strong_tau')
        .itemInputs('bloodmagic:weak_tau')
        .addData("addlp", -3750)
        .itemOutputs('bloodmagic:strong_tau')
        .duration(200)
        .EUt(1960)
    event.recipes.gtceu.alter('bloodmagic:weakbloodshard')
        .itemInputs('bloodmagic:strong_tau')
        .addData("addlp", -37500)
        .itemOutputs('bloodmagic:weakbloodshard')
        .duration(400)
        .EUt(6666)
    event.recipes.gtceu.alter('bloodmagic:apprenticebloodorb')
        .itemInputs('minecraft:redstone_block')
        .addData("addlp", -3750)
        .itemOutputs('bloodmagic:apprenticebloodorb')
        .duration(800)
        .EUt(960)
    event.recipes.gtceu.alter('bloodmagic:weakbloodorb')
        .itemInputs('botania:terrasteel_ingot')
        .addData("addlp", -1500)
        .itemOutputs('bloodmagic:weakbloodorb')
        .duration(800)
        .EUt(480)
    event.recipes.gtceu.alter('bloodmagic:masterbloodorb')
        .itemInputs('bloodmagic:weakbloodshard')
        .addData("addlp", -30000)
        .itemOutputs('bloodmagic:masterbloodorb')
        .duration(400)
        .EUt(6666)
    event.recipes.gtceu.alter('bloodmagic:apprenticebloodorbx')
        .itemInputs('minecraft:gold_block')
        .addData("addlp", -22500)
        .itemOutputs('bloodmagic:magicianbloodorb')
        .duration(800)
        .EUt(1960)
    event.recipes.gtceu.alter('bloodmagic:apprenticebloodorby')
        .itemInputs('bloodmagic:dungeon_metal')
        .addData("addlp", -80000)
        .itemOutputs('bloodmagic:archmagebloodorb')
        .duration(200)
        .EUt(12222)
})