ServerEvents.recipes(event => {


    let ctnh = event.recipes.gtceu
    event.recipes.gtceu.arc_generator('arc_1')
        .itemInputs('gtceu:tungsten_steel_block')
        .itemOutputs('4x gtceu:tiny_tungsten_steel_dust')
        .EUt(-262144)
        .duration(200)
        .addData("requirearc", 100)
        .addData("maxarc", 1000)
    ctnh.assembler('ctnhcore:arc_cell')
        .itemOutputs('ctnhcore:arc_cell')
        .itemInputs('gtceu:electrolytic_cell')
        .itemInputs('4x gtceu:tungsten_steel_octal_wire')
        .itemInputs('2x #gtceu:circuits/luv')
        .duration(200)
        .EUt(8192)
    ctnh.assembler('ctnhcore:arc_reactor')
        .itemOutputs('ctnhcore:arc_reactor')
        .itemInputs('16x ctnhcore:arc_cell')
        .itemInputs('16x #gtceu:circuits/luv')
        .itemInputs('gtceu:large_electrolyzer')
        .itemInputs('64x gtceu:nonconducting_casing')
        .itemInputs('4x gtceu:tungsten_steel_octal_wire')
        .duration(1000)
        .EUt(8192)
    ctnh.assembler('ctnhcore:arc_generator')
        .itemOutputs('ctnhcore:arc_generator')
        .itemInputs('16x ctnhcore:arc_cell')
        .itemInputs('16x #gtceu:circuits/luv')
        .itemInputs('8x #gtceu:circuits/zpm')
        .itemInputs('gtceu:large_electrolyzer')
        .itemInputs('16x gtceu:samarium_iron_arsenic_oxide_hex_wire')
        .itemInputs('gtceu:nonconducting_casing')
        .duration(2000)
        .EUt(8192)

})