/*event.recipes.gtceu.配方类型("id")            
        .itemInputs("物品id","物品id",....)
        .itemOutputs("物品id")
        .duration(时间)
        .EUt(功率)*/
const GTNNRecipes = Java.loadClass("dev.arbor.gtnn.data.GTNNRecipes")
ServerEvents.recipes(event => {
  event.recipes.gtceu.create_mixer("rose_quartz")
    .itemInputs("minecraft:quartz", "4x minecraft:redstone")
    .itemOutputs("create:rose_quartz")
    .duration(100)
    .EUt(32)
    .rpm(64)
  event.recipes.gtceu.mixer("rose_quartz2")
    .itemInputs("minecraft:quartz", "4x minecraft:redstone")
    .itemOutputs("create:rose_quartz")
    .duration(100)
    .EUt(32)
  event.recipes.gtceu.create_mixer("polished_rose_quartz")
    .itemInputs("minecraft:quartz")
    .inputFluids("gtceu:redstone 288")
    .itemOutputs("create:polished_rose_quartz")
    .duration(100)
    .EUt(32)
    .rpm(64)
  event.recipes.gtceu.mixer("polished_rose_quartz2")
    .itemInputs("minecraft:quartz")
    .inputFluids("gtceu:redstone 288")
    .itemOutputs("create:polished_rose_quartz")
    .duration(100)
    .EUt(32)
  event.recipes.gtceu.alloy_smelter("andesite_alloy")
    .EUt(7)
    .duration(100)
    .itemInputs("minecraft:andesite")
    .itemInputs("minecraft:iron_ingot")
    .itemOutputs("2x gtceu:andesite_alloy_ingot")
  event.recipes.gtceu.assembler("manatransformer")
    .EUt(30)
    .duration(100)
    .itemInputs(["#gtceu:circuits/lv", "4x gtceu:red_alloy_plate", "4x botania:livingrock"])
    .itemOutputs("botania:mana_fluxfield")
  event.recipes.gtceu.assembler("submarine")
    .EUt(480)
    .duration(400)
    .itemInputs(["alexscaves:enigmatic_engine", "2x #gtceu:circuits/hv", "4x gtceu:energy_crystal", "2x gtceu:hv_sensor", "4x gtceu:hv_electric_motor", "8x gtceu:red_steel_plate"])
    .itemOutputs("alexscaves:submarine")
  event.recipes.gtceu.desalting("salt1")
    .EUt(120)
    .duration(400)
    .blastFurnaceTemp(1600)
    .circuit(0)
    .inputFluids("minecraft:water 1000")
    .itemOutputs("2x gtceu:salt_dust")
    .chancedOutput("gtceu:small_rock_salt_dust", 4000, 500)
  event.recipes.gtceu.desalting("salt2")
    .EUt(480)
    .duration(400)
    .blastFurnaceTemp(2900)
    .circuit(1)
    .inputFluids("minecraft:water 2000")
    .itemOutputs("3x gtceu:salt_dust")
    .chancedOutput("gtceu:small_rock_salt_dust", 6000, 500)
    .outputFluids("gtceu:iodized_brine 100")
  event.recipes.gtceu.alloy_smelter("scarlet_ingot")
    .EUt(7)
    .duration(100)
    .itemInputs(["alexscaves:raw_scarlet_neodymium", "minecraft:iron_ingot"])
    .itemOutputs("2x alexscaves:scarlet_neodymium_ingot")
  event.recipes.gtceu.alloy_smelter("azure_ingot")
    .EUt(7)
    .duration(100)
    .itemInputs(["alexscaves:raw_azure_neodymium", "minecraft:iron_ingot"])
    .itemOutputs("2x alexscaves:azure_neodymium_ingot")
  event.recipes.gtceu.mixer("sky_dust")
    .EUt(120)
    .duration(100)
    .itemInputs(["10x gtceu:stone_dust", "2x gtceu:silicon_dust", "gtceu:electrotine_dust"])
    .itemOutputs("13x ae2:sky_dust")
    .circuit(2)
  event.recipes.gtceu.compressor("dense_obsidian_plate")
    .EUt(96)
    .duration(400)
    .itemInputs("9x gtceu:obsidian_plate")
    .circuit(9)
    .itemOutputs("gtceu:dense_obsidian_plate")
  event.recipes.gtceu.compressor("dense_obsidian_plate2")
    .EUt(96)
    .duration(400)
    .itemInputs("9x gtceu:obsidian_dust")
    .circuit(9)
    .itemOutputs("gtceu:dense_obsidian_plate")
  /*event.recipes.gtceu.rocket_engine("rocket_fuel")
  .outputEU(25600)
  .duration(25)
  .inputFluids("gtceu:rocket_fuel 16")*/
  event.recipes.gtceu.alloy_smelter("dark_steel")
    .EUt(120)
    .duration(150)
    .itemInputs(["gtceu:steel_ingot", "gtceu:obsidian_dust"])
    .itemOutputs("gtceu:dark_steel_ingot")
  event.recipes.gtceu.primitive_blast_furnace("lockwood")
    .duration(1500)
    .itemInputs(["twilightforest:ironwood_ingot", "gtceu:coke_gem"])
    .itemOutputs("tetranichematerials:lockwood_ingot")
    .chancedOutput("gtceu:ash_dust", 1111, 0)
  event.recipes.gtceu.primitive_blast_furnace("lockwood2")
    .duration(1500)
    .itemInputs(["twilightforest:ironwood_ingot", "gtceu:coke_dust"])
    .itemOutputs("tetranichematerials:lockwood_ingot")
    .chancedOutput("gtceu:ash_dust", 1111, 0)
  event.recipes.gtceu.kinetic_steam_turbine("steam")
    .inputFluids(Fluid.of("gtceu:steam", 640))
    .outputFluids(Fluid.of("gtceu:distilled_water", 4))
    .outputStress(8192)
    .duration(10)
  event.recipes.gtceu.seaweed_farm("seaweed")
    .itemInputs("gtceu:fertilizer")
    .notConsumable("minecraft:kelp")
    .duration(400)
    .itemOutputs("4x minecraft:kelp")
    .chancedOutput("2x minecraft:kelp", 2000, 500)
    .chancedOutput("1x minecraft:kelp", 500, 500)
    .inputStress(512)
  event.recipes.gtceu.chemical_reactor("fix")
    .inputFluids(Fluid.of("gtceu:dilute_iodine_solution", 1000))
    .inputFluids(Fluid.of("gtceu:chlorine", 2000))
    .outputFluids(Fluid.of("gtceu:iodine_solution", 1000))
    .outputFluids(Fluid.of("gtceu:hydrochloric_acid", 2000))
    .duration(100)
    .EUt(240)
  event.remove({ id: "gtceu:chemical_reactor/iodine_solution" })
  event.remove({ id: "gtceu:large_chemical_reactor/iodine_solution" })
  event.recipes.gtceu.mixer("aeternium")
    .itemInputs("2x gtceu:steel_dust")
    .itemInputs("gtceu:ender_pearl_dust")
    .itemInputs("gtceu:netherite_dust")
    .itemOutputs("4x gtceu:aeternium_dust")
    .EUt(480)
    .duration(100)
  event.recipes.gtceu.electric_blast_furnace("aeternium_ingot")
    .itemInputs("gtceu:aeternium_dust")
    .itemOutputs("betterend:aeternium_ingot")
    .circuit(1)
    .EUt(1920)
    .duration(664)
  // event.recipes.gtceu.electric_blast_furnace("aeternium_ingot")
  // .itemInputs("gtceu:aeternium_dust")
  // .itemOutputs("betterend:aeternium_ingot")
  // .InputFluids(Fluid.of("gtceu:nitrogen",1000))
  // .circuit(1)
  // .EUt(1920)
  // .duration(664)
  event.recipes.gtceu.chemical_reactor("ancient_debris_leach")
    .itemInputs("3x gtceu:ancient_debris_dust")
    .inputFluids(Fluid.of("gtceu:aqua_regia", 3000))
    .outputFluids(Fluid.of("gtceu:ancient_debris_leach", 2000))
    .outputFluids(Fluid.of("gtceu:nitrogen_dioxide", 1000))
    .EUt(120)
    .duration(100)
  event.recipes.gtceu.macerator("ancient_debris_dust")
    .itemInputs("minecraft:ancient_debris")
    .itemOutputs("4x gtceu:ancient_debris_dust")
    .itemOutputs("1x gtceu:netherrack_dust")
    .chancedOutput("1x gtceu:gold_dust", 2000, 200)
    .EUt(120)
    .duration(200)
  event.recipes.gtceu.centrifuge("netherite_dust")
    .itemInputs("2x gtceu:gold_dust")
    .inputFluids(Fluid.of("gtceu:ancient_debris_leach", 2000))
    .outputFluids(Fluid.of("gtceu:rare_earth_chloride_solution", 2000))
    .itemOutputs("gtceu:netherite_dust")
    .EUt(120)
    .duration(100)
  event.recipes.gtceu.slaughter_house("kill")
    .EUt(480)
    .duration(60)
    .inputFluids(Fluid.of("gtceu:lubricant", 2))
  event.recipes.gtceu.assembler("blaze_blast_furnace_casing")
    .itemInputs(["4x gtceu:stainless_steel_plate", "2x gtceu:stainless_steel_frame", "botania:blaze_block"])
    .inputFluids(Fluid.of("gtceu:polyvinyl_chloride", 288))
    .EUt(480)
    .duration(100)
    .itemOutputs("kubejs:blaze_blast_furnace_casing")
  event.recipes.gtceu.mana_generator("mana_generator")
    .inputFluids(Fluid.of("gtceu:mana", 4))
    .duration(60)
    .EUt(-32)
    .circuit(0)
  let tier1 = ["water", "fire", "earth", "air"]
  let tier2 = ["spring", "summer", "autumn", "winter", "mana"]
  let tier3 = ["lust", "gluttony", "greed", "sloth", "wrath", "envy", "pride"]
  let tier4 = ["asgard", "vanaheim", "alfheim", "midgard", "joetunheim", "muspelheim", "niflheim", "nidavellir", "helheim"]
  tier1.forEach(rune => {
    event.recipes.gtceu.mana_generator("mana_generator_rune_" + rune)
      .inputFluids(Fluid.of("gtceu:mana", 4))
      .chancedInput("botania:rune_" + rune, 500, 0)
      .duration(80)
      .EUt(-32)
      .circuit(1)
  })
  tier2.forEach(rune => {
    event.recipes.gtceu.mana_generator("mana_generator_rune_" + rune)
      .inputFluids(Fluid.of("gtceu:mana", 4))
      .chancedInput("botania:rune_" + rune, 250, 0)
      .duration(100)
      .EUt(-32)
      .circuit(1)
  })
  tier3.forEach(rune => {
    event.recipes.gtceu.mana_generator("mana_generator_rune_" + rune)
      .inputFluids(Fluid.of("gtceu:mana", 4))
      .chancedInput("botania:rune_" + rune, 125, 0)
      .duration(100)
      .EUt(-48)
      .circuit(1)
  })
  tier4.forEach(rune => {
    event.recipes.gtceu.mana_generator("mana_generator_rune_" + rune)
      .inputFluids(Fluid.of("gtceu:mana", 4))
      .notConsumable("mythicbotany:" + rune + "_rune")
      .duration(120)
      .EUt(-48)
      .circuit(1)
  })
  event.recipes.gtceu.assembler("blaze_blast_furnace")
    .itemInputs(["4x gtceu:nano_processor_assembly", "4x kubejs:blaze_blast_furnace_casing", "2x gtceu:pyrotheum_dust", "2x gtceu:hv_sensor", "gtceu:hv_field_generator"])
    .inputFluids(Fluid.of("gtceu:polyvinyl_chloride", 288))
    .EUt(480)
    .duration(200)
    .itemOutputs("gtceu:blaze_blast_furnace")
  event.recipes.gtceu.assembler("temperature_keeping_device")
    .itemInputs(["4x gtnn:heavy_plate_t1", "minecraft:iron_chestplate", "2x gtceu:polyvinyl_chloride_foil", "gtceu:pyrotheum_bucket", "gtceu:cryotheum_bucket", "2x gtceu:hv_sensor", "cold_sweat:thermometer"])
    .itemOutputs("kubejs:temperature_keeping_device")
    .inputFluids(Fluid.of("gtceu:polyethylene", 288))
    .EUt(480)
    .duration(400)
  event.recipes.gtceu.mixer("pyrotheum")
    .itemInputs(["gtceu:small_saltpeter_dust", "gtceu:sulfur_dust", "gtceu:coke_dust", "minecraft:blaze_powder"])
    .itemOutputs("2x gtceu:pyrotheum_dust")
    .EUt(120)
    .duration(40)
  event.recipes.gtceu.mixer("cryotheum")
    .itemInputs(["gtceu:small_saltpeter_dust", "minecraft:snowball", "gtceu:ice_dust", "minecraft:redstone"])
    .itemOutputs("2x gtceu:cryotheum_dust")
    .EUt(480)
    .duration(40)
  event.recipes.gtceu.water_power("water_power")
    .inputFluids(Fluid.of("gtceu:lubricant", 2))
    .duration(20)
    .EUt(-32)
  event.recipes.gtceu.primitive_blast_furnace("high_quality")
    .itemInputs(["minecraft:iron_ingot", "kubejs:high_quality_solid_fuel"])
    .itemOutputs("gtceu:steel_ingot")
    .chancedOutput("gtceu:ash_dust", 500, 0)
    .duration(1200)
  event.recipes.gtceu.primitive_blast_furnace("high_quality1")
    .itemInputs(["gtceu:wrought_iron_ingot", "kubejs:high_quality_solid_fuel"])
    .itemOutputs("gtceu:steel_ingot")
    .chancedOutput("gtceu:ash_dust", 500, 0)
    .duration(300)
  event.recipes.gtceu.assembler("thermometer_casing")
    .itemInputs(["2x gtceu:gold_plate", "2x minecraft:redstone", "gtceu:steel_rod"])
    .itemOutputs("kubejs:thermometer_case")
    .inputFluids(Fluid.of("gtceu:rubber", 144))
    .EUt(30)
    .duration(100)
  event.recipes.gtceu.chemical_reactor("titaniumtetrachloride")
    .itemInputs(["gtceu:rutile_dust", "2x gtceu:carbon_dust"])
    .inputFluids(Fluid.of("gtceu:chlorine", 4000))
    .outputFluids([Fluid.of("gtceu:titanium_tetrachloride", 1000), Fluid.of("gtceu:carbon_monoxite", 2000)])
    .EUt(480)
    .duration(500)
  event.recipes.gtceu.chemical_plant("rp_1_mixed_fuel")
    .inputFluids(Fluid.of("gtceu:rp_1_rocket_fuel", 500))
    .inputFluids(Fluid.of("gtceu:rocket_fuel", 500))
    .outputFluids(Fluid.of("gtceu:rp_1_mixed_fuel", 1000))
    .inputFluids(Fluid.of("gtceu:oxygen", 2000))
    .circuit(1)
    .addCondition(GTNNRecipes.INSTANCE.setPlantCasing(5))
    .EUt(480)
    .duration(300)
  event.recipes.gtceu.photovoltaic_power("photovoltaic_power")
    .inputFluids(Fluid.of("minecraft:water", 100))
    .EUt(-512)
    .duration(10)
  event.recipes.gtceu.hot_coolant_turbine("steam")
    .inputFluids(Fluid.of("gtceu:hot_steam", 540))
    .outputFluids(Fluid.of("gtceu:steam", 540))
    .EUt(-32)
    .duration(20)
  event.recipes.gtceu.hot_coolant_turbine("deuterium")
    .inputFluids(Fluid.of("gtceu:hot_deuterium", 180))
    .outputFluids(Fluid.of("gtceu:deuterium", 180))
    .EUt(-32)
    .duration(20)
  event.recipes.gtceu.hot_coolant_turbine("sodium")
    .inputFluids(Fluid.of("gtceu:hot_sodium", 108))
    .outputFluids(Fluid.of("gtceu:sodium", 108))
    .EUt(-32)
    .duration(20)
  event.recipes.gtceu.hot_coolant_turbine("sodium_potassium")
    .inputFluids(Fluid.of("gtceu:hot_sodium_potassium", 90))
    .outputFluids(Fluid.of("gtceu:sodium_potassium", 90))
    .EUt(-32)
    .duration(20)
  event.recipes.gtceu.forming_press("shielded_reactor_casing")
    .itemInputs(["12x gtceu:dense_lead_plate", "2x gtceu:dense_stainless_steel_plate", "4x gtceu:dense_vanadium_steel_plate"])
    .itemOutputs("4x kubejs:shielded_reactor_casing")
    .EUt(500)
    .duration(1500)
  event.recipes.gtceu.assembler("nuclear_reactor")
    .itemInputs(["4x kubejs:shielded_reactor_casing", "2x gtceu:ev_sensor", "2x gtceu:ev_electric_motor", "2x gtceu:ultimet_plate"])
    .itemOutputs("gtceu:nuclear_reactor")
    .EUt(1920)
    .duration(400)
  event.recipes.gtceu.assembler("hot_coolant_turbine")
    .itemInputs(["4x gtceu:stellite_100_gear", "2x #gtceu:circuits/ev", "2x gtceu:ultimet_large_item_pipe", "gtceu:ev_machine_hull"])
    .itemOutputs("gtceu:hot_coolant_turbine")
    .EUt(1920)
    .duration(400)
  event.recipes.gtceu.centrifuge("mana_fused")
    .itemInputs("4x gtceu:mana_fused_dust")
    .itemOutputs("3x gtceu:mana_steel_dust")
    .itemOutputs("botania:mana_diamond")
    .chancedOutput("gtceu:elementium_dust", 2000, 500)
    .EUt(120)
    .duration(160)
  event.recipes.gtceu.centrifuge("alexscaves:acid")
    .inputFluids(Fluid.of("alexscaves:acid", 1000))
    .outputFluids(Fluid.of("minecraft:water", 500))
    .outputFluids(Fluid.of("gtceu:hydrochloric_acid", 250))
    .outputFluids(Fluid.of("gtceu:sulfuric_acid", 100))
    .outputFluids(Fluid.of("gtceu:phosphoric_acid", 150))
    .itemOutputs("2x gtceu:tiny_uranium_dust")
    .chancedOutput("gtceu:tiny_plutonium_dust", 2000, 500)
    .EUt(30)
    .duration(80)
  event.recipes.gtceu.gaia_reactor("gaia1")
    .itemInputs("botania:terrasteel_ingot")
    .itemOutputs("4x botania:life_essence")
    .itemOutputs("10x botania:manasteel_ingot")
    .itemOutputs("5x botania:mana_diamond")
    .itemOutputs("5x botania:mana_pearl")
    .outputFluids(Fluid.of("gtceu:mana", 1000))
    .chancedOutput("botania:rune_water", 2500, 250)
    .chancedOutput("botania:rune_fire", 2500, 250)
    .chancedOutput("botania:rune_earth", 2500, 250)
    .chancedOutput("botania:rune_air", 2500, 250)
    .chancedOutput("botania:rune_spring", 1500, 150)
    .chancedOutput("botania:rune_summer", 1500, 150)
    .chancedOutput("botania:rune_autumn", 1500, 150)
    .chancedOutput("botania:rune_winter", 1500, 150)
    .duration(400)
    .EUt(480)

  event.recipes.gtceu.gaia_reactor("gaia2")
    .itemInputs("botania:gaia_ingot")
    .itemOutputs("16x botania:life_essence")
    .itemOutputs("12x botania:manasteel_ingot")
    .itemOutputs("8x botania:mana_diamond")
    .itemOutputs("8x botania:mana_pearl")
    .itemOutputs("2x botania:terrasteel_ingot")
    .itemOutputs("4x botania:dragonstone")
    .outputFluids(Fluid.of("gtceu:mana", 10000))
    .chancedOutput("botania:rune_water", 5000, 500)
    .chancedOutput("botania:rune_fire", 5000, 500)
    .chancedOutput("botania:rune_earth", 5000, 500)
    .chancedOutput("botania:rune_air", 5000, 500)
    .chancedOutput("botania:rune_spring", 3000, 300)
    .chancedOutput("botania:rune_summer", 3000, 300)
    .chancedOutput("botania:rune_autumn", 3000, 300)
    .chancedOutput("botania:rune_winter", 3000, 300)
    .chancedOutput("botania:rune_lust", 2000, 200)
    .chancedOutput("botania:rune_gluttony", 2000, 200)
    .chancedOutput("botania:rune_greed", 2000, 200)
    .chancedOutput("botania:rune_sloth", 2000, 200)
    .chancedOutput("botania:rune_wrath", 2000, 200)
    .chancedOutput("botania:rune_envy", 2000, 200)
    .chancedOutput("botania:rune_pride", 2000, 200)
    .duration(800)
    .EUt(1920)

  event.recipes.gtceu.assembler("gaia_reactor")
    .EUt(120)
    .duration(200)
    .itemInputs(["4x botania:gaia_ingot", "4x gtceu:solid_machine_casing", "2x gtceu:mv_emitter", "2x botania:mana_diamond", "2x gtceu:terra_steel_screw"])
    .inputFluids(Fluid.of("gtceu:polyethylene", 288))
    .itemOutputs("gtceu:gaia_reactor")

  event.remove({ id: "gtceu:assembler/cover_ender_fluid_link" })
  event.recipes.gtceu.assembler("cover_ender_fluid_link")
    .EUt(480)
    .duration(320)
    .itemInputs(["2x gtceu:ender_pearl_plate", "gtceu:hv_sensor", "gtceu:double_stainless_steel_plate", "gtceu:hv_emitter", "gtceu:hv_electric_pump"])
    .inputFluids(Fluid.of("gtceu:polyethylene", 288))
    .itemOutputs("gtceu:ender_fluid_link_cover")

  event.recipes.gtceu.macerator("tiny_uranium_dust")
    .itemInputs("alexscaves:uranium_shard")
    .itemOutputs("gtceu:tiny_uranium_dust")
    .chancedOutput("gtceu:tiny_uranium_dust", 2000, 150)
    .duration(20)
    .EUt(30)

  event.recipes.gtceu.assembler("lv_energy_output_hatch_4a")
    .itemInputs(["gtceu:lv_energy_output_hatch", "2x gtceu:tin_quadruple_wire", "2x gtceu:steel_plate"])
    .itemOutputs("gtceu:lv_energy_output_hatch_4a0")
    .EUt(7)
    .duration(100)

  event.recipes.gtceu.assembler("mv_energy_output_hatch_4a")
    .itemInputs(["gtceu:mv_energy_output_hatch", "2x gtceu:cupronickel_quadruple_wire", "2x gtceu:aluminium_plate"])
    .itemOutputs("gtceu:mv_energy_output_hatch_4a1")
    .EUt(30)
    .duration(100)

  event.recipes.gtceu.assembler("hv_energy_output_hatch_4a")
    .itemInputs(["gtceu:hv_energy_output_hatch", "2x gtceu:silver_quadruple_wire", "2x gtceu:stainless_steel_plate"])
    .itemOutputs("gtceu:hv_energy_output_hatch_4a2")
    .EUt(120)
    .duration(100)

  event.recipes.gtceu.centrifuge("oil_refined_residues")
    .itemInputs("gtceu:oil_refined_residues_dust")
    .itemOutputs("gtceu:stone_dust")
    .itemOutputs("gtceu:small_oxidized_residues_dust")
    .chancedOutput("gtceu:magnetite_dust", 1500, 100)
    .chancedOutput("gtceu:garnierite_dust", 1500, 100)
    .chancedOutput("gtceu:pyrite_dust", 1500, 100)
    .EUt(30)
    .duration(20)
  event.recipes.gtceu.centrifuge("dried_salt")
    .itemInputs("gtceu:dried_salt_dust")
    .itemOutputs("gtceu:stone_dust")
    .itemOutputs("2x gtceu:tiny_salt_dust")
    .itemOutputs("2x gtceu:tiny_rock_salt_dust")
    .EUt(30)
    .duration(20)

  event.recipes.gtceu.macerator("dried_salt_stone")
    .itemInputs("biomesoplenty:dried_salt")
    .itemOutputs("gtceu:dried_salt_dust")
    .EUt(16)
    .duration(30)

  event.replaceOutput({ id: "gtceu:centrifuge/endstone_separation" }, "gtceu:platinum_dust", "gtceu:platinum_metal_dust")

  event.recipes.gtceu.macerator("rich_soil")
    .itemInputs("farmersdelight:rich_soil")
    .itemOutputs("4x gtceu:rich_soil_dust")
    .chancedOutput("gtceu:normal_yeast_dust", 2500, 200)
    .EUt(30)
    .duration(20)

  event.recipes.gtceu.macerator("rich_soul_soil")
    .itemInputs("nethersdelight:rich_soul_soil")
    .itemOutputs("4x gtceu:rich_soul_soil_dust")
    .chancedOutput("gtceu:crimson_yeast_dust", 1500, 150)
    .chancedOutput("gtceu:wraped_yeast_dust", 1500, 150)
    .EUt(30)
    .duration(20)

  event.replaceInput({ id: "gtceu:shaped/small_wooden_pipe" }, "#minecraft:planks", "gtceu:wood_plate")
  event.recipes.gtceu.gas_collector("twilightforest_air")
    .circuit(4)
    .dimension("twilightforest:twilight_forest")
    .outputFluids(Fluid.of("gtceu:twilightforest_air", 10000))
    .EUt(16)
    .duration(200)
  event.recipes.gtceu.gas_collector("alfheim_air")
    .circuit(5)
    .dimension("mythicbotany:alfheim")
    .outputFluids(Fluid.of("gtceu:alfheim_air", 10000))
    .EUt(64)
    .duration(200)
  event.recipes.gtceu.gas_collector("aether_air")
    .circuit(6)
    .dimension("aether:the_aether")
    .outputFluids(Fluid.of("gtceu:aether_air", 10000))
    .EUt(256)
    .duration(200)
  event.recipes.gtceu.gas_collector("venus_air")
    .circuit(7)
    .dimension("ad_astra:venus")
    .outputFluids(Fluid.of("gtceu:venus_air", 10000))
    .EUt(1024)
    .duration(200)
  event.recipes.gtceu.vacuum_freezer("twilightforest_air_freeze")
    .inputFluids(Fluid.of("gtceu:twilightforest_air", 4000))
    .outputFluids(Fluid.of("gtceu:liquid_twilightforest_air", 4000))
    .EUt(120)
    .duration(80)
  event.recipes.gtceu.vacuum_freezer("alfheim_air_freeze")
    .inputFluids(Fluid.of("gtceu:alfheim_air", 4000))
    .outputFluids(Fluid.of("gtceu:liquid_alfheim_air", 4000))
    .EUt(480)
    .duration(80)
  event.recipes.gtceu.vacuum_freezer("aether_air_freeze")
    .inputFluids(Fluid.of("gtceu:aether_air", 4000))
    .outputFluids(Fluid.of("gtceu:liquid_aether_air", 4000))
    .EUt(GTValues.VA[GTValues.LuV])
    .duration(80)
  event.recipes.gtceu.vacuum_freezer("venus_air_freeze")
    .inputFluids(Fluid.of("gtceu:venus_air", 4000))
    .outputFluids(Fluid.of("gtceu:liquid_venus_air", 4000))
    .EUt(GTValues.VA[GTValues.LuV])
    .duration(80)
  event.recipes.gtceu.distillation_tower("liquid_twilightforest_air")
    .inputFluids(Fluid.of("gtceu:liquid_twilightforest_air", 25000))
    .outputFluids(Fluid.of("gtceu:nitrogen", 12500))
    .outputFluids(Fluid.of("gtceu:oxygen", 10000))
    .outputFluids(Fluid.of("gtceu:carbon_dioxide", 2000))
    .outputFluids(Fluid.of("gtceu:helium", 500))
    .EUt(120)
    .duration(2000)
  event.recipes.gtceu.centrifuge("twilightforest_air")
    .inputFluids(Fluid.of("gtceu:twilightforest_air", 10000))
    .outputFluids(Fluid.of("gtceu:nitrogen", 2500))
    .outputFluids(Fluid.of("gtceu:oxygen", 2500))
    .EUt(7)
    .duration(800)
  event.recipes.gtceu.distillation_tower("liquid_alfheim_air")
    .inputFluids(Fluid.of("gtceu:liquid_alfheim_air", 100000))
    .itemOutputs("botania:mana_powder")
    .outputFluids(Fluid.of("gtceu:mana", 40000))
    .outputFluids(Fluid.of("gtceu:oxygen", 25000))
    .outputFluids(Fluid.of("gtceu:steam", 12000))
    .outputFluids(Fluid.of("gtceu:neon", 10000))
    .outputFluids(Fluid.of("gtceu:carbon_dioxide", 5000))
    .outputFluids(Fluid.of("gtceu:helium", 5000))
    .outputFluids(Fluid.of("gtceu:argon", 3000))
    .EUt(480)
    .duration(2000)
  event.recipes.gtceu.centrifuge("alfheim_air")
    .inputFluids(Fluid.of("gtceu:alfheim_air", 10000))
    .outputFluids(Fluid.of("gtceu:mana", 2500))
    .outputFluids(Fluid.of("gtceu:oxygen", 1500))
    .outputFluids(Fluid.of("gtceu:helium", 1000))
    .EUt(120)
    .duration(800)
  // event.recipes.gtceu.distillation_tower("liquid_aether_air")
  //   .inputFluids(Fluid.of("gtceu:aether_air",100000))
  //   .itemOutputs("botania:mana_powder")
  //   .outputFluids(Fluid.of("gtceu:mana",40000))
  //   .outputFluids(Fluid.of("gtceu:oxygen",25000))
  //   .outputFluids(Fluid.of("gtceu:steam",12000))
  //   .outputFluids(Fluid.of("gtceu:neon",10000))
  //   .outputFluids(Fluid.of("gtceu:carbon_dioxide",5000))
  //   .outputFluids(Fluid.of("gtceu:helium",5000))
  //   .outputFluids(Fluid.of("gtceu:argon",3000))
  //   .EUt(480)
  //   .duration(2000)
  event.recipes.gtceu.assembler("barrel")
    .itemInputs("7x #minecraft:planks")
    .itemOutputs("minecraft:barrel")
    .circuit(7)
    .EUt(4)
    .duration(100)
  event.remove({ id: "gtceu:assembler/barrel" })
  event.recipes.gtceu.kinetic_generator("generator")
    .inputFluids(Fluid.of("gtceu:lubricant", 1))
    .inputStress(512)
    .duration(40)
    .EUt(-32)

  event.recipes.gtceu.mixer("chorusite_alloy_dust")
    .itemInputs(["gtceu:andesite_alloy_dust", "2x minecraft:popped_chorus_fruit", "minecraft:dragon_breath"])
    .itemOutputs("4x gtceu:chorusite_alloy_dust")
    .EUt(120)
    .duration(200)

  event.recipes.gtceu.big_dam("big_dam")
    .inputFluids(Fluid.of("gtceu:lubricant", 50))
    .outputStress(1048576)
    .duration(200)

  event.recipes.gtceu.centrifuge('slag')
    .itemInputs('8x gtceu:slag_dust')
    .itemOutputs('3x gtceu:alumina_dust')
    .itemOutputs('3x gtceu:silicon_dioxide_dust')
    .itemOutputs('2x gtceu:magnesia_dust')
    .chancedOutput('gtceu:calcium_sulfide_dust',2500,500)
    .chancedOutput('gtceu:sodium_sulfide_dust',1500,500)
    .EUt(30)
    .duration(288)
  let stones = ['asurine','crimsite','ochrum','veridium']
  stones.forEach(stone =>{
    event.recipes.gtceu.macerator(stone+'_macerator')
      .itemInputs('create:' + stone)
      .itemOutputs('gtceu:' + stone + '_dust')
      .chancedOutput('gtceu:' + stone + '_dust',1500,500)
      .EUt(30)
      .duration(100)
    event.recipes.gtceu.mixer(stone + "_slurry")
      .itemInputs('gtceu:' + stone + '_dust')
      .inputFluids(Fluid.of('gtceu:aqua_regia',3000))
      .outputFluids(Fluid.of('gtceu:' + stone + '_slurry',3000))
      .EUt(480)
      .duration(100)
  })
  event.recipes.gtceu.centrifuge('asurine_dust')
    .itemInputs('gtceu:asurine_dust')
    .itemOutputs('gtceu:silicon_dioxide_dust')
    .itemOutputs('gtceu:small_zinc_dust')
    .chancedOutput('gtceu:small_gallium_dust',1500,250)
    .EUt(30)
    .duration(60)
  event.recipes.gtceu.centrifuge('crimsite_dust')
    .itemInputs('gtceu:crimsite_dust')
    .itemOutputs('gtceu:silicon_dioxide_dust')
    .itemOutputs('gtceu:small_iron_dust')
    .chancedOutput('gtceu:small_cobalt_dust',1500,250)
    .EUt(30)
    .duration(60)
  event.recipes.gtceu.centrifuge('ochrum_dust')
    .itemInputs('gtceu:ochrum_dust')
    .itemOutputs('gtceu:silicon_dioxide_dust')
    .itemOutputs('gtceu:small_precious_alloy_dust')
    .chancedOutput('gtceu:small_silver_dust',1500,250)
    .EUt(30)
    .duration(60)
  event.recipes.gtceu.centrifuge('veridium_dust')
    .itemInputs('gtceu:veridium_dust')
    .itemOutputs('gtceu:silicon_dioxide_dust')
    .itemOutputs('gtceu:small_copper_dust')
    .chancedOutput('gtceu:small_nickel_dust',1500,250)
    .EUt(30)
    .duration(60)
  event.recipes.gtceu.centrifuge('asurine_slurry')
    .inputFluids(Fluid.of('gtceu:asurine_slurry',3000))
    .outputFluids(Fluid.of('gtceu:diluted_hydrochloric_acid',2000))
    .itemOutputs('2x gtceu:small_silicon_dust')
    .itemOutputs('gtceu:zinc_dust')
    .chancedOutput('gtceu:gallium_dust',1000,500)
    .chancedOutput('gtceu:aluminium_dust',1000,250)
    .EUt(480)
    .duration(200)
  event.recipes.gtceu.centrifuge('crimsite_slurry')
    .inputFluids(Fluid.of('gtceu:crimsite_slurry',3000))
    .outputFluids(Fluid.of('gtceu:diluted_hydrochloric_acid',2000))
    .itemOutputs('2x gtceu:small_silicon_dust')
    .itemOutputs('gtceu:iron_dust')
    .chancedOutput('gtceu:cobalt_dust',1000,500)
    .chancedOutput('gtceu:chromium_dust',500,250)
    .EUt(480)
    .duration(200)
  event.recipes.gtceu.centrifuge('ochrum_slurry')
    .inputFluids(Fluid.of('gtceu:ochrum_slurry',3000))
    .outputFluids(Fluid.of('gtceu:diluted_hydrochloric_acid',1000))
    .itemOutputs('2x gtceu:small_silicon_dust')
    .outputFluids(Fluid.of('gtceu:chloroauric_acid',500))
    .chancedOutput('gtceu:silver_dust',1000,500)
    .chancedOutput(Fluid.of('gtceu:mercury'),1000,250)
    .EUt(480)
    .duration(200)
  event.recipes.gtceu.centrifuge('veridium_slurry')
    .inputFluids(Fluid.of('gtceu:veridium_slurry',3000))
    .outputFluids(Fluid.of('gtceu:diluted_hydrochloric_acid',2000))
    .itemOutputs('2x gtceu:small_silicon_dust')
    .itemOutputs('gtceu:copper_dust')
    .chancedOutput('gtceu:nickel_dust',1000,500)
    .chancedOutput('gtceu:tin_dust',1000,250)
    .EUt(480)
    .duration(200)
  function Greenhouse(id, input, fluid, output, boosted) {
        if (boosted) {
            event.recipes.gtceu.greenhouse(id)
                .circuit(2)
                .notConsumable(InputItem.of(input))
                .itemInputs('4x gtceu:fertilizer')
                .inputFluids(Fluid.of('minecraft:water', fluid))
                .itemOutputs(output)
                .duration(320)
                .EUt(120)
        } else {
            event.recipes.gtceu.greenhouse(id)
                .circuit(1)
                .notConsumable(InputItem.of(input))
                .inputFluids(Fluid.of('minecraft:water', fluid))
                .itemOutputs(output)
                .duration(640)
                .EUt(120)
        }
    }
  // Rubber
  Greenhouse('rubber_sapling', 'gtceu:rubber_sapling', 1000, ['32x gtceu:rubber_log', '8x gtceu:sticky_resin', '4x gtceu:rubber_sapling'], false)
  Greenhouse('rubber_sapling_boosted', 'gtceu:rubber_sapling', 1000, ['64x gtceu:rubber_log', '16x gtceu:sticky_resin', '4x gtceu:rubber_sapling'], true)

  // Oak
  Greenhouse('oak_sapling', 'minecraft:oak_sapling', 1000, ['64x minecraft:oak_log', '4x minecraft:oak_sapling'], false)
  Greenhouse('oak_sapling_boosted', 'minecraft:oak_sapling', 1000, ['64x minecraft:oak_log', '64x minecraft:oak_log', '4x minecraft:oak_sapling'], true)

  // Dark Oak
  Greenhouse('dark_oak_sapling', 'minecraft:dark_oak_sapling', 1000, ['64x minecraft:dark_oak_log', '4x minecraft:dark_oak_sapling'], false)
  Greenhouse('dark_oak_sapling_boosted', 'minecraft:dark_oak_sapling', 1000, ['64x minecraft:dark_oak_log', '64x minecraft:dark_oak_log', '4x minecraft:dark_oak_sapling'], true)

  // Spruce
  Greenhouse('spruce_sapling', 'minecraft:spruce_sapling', 1000, ['64x minecraft:spruce_log', '4x minecraft:spruce_sapling'], false)
  Greenhouse('spruce_sapling_boosted', 'minecraft:spruce_sapling', 1000, ['64x minecraft:spruce_log', '64x minecraft:spruce_log', '4x minecraft:spruce_sapling'], true)

  // Birch
  Greenhouse('birch_sapling', 'minecraft:birch_sapling', 1000, ['64x minecraft:birch_log', '4x minecraft:birch_sapling'], false)
  Greenhouse('birch_sapling_boosted', 'minecraft:birch_sapling', 1000, ['64x minecraft:birch_log', '64x minecraft:birch_log', '4x minecraft:birch_sapling'], true)

  // Acacia
  Greenhouse('acacia_sapling', 'minecraft:acacia_sapling', 1000, ['64x minecraft:acacia_log', '4x minecraft:acacia_sapling'], false)
  Greenhouse('acacia_sapling_boosted', 'minecraft:acacia_sapling', 1000, ['64x minecraft:acacia_log', '64x minecraft:acacia_log', '4x minecraft:acacia_sapling'], true)

  // Jungle
  Greenhouse('jungle_sapling', 'minecraft:jungle_sapling', 1000, ['64x minecraft:jungle_log', '4x minecraft:jungle_sapling'], false)
  Greenhouse('jungle_sapling_boosted', 'minecraft:jungle_sapling', 1000, ['64x minecraft:jungle_log', '64x minecraft:jungle_log', '4x minecraft:jungle_sapling'], true)

  // Azalea
  Greenhouse('azalea_sapling', 'minecraft:azalea', 1000, ['64x minecraft:oak_log', '4x minecraft:azalea'], false)
  Greenhouse('azalea_boosted', 'minecraft:azalea', 1000, ['64x minecraft:oak_log', '64x minecraft:oak_log', '4x minecraft:azalea'], true)

  // Flowering Azalea
  Greenhouse('flowering_azalea', 'minecraft:flowering_azalea', 1000, ['64x minecraft:oak_log', '4x minecraft:flowering_azalea'], false)
  Greenhouse('flowering_azalea_boosted', 'minecraft:flowering_azalea', 1000, ['64x minecraft:oak_log', '64x minecraft:oak_log', '4x minecraft:flowering_azalea'], true)

  // Mangrove
  Greenhouse('mangrove_propagule', 'minecraft:mangrove_propagule', 1000, ['64x minecraft:mangrove_log', '4x minecraft:mangrove_propagule'], false)
  Greenhouse('mangrove_propagule_boosted', 'minecraft:mangrove_propagule', 1000, ['64x minecraft:mangrove_log', '64x minecraft:mangrove_log', '4x minecraft:mangrove_propagule'], true)

  ////// Crops //////

  // Sugarcane
  Greenhouse('sugar_cane', 'minecraft:sugar_cane', 1000, '24x minecraft:sugar_cane', false)
  Greenhouse('sugar_cane_boosted', 'minecraft:sugar_cane', 1000, '48x minecraft:sugar_cane', true)

  // Kelp
  Greenhouse('kelp', 'minecraft:kelp', 2000, '24x minecraft:kelp', false)
  Greenhouse('kelp_boosted', 'minecraft:kelp', 2000, '48x minecraft:kelp', true)

  // Bamboo
  Greenhouse('bamboo', 'minecraft:bamboo', 1000, '24x minecraft:bamboo', false)
  Greenhouse('bamboo_boosted', 'minecraft:bamboo', 1000, '48x minecraft:bamboo', true)

  // Cactus
  Greenhouse('cactus', 'minecraft:cactus', 1000, '24x minecraft:cactus', false)
  Greenhouse('cactus_boosted', 'minecraft:cactus', 1000, '48x minecraft:cactus', true)

  // Wheat
  Greenhouse('wheat', 'minecraft:wheat_seeds', 1000, '24x minecraft:wheat', false)
  Greenhouse('wheat_boosted', 'minecraft:wheat_seeds', 1000, '48x minecraft:wheat', true)

  // Carrot
  Greenhouse('carrot', 'minecraft:carrot', 1000, '24x minecraft:carrot', false)
  Greenhouse('carrot_boosted', 'minecraft:carrot', 1000, '48x minecraft:carrot', true)

  // Potato
  Greenhouse('potato', 'minecraft:potato', 1000, '24x minecraft:potato', false)
  Greenhouse('potato_boosted', 'minecraft:potato', 1000, '48x minecraft:potato', true)

  // Beetroot
  Greenhouse('beetroot', 'minecraft:beetroot_seeds', 1000, '24x minecraft:beetroot', false)
  Greenhouse('beetroot_boosted', 'minecraft:beetroot_seeds', 1000, '48x minecraft:beetroot', true)

  // Mellon
  Greenhouse('melon', 'minecraft:melon_seeds', 1000, '12x minecraft:melon', false)
  Greenhouse('melon_boosted', 'minecraft:melon_seeds', 1000, '24x minecraft:melon', true)

  // Pumpkin
  Greenhouse('pumpkin', 'minecraft:pumpkin_seeds', 1000, '12x minecraft:pumpkin', false)
  Greenhouse('pumpkin_boosted', 'minecraft:pumpkin_seeds', 1000, '24x minecraft:pumpkin', true)

  // Nether Wart
  Greenhouse('nether_wart', 'minecraft:nether_wart', 1000, '12x minecraft:nether_wart', false)
  Greenhouse('nether_wart_boosted', 'minecraft:nether_wart', 1000, '24x minecraft:nether_wart', true)

  // Red Mushroom
  Greenhouse('red_mushroom', 'minecraft:red_mushroom', 1000, '12x minecraft:red_mushroom', false)
  Greenhouse('red_mushroom_boosted', 'minecraft:red_mushroom', 1000, '24x minecraft:red_mushroom', true)

  // Brown Mushroom
  Greenhouse('brown_mushroom', 'minecraft:brown_mushroom', 1000, '12x minecraft:brown_mushroom', false)
  Greenhouse('brown_mushroom_boosted', 'minecraft:brown_mushroom', 1000, '24x minecraft:brown_mushroom', true)

  event.recipes.gtceu.greenhouse('rhizobium')
    .circuit(3)
    .duration(640)
    .EUt(120)
    .notConsumable('minecraft:spruce_sapling')
    .itemInputs('4x gtceu:rhizobium_dust')
    .inputFluids(Fluid.of('minecraft:water',1000))
    .itemInputs('4x gtceu:fertilizer')
    .itemOutputs('32x minecraft:spruce_log')
    .itemOutputs('8x gtceu:rhizobium_dust')
    .itemOutputs('50x gtceu:sodium_nitrate_dust')
})
